/**
 * Rich seed products for auto-marketplace demos, sgcarmart-inspired mixed inventory.
 * Pricing in SGD for Singapore demo stores.
 */
import { stockImage } from './richProductCatalog.js';

/** @type {Array<Record<string, unknown>>} */
export const AUTO_MARKETPLACE_SEED_PRODUCTS = [
  // New cars
  {
    name: 'BYD Sealion 7 Electric Performance',
    brand: 'BYD',
    category: 'New Cars',
    unit: 'unit',
    price: 198800,
    marketPrices: { SG: 198800 },
    compare_price: 202388,
    stock: 5,
    sku: 'BYD-S7-PERF',
    description: 'Cat A electric SUV with dual motor AWD and premium equipment.',
    image_url: stockImage('1593941707882-a5bba14938c7', 1200),
    is_featured: true,
    domain_data: {
      vehiclemake: 'BYD',
      vehiclemodel: 'Sealion 7',
      modelyear: '2026',
      mileage: '0',
      fueltype: 'Electric',
      bodytype: 'SUV',
      condition: 'new',
    },
  },
  {
    name: 'Tesla Model Y Electric',
    brand: 'Tesla',
    category: 'New Cars',
    unit: 'unit',
    price: 222999,
    marketPrices: { SG: 222999 },
    stock: 3,
    sku: 'TSLA-MY-2026',
    description: 'Best-selling electric SUV with Autopilot and supercharger access.',
    image_url: stockImage('1560958089-b8a1929cea89', 1200),
    is_featured: true,
    domain_data: {
      vehiclemake: 'Tesla',
      vehiclemodel: 'Model Y',
      modelyear: '2026',
      mileage: '0',
      fueltype: 'Electric',
      bodytype: 'SUV',
      condition: 'new',
    },
  },
  {
    name: 'Honda Odyssey Hybrid 2.0',
    brand: 'Honda',
    category: 'New Cars',
    unit: 'unit',
    price: 236980,
    marketPrices: { SG: 236980 },
    stock: 4,
    sku: 'HON-ODY-HYB',
    description: 'Eight-seat family MPV with Honda Sensing and hybrid efficiency.',
    image_url: stockImage('1544639917-a0f146b8456b', 1200),
    is_featured: true,
    domain_data: {
      vehiclemake: 'Honda',
      vehiclemodel: 'Odyssey Hybrid',
      modelyear: '2025',
      mileage: '0',
      fueltype: 'Hybrid',
      bodytype: 'MPV',
      condition: 'new',
    },
  },
  {
    name: 'Toyota Alphard Hybrid Executive',
    brand: 'Toyota',
    category: 'New Cars',
    unit: 'unit',
    price: 275538,
    marketPrices: { SG: 275538 },
    stock: 2,
    sku: 'TYT-ALP-HYB',
    description: 'Flagship luxury MPV with captain seats and smooth hybrid drivetrain.',
    image_url: stockImage('1621007947382-bb3c3994e3fb', 1200),
    domain_data: {
      vehiclemake: 'Toyota',
      vehiclemodel: 'Alphard Hybrid',
      modelyear: '2025',
      mileage: '0',
      fueltype: 'Hybrid',
      bodytype: 'MPV',
      condition: 'new',
    },
  },
  {
    name: 'Mercedes-Benz GLB Electric',
    brand: 'Mercedes-Benz',
    category: 'New Cars',
    unit: 'unit',
    price: 290888,
    marketPrices: { SG: 290888 },
    stock: 2,
    sku: 'MB-GLB-EV',
    description: 'Premium compact electric SUV with MBUX and fast charging.',
    image_url: stockImage('1618843479313-40f8afb4b4d8', 1200),
    domain_data: {
      vehiclemake: 'Mercedes-Benz',
      vehiclemodel: 'GLB Electric',
      modelyear: '2026',
      mileage: '0',
      fueltype: 'Electric',
      bodytype: 'SUV',
      condition: 'new',
    },
  },
  // Used cars
  {
    name: 'Porsche Cayenne Diesel 3.0A Platinum Edition',
    brand: 'Porsche',
    category: 'Used Cars',
    unit: 'unit',
    price: 218800,
    marketPrices: { SG: 218800 },
    stock: 1,
    sku: 'POR-CAY-USED',
    description: 'New 10-yr COE, low mileage executive SUV.',
    image_url: stockImage('1503376780353-7e6692767b70', 1200),
    is_featured: true,
    domain_data: {
      vehiclemake: 'Porsche',
      vehiclemodel: 'Cayenne',
      modelyear: '2019',
      mileage: '42000',
      fueltype: 'Diesel',
      bodytype: 'SUV',
      condition: 'pre-owned',
    },
  },
  {
    name: 'Honda Shuttle 1.5A G',
    brand: 'Honda',
    category: 'Used Cars',
    unit: 'unit',
    price: 47800,
    marketPrices: { SG: 47800 },
    stock: 1,
    sku: 'HON-SHT-USED',
    description: 'Practical hybrid MPV, one owner, full service history.',
    image_url: stockImage('1590362891991-f776e747a588', 1200),
    is_featured: true,
    domain_data: {
      vehiclemake: 'Honda',
      vehiclemodel: 'Shuttle',
      modelyear: '2020',
      mileage: '68000',
      fueltype: 'Hybrid',
      bodytype: 'MPV',
      condition: 'pre-owned',
    },
  },
  {
    name: 'Toyota Vios 1.5A E',
    brand: 'Toyota',
    category: 'Used Cars',
    unit: 'unit',
    price: 53000,
    marketPrices: { SG: 53000 },
    stock: 2,
    sku: 'TYT-VIOS-USED',
    description: 'Reliable Cat A sedan, ideal first car.',
    image_url: stockImage('1621007947382-bb3c3994e3fb', 1200),
    domain_data: {
      vehiclemake: 'Toyota',
      vehiclemodel: 'Vios',
      modelyear: '2021',
      mileage: '55000',
      fueltype: 'Petrol',
      bodytype: 'Sedan',
      condition: 'pre-owned',
    },
  },
  {
    name: 'Mercedes-Benz GLB180 Mild Hybrid Progressive',
    brand: 'Mercedes-Benz',
    category: 'Used Cars',
    unit: 'unit',
    price: 225888,
    marketPrices: { SG: 225888 },
    stock: 1,
    sku: 'MB-GLB180-USED',
    description: 'Luxury compact SUV with mild hybrid and panoramic roof.',
    image_url: stockImage('1618843479313-40f8afb4b4d8', 1200),
    domain_data: {
      vehiclemake: 'Mercedes-Benz',
      vehiclemodel: 'GLB180',
      modelyear: '2022',
      mileage: '32000',
      fueltype: 'Hybrid',
      bodytype: 'SUV',
      condition: 'pre-owned',
    },
  },
  {
    name: 'Lexus ES250 Executive Sunroof',
    brand: 'Lexus',
    category: 'Used Cars',
    unit: 'unit',
    price: 86800,
    marketPrices: { SG: 86800 },
    stock: 1,
    sku: 'LEX-ES250-USED',
    description: 'Executive sedan with sunroof, immaculate condition.',
    image_url: stockImage('1617814076665-75e412d1d0cd', 1200),
    domain_data: {
      vehiclemake: 'Lexus',
      vehiclemodel: 'ES250',
      modelyear: '2018',
      mileage: '72000',
      fueltype: 'Petrol',
      bodytype: 'Luxury',
      condition: 'pre-owned',
    },
  },
  {
    name: 'Audi A4 2.0A TFSI S-tronic',
    brand: 'Audi',
    category: 'Used Cars',
    unit: 'unit',
    price: 70700,
    marketPrices: { SG: 70700 },
    stock: 1,
    sku: 'AUD-A4-USED',
    description: 'Sporty executive sedan, COE till 2029.',
    image_url: stockImage('1606664515524-ed2f786a0bd6', 1200),
    domain_data: {
      vehiclemake: 'Audi',
      vehiclemodel: 'A4',
      modelyear: '2017',
      mileage: '89000',
      fueltype: 'Petrol',
      bodytype: 'Sedan',
      condition: 'pre-owned',
    },
  },
  // Rental
  {
    name: 'Toyota Corolla Altis, Monthly Rental',
    brand: 'Toyota',
    category: 'Rental Cars',
    unit: 'unit',
    price: 1680,
    marketPrices: { SG: 1680 },
    stock: 10,
    sku: 'RENT-COR-ALT',
    description: 'Long-term personal lease from $1,680/month, insurance included.',
    image_url: stockImage('1621007947382-bb3c3994e3fb', 1200),
    is_featured: true,
    domain_data: {
      vehiclemake: 'Toyota',
      vehiclemodel: 'Corolla Altis',
      modelyear: '2024',
      mileage: '0',
      fueltype: 'Petrol',
      bodytype: 'Sedan',
      condition: 'rental',
    },
  },
  {
    name: 'Honda Vezel Hybrid, Weekend Rental',
    brand: 'Honda',
    category: 'Rental Cars',
    unit: 'unit',
    price: 128,
    marketPrices: { SG: 128 },
    stock: 8,
    sku: 'RENT-VEZ-DAY',
    description: 'Short-term rental from $128/day, unlimited mileage option.',
    image_url: stockImage('1590362891991-f776e747a588', 1200),
    domain_data: {
      vehiclemake: 'Honda',
      vehiclemodel: 'Vezel',
      modelyear: '2023',
      mileage: '0',
      fueltype: 'Hybrid',
      bodytype: 'SUV',
      condition: 'rental',
    },
  },
  {
    name: 'Mercedes-Benz E-Class, Wedding Chauffeur',
    brand: 'Mercedes-Benz',
    category: 'Rental Cars',
    unit: 'unit',
    price: 450,
    marketPrices: { SG: 450 },
    stock: 3,
    sku: 'RENT-E-CLASS',
    description: 'Premium wedding car package with chauffeur, 4 hours from $450.',
    image_url: stockImage('1618843479313-40f8afb4b4d8', 1200),
    domain_data: {
      vehiclemake: 'Mercedes-Benz',
      vehiclemodel: 'E-Class',
      modelyear: '2022',
      mileage: '0',
      fueltype: 'Petrol',
      bodytype: 'Luxury',
      condition: 'rental',
    },
  },
  // e-Shop parts
  {
    name: 'Dunlop SP Sport LM705 Tyre (2025)',
    brand: 'Dunlop',
    category: 'Tyres',
    unit: 'pcs',
    price: 114.45,
    marketPrices: { SG: 114.45 },
    stock: 48,
    sku: 'DUN-LM705',
    description: 'Premium touring tyre, sizes 195/65R15 to 225/50R17.',
    image_url: stockImage('1486262715619-67b85e0b08d3', 800),
    is_featured: true,
    domain_data: { parttype: 'Tyre', brand: 'Dunlop' },
  },
  {
    name: 'Bridgestone Ecopia EP300 Tyre (2025)',
    brand: 'Bridgestone',
    category: 'Tyres',
    unit: 'pcs',
    price: 120.99,
    marketPrices: { SG: 120.99 },
    stock: 36,
    sku: 'BRI-EP300',
    description: 'Fuel-saving eco tyre with low rolling resistance.',
    image_url: stockImage('1486262715619-67b85e0b08d3', 800),
    domain_data: { parttype: 'Tyre', brand: 'Bridgestone' },
  },
  {
    name: 'Kumho Crugen HP71 Tyre (2024)',
    brand: 'Kumho',
    category: 'Tyres',
    unit: 'pcs',
    price: 163.50,
    marketPrices: { SG: 163.50 },
    stock: 24,
    sku: 'KUM-HP71',
    description: 'SUV all-season tyre with excellent wet grip.',
    image_url: stockImage('1486262715619-67b85e0b08d3', 800),
    domain_data: { parttype: 'Tyre', brand: 'Kumho' },
  },
  {
    name: 'CWORKS Certified Performance Wiper (2pcs)',
    brand: 'CWORKS',
    category: 'Parts & Accessories',
    unit: 'set',
    price: 32.70,
    marketPrices: { SG: 32.70 },
    stock: 120,
    sku: 'CWK-WIPER-2',
    description: 'All-weather performance wiper blades, universal fit.',
    image_url: stockImage('1625047509248-ec889cbff817', 800),
    domain_data: { parttype: 'Wiper', brand: 'CWORKS' },
  },
  {
    name: 'Bosch S5 Car Battery  DIN74',
    brand: 'Bosch',
    category: 'Batteries',
    unit: 'pcs',
    price: 198.00,
    marketPrices: { SG: 198.00 },
    stock: 30,
    sku: 'BOS-S5-DIN74',
    description: 'Maintenance-free AGM battery with 3-year warranty.',
    image_url: stockImage('1625047509248-ec889cbff817', 800),
    domain_data: { parttype: 'Battery', brand: 'Bosch' },
  },
  {
    name: 'Meguiar\'s Gold Class Car Wash Kit',
    brand: 'Meguiar\'s',
    category: 'Car Grooming',
    unit: 'set',
    price: 45.90,
    marketPrices: { SG: 45.90 },
    stock: 60,
    sku: 'MEG-GOLD-KIT',
    description: 'Complete wash & wax kit for showroom shine at home.',
    image_url: stockImage('1486262715619-67b85e0b08d3', 800),
    domain_data: { parttype: 'Grooming', brand: "Meguiar's" },
  },
  {
    name: 'Shell Helix Ultra 5W-40 Engine Oil (4L)',
    brand: 'Shell',
    category: 'Engine Oil',
    unit: 'pcs',
    price: 68.50,
    marketPrices: { SG: 68.50 },
    stock: 80,
    sku: 'SHL-5W40-4L',
    description: 'Fully synthetic engine oil for modern petrol engines.',
    image_url: stockImage('1625047509248-ec889cbff817', 800),
    domain_data: { parttype: 'Engine Oil', brand: 'Shell' },
  },
  // More new cars
  {
    name: 'Proton e.MAS 5 Electric',
    brand: 'Proton',
    category: 'New Cars',
    unit: 'unit',
    price: 164988,
    marketPrices: { SG: 164988 },
    compare_price: 172800,
    stock: 6,
    sku: 'PRT-EMAS5-EV',
    description: 'Cat A electric hatchback with 410km range and fast-charge support.',
    image_url: stockImage('1609521263047-f8f205293f24', 1200),
    is_featured: true,
    domain_data: {
      vehiclemake: 'Proton',
      vehiclemodel: 'e.MAS 5',
      modelyear: '2026',
      mileage: '0',
      fueltype: 'Electric',
      transmission: 'Single-speed',
      bodytype: 'Hatchback',
      condition: 'new',
    },
  },
  {
    name: 'Toyota RAV4 Hybrid 2.5',
    brand: 'Toyota',
    category: 'New Cars',
    unit: 'unit',
    price: 248888,
    marketPrices: { SG: 248888 },
    stock: 4,
    sku: 'TYT-RAV4-HYB',
    description: 'Rugged hybrid SUV with Toyota Safety Sense and all-wheel drive.',
    image_url: stockImage('1542362565-777542eab9da', 1200),
    is_featured: true,
    domain_data: {
      vehiclemake: 'Toyota',
      vehiclemodel: 'RAV4 Hybrid',
      modelyear: '2026',
      mileage: '0',
      fueltype: 'Hybrid',
      transmission: 'CVT',
      bodytype: 'SUV',
      condition: 'new',
    },
  },
  {
    name: 'Toyota Noah Hybrid MYCAR Edition',
    brand: 'Toyota',
    category: 'New Cars',
    unit: 'unit',
    price: 213988,
    marketPrices: { SG: 213988 },
    compare_price: 218800,
    stock: 5,
    sku: 'TYT-NOAH-MYCAR',
    description: '$0 driveaway promo, eight-seat MPV with captain seats and hybrid efficiency.',
    image_url: stockImage('1544639917-a0f146b8456b', 1200),
    domain_data: {
      vehiclemake: 'Toyota',
      vehiclemodel: 'Noah Hybrid',
      modelyear: '2026',
      mileage: '0',
      fueltype: 'Hybrid',
      transmission: 'CVT',
      bodytype: 'MPV',
      condition: 'new',
    },
  },
  {
    name: 'Honda Stepwgn Hybrid 1.5',
    brand: 'Honda',
    category: 'New Cars',
    unit: 'unit',
    price: 222595,
    marketPrices: { SG: 222595 },
    stock: 3,
    sku: 'HON-STPWGN-HYB',
    description: 'Spacious seven-seat MPV with wide-opening doors and e:HEV hybrid.',
    image_url: stockImage('1494976388531-d1058498ceb8', 1200),
    domain_data: {
      vehiclemake: 'Honda',
      vehiclemodel: 'Stepwgn Hybrid',
      modelyear: '2025',
      mileage: '0',
      fueltype: 'Hybrid',
      transmission: 'e-CVT',
      bodytype: 'MPV',
      condition: 'new',
    },
  },
  {
    name: 'ZEEKR 7X Electric',
    brand: 'ZEEKR',
    category: 'New Cars',
    unit: 'unit',
    price: 256999,
    marketPrices: { SG: 256999 },
    stock: 2,
    sku: 'ZEK-7X-EV',
    description: 'Premium electric SUV with 800V architecture and advanced driver assist.',
    image_url: stockImage('1593941707882-a5bba14938c7', 1200),
    is_featured: true,
    domain_data: {
      vehiclemake: 'ZEEKR',
      vehiclemodel: '7X',
      modelyear: '2026',
      mileage: '0',
      fueltype: 'Electric',
      transmission: 'Single-speed',
      bodytype: 'SUV',
      condition: 'new',
    },
  },
  {
    name: 'Jaecoo 6 Electric',
    brand: 'Jaecoo',
    category: 'New Cars',
    unit: 'unit',
    price: 174999,
    marketPrices: { SG: 174999 },
    stock: 4,
    sku: 'JCO-6-EV',
    description: 'Stylish Cat A electric SUV with off-road styling and generous equipment.',
    image_url: stockImage('1542362565-777542eab9da', 1200),
    domain_data: {
      vehiclemake: 'Jaecoo',
      vehiclemodel: '6',
      modelyear: '2026',
      mileage: '0',
      fueltype: 'Electric',
      transmission: 'Single-speed',
      bodytype: 'SUV',
      condition: 'new',
    },
  },
  {
    name: 'BYD Seal 6 Touring Plug-in Hybrid',
    brand: 'BYD',
    category: 'New Cars',
    unit: 'unit',
    price: 191888,
    marketPrices: { SG: 191888 },
    stock: 3,
    sku: 'BYD-S6-PHEV',
    description: 'Estate PHEV with Blade Battery safety and up to 1,200km combined range.',
    image_url: stockImage('1619767886555-efdc259cde1a', 1200),
    domain_data: {
      vehiclemake: 'BYD',
      vehiclemodel: 'Seal 6 Touring',
      modelyear: '2026',
      mileage: '0',
      fueltype: 'Plug-in Hybrid',
      transmission: 'Single-speed',
      bodytype: 'Stationwagon',
      condition: 'new',
    },
  },
  {
    name: 'GAC Aion Y Plus Electric',
    brand: 'GAC',
    category: 'New Cars',
    unit: 'unit',
    price: 158800,
    marketPrices: { SG: 158800 },
    stock: 5,
    sku: 'GAC-AIONY-NEW',
    description: 'Spacious electric crossover with ADAS Level 2 and panoramic sunroof option.',
    image_url: stockImage('1617788138017-80ad40651399', 1200),
    domain_data: {
      vehiclemake: 'GAC',
      vehiclemodel: 'Aion Y Plus',
      modelyear: '2026',
      mileage: '0',
      fueltype: 'Electric',
      transmission: 'Single-speed',
      bodytype: 'SUV',
      condition: 'new',
    },
  },
  {
    name: 'Honda Super-ONE Electric',
    brand: 'Honda',
    category: 'New Cars',
    unit: 'unit',
    price: 201999,
    marketPrices: { SG: 201999 },
    stock: 2,
    sku: 'HON-SUPER1-EV',
    description: 'All-electric seven-seater MPV with Honda Sensing and V2L power export.',
    image_url: stockImage('1593941707882-a5bba14938c7', 1200),
    domain_data: {
      vehiclemake: 'Honda',
      vehiclemodel: 'Super-ONE',
      modelyear: '2026',
      mileage: '0',
      fueltype: 'Electric',
      transmission: 'Single-speed',
      bodytype: 'MPV',
      condition: 'new',
    },
  },
  {
    name: 'DEEPAL S05 Electric',
    brand: 'DEEPAL',
    category: 'New Cars',
    unit: 'unit',
    price: 187999,
    marketPrices: { SG: 187999 },
    stock: 3,
    sku: 'DPL-S05-EV',
    description: 'Cat A electric SUV with extended range battery and premium cabin.',
    image_url: stockImage('1593941707882-a5bba14938c7', 1200),
    domain_data: {
      vehiclemake: 'DEEPAL',
      vehiclemodel: 'S05',
      modelyear: '2026',
      mileage: '0',
      fueltype: 'Electric',
      transmission: 'Single-speed',
      bodytype: 'SUV',
      condition: 'new',
    },
  },
  {
    name: 'BMW iX3 Electric',
    brand: 'BMW',
    category: 'New Cars',
    unit: 'unit',
    price: 387888,
    marketPrices: { SG: 387888 },
    stock: 2,
    sku: 'BMW-IX3-EV',
    description: 'Premium electric SUV with BMW Curved Display and 460km WLTP range.',
    image_url: stockImage('1555215695-3004980ad54e', 1200),
    domain_data: {
      vehiclemake: 'BMW',
      vehiclemodel: 'iX3',
      modelyear: '2026',
      mileage: '0',
      fueltype: 'Electric',
      transmission: 'Single-speed',
      bodytype: 'SUV',
      condition: 'new',
    },
  },
  // More used / pre-owned
  {
    name: 'BMW 320i M Sport 2.0A',
    brand: 'BMW',
    category: 'Pre-Owned',
    unit: 'unit',
    price: 158000,
    marketPrices: { SG: 158000 },
    stock: 1,
    sku: 'BMW-320I-USED',
    description: 'Depreciation approx. $14,200/yr, COE till 08/2030, low mileage M Sport.',
    image_url: stockImage('1555215695-3004980ad54e', 1200),
    is_featured: true,
    domain_data: {
      vehiclemake: 'BMW',
      vehiclemodel: '320i M Sport',
      modelyear: '2021',
      mileage: '38000',
      fueltype: 'Petrol',
      transmission: '8AT',
      bodytype: 'Sedan',
      condition: 'pre-owned',
    },
  },
  {
    name: 'Mercedes-Benz C-Class C200 Avantgarde',
    brand: 'Mercedes-Benz',
    category: 'Used Cars',
    unit: 'unit',
    price: 91800,
    marketPrices: { SG: 91800 },
    stock: 1,
    sku: 'MB-C200-USED',
    description: 'Depreciation approx. $11,800/yr, executive sedan, COE till 06/2029.',
    image_url: stockImage('1618843479313-40f8afb4b4d8', 1200),
    is_featured: true,
    domain_data: {
      vehiclemake: 'Mercedes-Benz',
      vehiclemodel: 'C200 Avantgarde',
      modelyear: '2019',
      mileage: '65000',
      fueltype: 'Petrol',
      transmission: '9G-TRONIC',
      bodytype: 'Sedan',
      condition: 'pre-owned',
    },
  },
  {
    name: 'Toyota Alphard 2.5A Elegance Moonroof',
    brand: 'Toyota',
    category: 'Used Cars',
    unit: 'unit',
    price: 166880,
    marketPrices: { SG: 166880 },
    stock: 1,
    sku: 'TYT-ALP-USED',
    description: 'Depreciation approx. $18,500/yr, luxury MPV with moonroof, one owner.',
    image_url: stockImage('1621007947382-bb3c3994e3fb', 1200),
    is_featured: true,
    domain_data: {
      vehiclemake: 'Toyota',
      vehiclemodel: 'Alphard',
      modelyear: '2020',
      mileage: '58000',
      fueltype: 'Petrol',
      transmission: 'CVT',
      bodytype: 'MPV',
      condition: 'pre-owned',
    },
  },
  {
    name: 'Volvo XC90 T5 Momentum',
    brand: 'Volvo',
    category: 'Used Cars',
    unit: 'unit',
    price: 56900,
    marketPrices: { SG: 56900 },
    stock: 1,
    sku: 'VOL-XC90-USED',
    description: 'Depreciation approx. $9,200/yr, seven-seat family SUV, full service history.',
    image_url: stockImage('1544636331-e26879cd4d9b', 1200),
    domain_data: {
      vehiclemake: 'Volvo',
      vehiclemodel: 'XC90 T5',
      modelyear: '2018',
      mileage: '82000',
      fueltype: 'Petrol',
      transmission: '8AT',
      bodytype: 'SUV',
      condition: 'pre-owned',
    },
  },
  {
    name: 'Porsche Macan 2.0A PDK',
    brand: 'Porsche',
    category: 'Used Cars',
    unit: 'unit',
    price: 98800,
    marketPrices: { SG: 98800 },
    stock: 1,
    sku: 'POR-MACAN-USED',
    description: 'Depreciation approx. $16,400/yr, compact sports SUV, COE till 11/2029.',
    image_url: stockImage('1503376780353-7e6692767b70', 1200),
    is_featured: true,
    domain_data: {
      vehiclemake: 'Porsche',
      vehiclemodel: 'Macan',
      modelyear: '2018',
      mileage: '71000',
      fueltype: 'Petrol',
      transmission: 'PDK',
      bodytype: 'SUV',
      condition: 'pre-owned',
    },
  },
  {
    name: 'Hyundai Avante 1.6A (COE till 12/2028)',
    brand: 'Hyundai',
    category: 'Used Cars',
    unit: 'unit',
    price: 26800,
    marketPrices: { SG: 26800 },
    stock: 2,
    sku: 'HYU-AVT-USED',
    description: 'Depreciation approx. $6,800/yr, budget-friendly Cat A sedan, well maintained.',
    image_url: stockImage('1552519507-da3b142c6e3d', 1200),
    domain_data: {
      vehiclemake: 'Hyundai',
      vehiclemodel: 'Avante',
      modelyear: '2016',
      mileage: '95000',
      fueltype: 'Petrol',
      transmission: '6AT',
      bodytype: 'Sedan',
      condition: 'pre-owned',
    },
  },
  {
    name: 'Mazda 3 1.5A Deluxe',
    brand: 'Mazda',
    category: 'Used Cars',
    unit: 'unit',
    price: 13500,
    marketPrices: { SG: 13500 },
    stock: 1,
    sku: 'MAZ-3-USED',
    description: 'Depreciation approx. $4,200/yr, renewed COE, ideal budget runabout.',
    image_url: stockImage('1492144534655-ae79c964c9d7', 1200),
    domain_data: {
      vehiclemake: 'Mazda',
      vehiclemodel: '3',
      modelyear: '2014',
      mileage: '112000',
      fueltype: 'Petrol',
      transmission: '6AT',
      bodytype: 'Hatchback',
      condition: 'pre-owned',
    },
  },
  {
    name: 'Mercedes-Benz GLC250 Sport 4MATIC',
    brand: 'Mercedes-Benz',
    category: 'Used Cars',
    unit: 'unit',
    price: 52400,
    marketPrices: { SG: 52400 },
    stock: 1,
    sku: 'MB-GLC250-USED',
    description: 'Depreciation approx. $10,100/yr, AWD compact SUV, COE till 04/2028.',
    image_url: stockImage('1618843479313-40f8afb4b4d8', 1200),
    domain_data: {
      vehiclemake: 'Mercedes-Benz',
      vehiclemodel: 'GLC250',
      modelyear: '2017',
      mileage: '78000',
      fueltype: 'Petrol',
      transmission: '9G-TRONIC',
      bodytype: 'SUV',
      condition: 'pre-owned',
    },
  },
  {
    name: 'Toyota Vellfire 2.5A Elegance Moonroof',
    brand: 'Toyota',
    category: 'Used Cars',
    unit: 'unit',
    price: 166880,
    marketPrices: { SG: 166880 },
    stock: 1,
    sku: 'TYT-VLF-USED',
    description: 'Depreciation approx. $17,900/yr, premium MPV with captain seats and moonroof.',
    image_url: stockImage('1617814076665-75e412d1d0cd', 1200),
    domain_data: {
      vehiclemake: 'Toyota',
      vehiclemodel: 'Vellfire',
      modelyear: '2019',
      mileage: '62000',
      fueltype: 'Petrol',
      transmission: 'CVT',
      bodytype: 'MPV',
      condition: 'pre-owned',
    },
  },
  {
    name: 'Audi Q3 1.4A TFSI S-tronic',
    brand: 'Audi',
    category: 'Used Cars',
    unit: 'unit',
    price: 101800,
    marketPrices: { SG: 101800 },
    stock: 1,
    sku: 'AUD-Q3-USED',
    description: 'Depreciation approx. $13,600/yr, compact luxury SUV, COE till 02/2030.',
    image_url: stockImage('1606664515524-ed2f786a0bd6', 1200),
    domain_data: {
      vehiclemake: 'Audi',
      vehiclemodel: 'Q3',
      modelyear: '2019',
      mileage: '55000',
      fueltype: 'Petrol',
      transmission: 'S-tronic',
      bodytype: 'SUV',
      condition: 'pre-owned',
    },
  },
  {
    name: 'Porsche Boxster S 3.4A PDK (COE till 03/2029)',
    brand: 'Porsche',
    category: 'Used Cars',
    unit: 'unit',
    price: 62800,
    marketPrices: { SG: 62800 },
    stock: 1,
    sku: 'POR-BOX-USED',
    description: 'Depreciation approx. $12,900/yr, convertible sports car, weekend driver.',
    image_url: stockImage('1519641471654-642cd0f66eda', 1200),
    domain_data: {
      vehiclemake: 'Porsche',
      vehiclemodel: 'Boxster S',
      modelyear: '2016',
      mileage: '68000',
      fueltype: 'Petrol',
      transmission: 'PDK',
      bodytype: 'Sports',
      condition: 'pre-owned',
    },
  },
  {
    name: 'Mercedes-Benz E-Class E250 Avantgarde',
    brand: 'Mercedes-Benz',
    category: 'Pre-Owned',
    unit: 'unit',
    price: 91800,
    marketPrices: { SG: 91800 },
    stock: 1,
    sku: 'MB-E250-USED',
    description: 'Depreciation approx. $11,500/yr, executive sedan with panoramic roof.',
    image_url: stockImage('1616422283683-0871ad66bfd7', 1200),
    domain_data: {
      vehiclemake: 'Mercedes-Benz',
      vehiclemodel: 'E250 Avantgarde',
      modelyear: '2018',
      mileage: '74000',
      fueltype: 'Petrol',
      transmission: '9G-TRONIC',
      bodytype: 'Luxury',
      condition: 'pre-owned',
    },
  },
  // More rental
  {
    name: 'Toyota Hiace Van, Daily Rental',
    brand: 'Toyota',
    category: 'Rental Cars',
    unit: 'unit',
    price: 95,
    marketPrices: { SG: 95 },
    stock: 6,
    sku: 'RENT-HIACE-DAY',
    description: 'Commercial van rental from $95/day, ideal for movers and deliveries.',
    image_url: stockImage('1583121274602-3c12800fd3b5', 1200),
    domain_data: {
      vehiclemake: 'Toyota',
      vehiclemodel: 'Hiace',
      modelyear: '2023',
      mileage: '0',
      fueltype: 'Diesel',
      transmission: '6MT',
      bodytype: 'Van',
      condition: 'rental',
    },
  },
  {
    name: 'Nissan Serena Hybrid, P-Plate Rental',
    brand: 'Nissan',
    category: 'Rental Cars',
    unit: 'unit',
    price: 88,
    marketPrices: { SG: 88 },
    stock: 12,
    sku: 'RENT-SER-PPL',
    description: 'Probation driver friendly from $88/day, insurance and roadside assist included.',
    image_url: stockImage('1517048676732-2162716b9996', 1200),
    is_featured: true,
    domain_data: {
      vehiclemake: 'Nissan',
      vehiclemodel: 'Serena',
      modelyear: '2024',
      mileage: '0',
      fueltype: 'Hybrid',
      transmission: 'CVT',
      bodytype: 'MPV',
      condition: 'rental',
    },
  },
  {
    name: 'BMW 320i, Daily Rental',
    brand: 'BMW',
    category: 'Rental Cars',
    unit: 'unit',
    price: 185,
    marketPrices: { SG: 185 },
    stock: 4,
    sku: 'RENT-BMW320-DAY',
    description: 'Premium daily rental from $185/day, unlimited mileage weekend package available.',
    image_url: stockImage('1555215695-3004980ad54e', 1200),
    domain_data: {
      vehiclemake: 'BMW',
      vehiclemodel: '320i',
      modelyear: '2024',
      mileage: '0',
      fueltype: 'Petrol',
      transmission: '8AT',
      bodytype: 'Sedan',
      condition: 'rental',
    },
  },
  {
    name: 'Honda Civic 1.5 Turbo, Monthly Lease',
    brand: 'Honda',
    category: 'Rental Cars',
    unit: 'unit',
    price: 1890,
    marketPrices: { SG: 1890 },
    stock: 8,
    sku: 'RENT-CIV-LEASE',
    description: 'Long-term personal lease from $1,890/month, maintenance and insurance bundled.',
    image_url: stockImage('1492144534655-ae79c964c9d7', 1200),
    domain_data: {
      vehiclemake: 'Honda',
      vehiclemodel: 'Civic Turbo',
      modelyear: '2024',
      mileage: '0',
      fueltype: 'Petrol',
      transmission: 'CVT',
      bodytype: 'Sedan',
      condition: 'rental',
    },
  },
  // More e-Shop
  {
    name: 'Dunlop SP Sport Maxx 060+ Tyre (2025)',
    brand: 'Dunlop',
    category: 'Tyres',
    unit: 'pcs',
    price: 156.96,
    marketPrices: { SG: 156.96 },
    stock: 32,
    sku: 'DUN-MAXX060',
    description: 'Ultra-high performance tyre, sizes 205/55R16 to 245/40R18.',
    image_url: stockImage('1486262715619-67b85e0b08d3', 800),
    domain_data: { parttype: 'Tyre', brand: 'Dunlop' },
  },
  {
    name: 'Bridgestone Alenza 001 Tyre (2025)',
    brand: 'Bridgestone',
    category: 'Tyres',
    unit: 'pcs',
    price: 185.30,
    marketPrices: { SG: 185.30 },
    stock: 28,
    sku: 'BRI-ALZ001',
    description: 'Premium SUV tyre with Enliten technology for lower rolling resistance.',
    image_url: stockImage('1486262715619-67b85e0b08d3', 800),
    is_featured: true,
    domain_data: { parttype: 'Tyre', brand: 'Bridgestone' },
  },
  {
    name: 'Pirelli Cinturato Rosso Seal Inside Tyre (2025)',
    brand: 'Pirelli',
    category: 'Tyres',
    unit: 'pcs',
    price: 210.21,
    marketPrices: { SG: 210.21 },
    stock: 20,
    sku: 'PIR-ROSSO-SI',
    description: 'Run-flat capable touring tyre with Seal Inside puncture protection.',
    image_url: stockImage('1486262715619-67b85e0b08d3', 800),
    domain_data: { parttype: 'Tyre', brand: 'Pirelli' },
  },
  {
    name: 'Dunlop Enasave EC300+ Tyre (2026)',
    brand: 'Dunlop',
    category: 'Tyres',
    unit: 'pcs',
    price: 155.87,
    marketPrices: { SG: 155.87 },
    stock: 40,
    sku: 'DUN-EC300P',
    description: 'Fuel-saving eco tyre with excellent wet braking performance.',
    image_url: stockImage('1486262715619-67b85e0b08d3', 800),
    domain_data: { parttype: 'Tyre', brand: 'Dunlop' },
  },
  {
    name: 'Dunlop SP Touring R1 Tyre (2025)',
    brand: 'Dunlop',
    category: 'Tyres',
    unit: 'pcs',
    price: 83.93,
    marketPrices: { SG: 83.93 },
    stock: 56,
    sku: 'DUN-R1-TOUR',
    description: 'Budget-friendly touring tyre for compact sedans and hatchbacks.',
    image_url: stockImage('1486262715619-67b85e0b08d3', 800),
    domain_data: { parttype: 'Tyre', brand: 'Dunlop' },
  },
  {
    name: 'Autoglym Super Resin Polish (500ml)',
    brand: 'Autoglym',
    category: 'Car Grooming',
    unit: 'pcs',
    price: 28.50,
    marketPrices: { SG: 28.50 },
    stock: 90,
    sku: 'AGL-SRP-500',
    description: 'Award-winning polish for deep gloss and lasting paint protection.',
    image_url: stockImage('1580273916550-bfc281217630', 800),
    domain_data: { parttype: 'Grooming', brand: 'Autoglym' },
  },
  {
    name: '3M Scotchgard Paint Protection Film (Front Kit)',
    brand: '3M',
    category: 'Parts & Accessories',
    unit: 'set',
    price: 880.00,
    marketPrices: { SG: 880.00 },
    compare_price: 980.00,
    stock: 12,
    sku: '3M-PPF-FRONT',
    description: 'Self-healing PPF for bonnet, bumper, and headlamps, professional install recommended.',
    image_url: stockImage('1580273916550-bfc281217630', 800),
    is_featured: true,
    domain_data: { parttype: 'Paint Protection', brand: '3M' },
  },
  {
    name: 'Varta Blue Dynamic E11 Battery (74Ah)',
    brand: 'Varta',
    category: 'Batteries',
    unit: 'pcs',
    price: 168.00,
    marketPrices: { SG: 168.00 },
    stock: 45,
    sku: 'VAR-E11-74AH',
    description: 'Maintenance-free battery for European and Japanese sedans.',
    image_url: stockImage('1625047509248-ec889cbff817', 800),
    domain_data: { parttype: 'Battery', brand: 'Varta' },
  },
  {
    name: 'Kenwood DMX7021DABS Car Audio Head Unit',
    brand: 'Kenwood',
    category: 'Parts & Accessories',
    unit: 'pcs',
    price: 549.00,
    marketPrices: { SG: 549.00 },
    stock: 15,
    sku: 'KEN-DMX7021',
    description: '6.8" wireless CarPlay/Android Auto with DAB+ and HD rear camera input.',
    image_url: stockImage('1550355291-bbee03df35d8', 800),
    domain_data: { parttype: 'Audio', brand: 'Kenwood' },
  },
  {
    name: 'Xpel Prime XR Plus Solar Film (Full Car)',
    brand: 'Xpel',
    category: 'Parts & Accessories',
    unit: 'set',
    price: 1280.00,
    marketPrices: { SG: 1280.00 },
    stock: 8,
    sku: 'XPL-XR-FULL',
    description: 'Ceramic tint package with 98% IR heat rejection, LTA-compliant VLT options.',
    image_url: stockImage('1580273916550-bfc281217630', 800),
    domain_data: { parttype: 'Solar Film', brand: 'Xpel' },
  },
  {
    name: 'Michelin Pilot Sport 4 Tyre (2025)',
    brand: 'Michelin',
    category: 'Tyres',
    unit: 'pcs',
    price: 198.50,
    marketPrices: { SG: 198.50 },
    stock: 22,
    sku: 'MIC-PS4-2025',
    description: 'Max-performance summer tyre for sports sedans and coupes.',
    image_url: stockImage('1486262715619-67b85e0b08d3', 800),
    domain_data: { parttype: 'Tyre', brand: 'Michelin' },
  },
  {
    name: 'Liqui Moly Engine Flush (300ml)',
    brand: 'Liqui Moly',
    category: 'Engine Oil',
    unit: 'pcs',
    price: 18.90,
    marketPrices: { SG: 18.90 },
    stock: 100,
    sku: 'LM-ENG-FLUSH',
    description: 'Pre-oil-change flush to remove sludge and deposits.',
    image_url: stockImage('1625047509248-ec889cbff817', 800),
    domain_data: { parttype: 'Additive', brand: 'Liqui Moly' },
  },
];
