/**
 * Gul Ahmed–inspired homepage section seeds (The Home Edit + Sale mosaic).
 * Generated by scripts/build-fashion-gul-sections.mjs — re-run after updating gulahmed.html.
 */

// Home Edit — fixed tile seeds (HTML scrape may fail on minified markup)
const GUL_AHMED_HOME_EDIT_TILES = [
  {
    id: 'bedding-hero',
    slot: 'hero',
    eyebrow: 'Ideas Home Bedding',
    title: 'Create a home that feels soft, welcoming, and full of love.',
    ctaLabel: 'Explore',
    href: '?category=bedding',
    image: 'https://www.gulahmedshop.com/cdn/shop/files/grid-item-1_534x.webp?v=1773294610',
  },
  {
    id: 'bedding-basics',
    slot: 'banner',
    eyebrow: 'Bedding Basics',
    title: 'The Anatomy of a Restful Sleep',
    ctaLabel: 'Explore',
    href: '?category=bedding',
    image: 'https://www.gulahmedshop.com/cdn/shop/files/grid-item-2_534x.webp?v=1773294610',
  },
  {
    id: 'bath-linen',
    slot: 'half-left',
    eyebrow: 'Bath Linen',
    ctaLabel: 'Explore',
    href: '?category=bath-linen',
    image: 'https://www.gulahmedshop.com/cdn/shop/files/grid-item-3_270x.webp?v=1773294610',
  },
  {
    id: 'plates-platters',
    slot: 'half-right',
    eyebrow: 'Plates & Platters',
    ctaLabel: 'Explore',
    href: '?category=home-accessories',
    image: 'https://www.gulahmedshop.com/cdn/shop/files/grid-item-4_1bbc4850-38b2-4ba5-9986-b0a49b7317ea_270x.webp?v=1773294731',
  },
];

export const GUL_AHMED_HOME_EDIT = {
  title: 'The Home Edit',
  subtitle:
    'Elevate everyday living with premium linens, essentials & home accessories, crafted for comfort, style and home harmony',
  viewAllHref: '?category=home',
  tiles: GUL_AHMED_HOME_EDIT_TILES,
};

/** Apparel-focused Home Edit for boutique / garments storefronts. */
export const BOUTIQUE_HOME_EDIT = {
  title: 'The Style Edit',
  subtitle:
    'Curated unstitched fabrics, ready-to-wear pret, and finishing accessories for every season and occasion.',
  viewAllHref: '?sort=newest',
  tiles: [
    {
      id: 'unstitched-hero',
      slot: 'hero',
      eyebrow: 'Unstitched',
      title: 'Premium lawn, cotton, and festive embroideries tailored to your style.',
      ctaLabel: 'Shop fabrics',
      href: '?search=unstitched',
      image: 'https://images.unsplash.com/photo-1558171813-4c088753af8f?w=800&q=82&auto=format&fit=crop',
    },
    {
      id: 'rtw-banner',
      slot: 'banner',
      eyebrow: 'Ready to wear',
      title: 'Effortless pret for workdays, weddings, and weekends.',
      ctaLabel: 'Shop pret',
      href: '?search=ready%20to%20wear',
      image: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=800&q=82&auto=format&fit=crop',
    },
    {
      id: 'accessories-left',
      slot: 'half-left',
      eyebrow: 'Accessories',
      ctaLabel: 'Explore',
      href: '?search=accessories',
      image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&q=82&auto=format&fit=crop',
    },
    {
      id: 'formal-right',
      slot: 'half-right',
      eyebrow: 'Formal',
      ctaLabel: 'Explore',
      href: '?search=formal',
      image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=82&auto=format&fit=crop',
    },
  ],
};

/** Fabric wholesale Home Edit for textile verticals. */
export const TEXTILE_HOME_EDIT = {
  title: 'The Fabric Edit',
  subtitle:
    'Seasonal lawn, khaddar, cotton, and bridal ranges for retailers and bulk buyers.',
  viewAllHref: '?search=lawn',
  tiles: [
    {
      id: 'lawn-hero',
      slot: 'hero',
      eyebrow: 'Lawn',
      title: 'Digital prints and signature summer collections.',
      ctaLabel: 'Shop lawn',
      href: '?search=lawn',
      image: 'https://images.unsplash.com/photo-1558171813-4c088753af8f?w=800&q=82&auto=format&fit=crop',
    },
    {
      id: 'khaddar-banner',
      slot: 'banner',
      eyebrow: 'Khaddar',
      title: 'Winter-ready textures trusted by boutiques nationwide.',
      ctaLabel: 'Browse khaddar',
      href: '?search=khaddar',
      image: 'https://images.unsplash.com/photo-1583292650118-0c8d2f9a9f2d?w=800&q=82&auto=format&fit=crop',
    },
    {
      id: 'unstitched-left',
      slot: 'half-left',
      eyebrow: 'Unstitched',
      ctaLabel: 'Explore',
      href: '?search=unstitched',
      image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&q=82&auto=format&fit=crop',
    },
    {
      id: 'bridal-right',
      slot: 'half-right',
      eyebrow: 'Bridal',
      ctaLabel: 'Explore',
      href: '?search=bridal',
      image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=600&q=82&auto=format&fit=crop',
    },
  ],
};

/** Leather / footwear Home Edit. */
export const LEATHER_HOME_EDIT = {
  title: 'The Leather Edit',
  subtitle: 'Hand-finished footwear, bags, and belts built for everyday style.',
  viewAllHref: '?sort=newest',
  tiles: [
    {
      id: 'footwear-hero',
      slot: 'hero',
      eyebrow: 'Footwear',
      title: 'Step into quality with durable materials and refined details.',
      ctaLabel: 'Shop footwear',
      href: '?search=footwear',
      image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&q=82&auto=format&fit=crop',
    },
    {
      id: 'bags-banner',
      slot: 'banner',
      eyebrow: 'Bags',
      title: 'Everyday carry with premium leather finishes.',
      ctaLabel: 'Shop bags',
      href: '?search=bags',
      image: 'https://images.unsplash.com/photo-1520639882103-d7964dc5a26a?w=800&q=82&auto=format&fit=crop',
    },
    {
      id: 'leather-left',
      slot: 'half-left',
      eyebrow: 'Leather goods',
      ctaLabel: 'Explore',
      href: '?search=leather',
      image: 'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=600&q=82&auto=format&fit=crop',
    },
    {
      id: 'sale-right',
      slot: 'half-right',
      eyebrow: 'Sale',
      ctaLabel: 'Explore',
      href: '?onSale=true',
      image: 'https://images.unsplash.com/photo-1520639882103-d7964dc5a26a?w=600&q=82&auto=format&fit=crop',
    },
  ],
};

export const GUL_AHMED_SALE_MOSAIC = {
  "title": "Sale",
  "columns": [
    {
      "id": "col-kids",
      "tiles": [
        {
          "id": "kids",
          "label": "Kids",
          "href": "?category=kids&onSale=true",
          "desktop": "https://www.gulahmedshop.com/cdn/shop/files/sale-kids-wb_575aaa29-01e7-45d7-b55f-bfa772be5b57.webp?v=1780487677&width=1000",
          "mobile": "https://www.gulahmedshop.com/cdn/shop/files/sale-kids-mb_1f261ed6-bd44-4e0d-a00e-d3ec530c452f.webp?v=1780487926&width=750"
        }
      ]
    },
    {
      "id": "col-rtw-home",
      "tiles": [
        {
          "id": "rtw",
          "label": "Ready to Wear",
          "href": "?sort=newest&onSale=true",
          "desktop": "https://www.gulahmedshop.com/cdn/shop/files/sale-rtw-wb_b56e926a-3968-42da-bfec-fa65986f983a.webp?v=1780487677&width=1000",
          "mobile": "https://www.gulahmedshop.com/cdn/shop/files/sale-rtw-mb_c5d1594a-b1c4-4fc7-b6be-da0d0e8b3693.webp?v=1780487926&width=750"
        },
        {
          "id": "home",
          "label": "Ideas Home",
          "href": "?category=home&onSale=true",
          "desktop": "https://www.gulahmedshop.com/cdn/shop/files/sale-home-wb_743e6659-4f93-40bd-ae7a-6218e5bcb124.webp?v=1780487677&width=1000",
          "mobile": "https://www.gulahmedshop.com/cdn/shop/files/sale-home-mb_e44d07b1-4906-4ce9-bcea-ff36ab3bcf57.webp?v=1780487926&width=750"
        }
      ]
    },
    {
      "id": "col-salt",
      "tiles": [
        {
          "id": "salt",
          "label": "Salt by Ideas",
          "href": "?category=pret&onSale=true",
          "desktop": "https://www.gulahmedshop.com/cdn/shop/files/sale-salt-wb_9b8ab626-6261-4baf-a36d-0b40b2e5578d.webp?v=1780487677&width=1000",
          "mobile": "https://www.gulahmedshop.com/cdn/shop/files/sale-sale-mb.webp?v=1780487926&width=750"
        }
      ]
    },
    {
      "id": "col-unstitched-men",
      "tiles": [
        {
          "id": "unstitched",
          "label": "Women's Unstitched",
          "href": "?category=unstitched&onSale=true",
          "desktop": "https://www.gulahmedshop.com/cdn/shop/files/sale-unstitched-wb.webp?v=1780487678&width=1000",
          "mobile": "https://www.gulahmedshop.com/cdn/shop/files/sale-unstitched-mb.webp?v=1780487926&width=750"
        },
        {
          "id": "men",
          "label": "Men Eastern",
          "href": "?category=eastern-wear&onSale=true",
          "desktop": "https://www.gulahmedshop.com/cdn/shop/files/sale-men-eastern.webp?v=1780487677&width=1000",
          "mobile": "https://www.gulahmedshop.com/cdn/shop/files/sale-eastern-mb.webp?v=1780487926&width=750"
        }
      ]
    },
    {
      "id": "col-shoes",
      "tiles": [
        {
          "id": "shoes",
          "label": "Shoes & Bags",
          "href": "?category=accessories&onSale=true",
          "desktop": "https://www.gulahmedshop.com/cdn/shop/files/sale-shoes-bags-wb.webp?v=1780487678&width=1000",
          "mobile": "https://www.gulahmedshop.com/cdn/shop/files/sale-shoes-bags-mb.webp?v=1780487926&width=750"
        }
      ]
    }
  ]
};

export const JEWELLERY_HOME_EDIT = {
  "title": "The Jewellery Edit",
  "subtitle": "Timeless gold, diamonds, and bridal sets crafted for every milestone.",
  "viewAllHref": "?category=gold",
  "tiles": [
    {
      "id": "gold-hero",
      "slot": "hero",
      "eyebrow": "Fine gold",
      "title": "Celebrate every occasion with hallmarked purity.",
      "ctaLabel": "Explore",
      "href": "?category=gold",
      "image": "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&q=82&auto=format&fit=crop"
    },
    {
      "id": "diamonds",
      "slot": "banner",
      "eyebrow": "Diamonds",
      "title": "Brilliance that lasts generations",
      "ctaLabel": "Explore",
      "href": "?category=diamonds",
      "image": "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&q=82&auto=format&fit=crop"
    },
    {
      "id": "bridal",
      "slot": "half-left",
      "eyebrow": "Bridal",
      "ctaLabel": "Explore",
      "href": "?category=bridal",
      "image": "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600&q=82&auto=format&fit=crop"
    },
    {
      "id": "gifts",
      "slot": "half-right",
      "eyebrow": "Gifts",
      "ctaLabel": "Explore",
      "href": "?sort=featured",
      "image": "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&q=82&auto=format&fit=crop"
    }
  ]
};

export const JEWELLERY_SALE_MOSAIC = {
  "title": "Sale",
  "columns": [
    {
      "id": "col-gold",
      "tiles": [
        {
          "id": "gold",
          "label": "Gold",
          "href": "?category=gold&onSale=true",
          "desktop": "https://www.gulahmedshop.com/cdn/shop/files/sale-rtw-wb_b56e926a-3968-42da-bfec-fa65986f983a.webp?v=1780487677&width=1000",
          "mobile": "https://www.gulahmedshop.com/cdn/shop/files/sale-rtw-mb_c5d1594a-b1c4-4fc7-b6be-da0d0e8b3693.webp?v=1780487926&width=750"
        }
      ]
    },
    {
      "id": "col-bridal-diamonds",
      "tiles": [
        {
          "id": "bridal",
          "label": "Bridal",
          "href": "?category=bridal&onSale=true",
          "desktop": "https://www.gulahmedshop.com/cdn/shop/files/sale-unstitched-wb.webp?v=1780487678&width=1000",
          "mobile": "https://www.gulahmedshop.com/cdn/shop/files/sale-unstitched-mb.webp?v=1780487926&width=750"
        },
        {
          "id": "diamonds",
          "label": "Diamonds",
          "href": "?category=diamonds&onSale=true",
          "desktop": "https://www.gulahmedshop.com/cdn/shop/files/sale-home-wb_743e6659-4f93-40bd-ae7a-6218e5bcb124.webp?v=1780487677&width=1000",
          "mobile": "https://www.gulahmedshop.com/cdn/shop/files/sale-home-mb_e44d07b1-4906-4ce9-bcea-ff36ab3bcf57.webp?v=1780487926&width=750"
        }
      ]
    },
    {
      "id": "col-gifts",
      "tiles": [
        {
          "id": "gifts",
          "label": "Gift sets",
          "href": "?onSale=true",
          "desktop": "https://www.gulahmedshop.com/cdn/shop/files/sale-salt-wb_9b8ab626-6261-4baf-a36d-0b40b2e5578d.webp?v=1780487677&width=1000",
          "mobile": "https://www.gulahmedshop.com/cdn/shop/files/sale-sale-mb.webp?v=1780487926&width=750"
        }
      ]
    },
    {
      "id": "col-rings-bangles",
      "tiles": [
        {
          "id": "rings",
          "label": "Rings",
          "href": "?category=rings&onSale=true",
          "desktop": "https://www.gulahmedshop.com/cdn/shop/files/sale-men-eastern.webp?v=1780487677&width=1000",
          "mobile": "https://www.gulahmedshop.com/cdn/shop/files/sale-eastern-mb.webp?v=1780487926&width=750"
        },
        {
          "id": "bangles",
          "label": "Bangles",
          "href": "?category=bangles&onSale=true",
          "desktop": "https://www.gulahmedshop.com/cdn/shop/files/sale-shoes-bags-wb.webp?v=1780487678&width=1000",
          "mobile": "https://www.gulahmedshop.com/cdn/shop/files/sale-shoes-bags-mb.webp?v=1780487926&width=750"
        }
      ]
    },
    {
      "id": "col-watches",
      "tiles": [
        {
          "id": "watches",
          "label": "Watches",
          "href": "?category=watches&onSale=true",
          "desktop": "https://www.gulahmedshop.com/cdn/shop/files/sale-kids-wb_575aaa29-01e7-45d7-b55f-bfa772be5b57.webp?v=1780487677&width=1000",
          "mobile": "https://www.gulahmedshop.com/cdn/shop/files/sale-kids-mb_1f261ed6-bd44-4e0d-a00e-d3ec530c452f.webp?v=1780487926&width=750"
        }
      ]
    }
  ]
};

/** @typedef {'boutique' | 'textile' | 'leather' | 'jewellery'} FashionGulVariant */

/**
 * @param {import('@/lib/storefront/luxuryFashion').LuxuryFashionVariant | null | undefined} variant
 */
export function getDefaultFashionGulSections(variant) {
  if (variant === 'jewellery') {
    return { homeEdit: JEWELLERY_HOME_EDIT, saleMosaic: JEWELLERY_SALE_MOSAIC };
  }
  if (variant === 'textile') {
    return { homeEdit: TEXTILE_HOME_EDIT, saleMosaic: GUL_AHMED_SALE_MOSAIC };
  }
  if (variant === 'leather') {
    return { homeEdit: LEATHER_HOME_EDIT, saleMosaic: GUL_AHMED_SALE_MOSAIC };
  }
  return { homeEdit: BOUTIQUE_HOME_EDIT, saleMosaic: GUL_AHMED_SALE_MOSAIC };
}
