/**
 * Rich seed products for boutique / textile demos, names, PKR pricing, and
 * domain_data aligned with Limelight & Khaadi navigation (Unstitched, RTW,
 * Accessories, New In). Images from fashionDemoImages.js (Unsplash).
 */
import { fashionStockImage, FASHION_DEMO_IMAGES } from './fashionDemoImages.js';

const U = FASHION_DEMO_IMAGES.unstitched;
const R = FASHION_DEMO_IMAGES.rtw;
const A = FASHION_DEMO_IMAGES.accessories;
const W = FASHION_DEMO_IMAGES.western;

/** @type {Array<Record<string, unknown>>} */
export const BOUTIQUE_FASHION_SEED_PRODUCTS = [
  // Unstitched (Limelight UNSTITCHED grid)
  {
    name: '3 Piece Lawn Suit (Unstitched)',
    brand: 'Limelight',
    category: 'Lawn',
    unit: 'set',
    price: 4699,
    compare_price: 4699,
    cost_price: 3200,
    stock: 48,
    sku: 'LL-LWN-3PC-001',
    description: 'Signature summer lawn, shirt, dupatta & trouser fabric.',
    image_url: fashionStockImage(U.summer),
    domain_data: {
      fabrictype: 'Lawn',
      stitchingtype: 'Unstitched',
      korafinished: 'Printed',
      collection: 'Summer',
      department: 'Women',
      line: 'Essentials',
    },
    is_featured: true,
    is_new: true,
  },
  {
    name: '3 Piece Lawn Suit, Embroidered (Unstitched)',
    brand: 'Khaadi',
    category: 'Unstitched Fabric',
    unit: 'set',
    price: 5999,
    compare_price: 5999,
    cost_price: 4100,
    stock: 36,
    sku: 'KH-LWN-EMB-002',
    description: 'Embroidered lawn 3pc, festive unstitched collection.',
    image_url: fashionStockImage(U.embroidered),
    domain_data: {
      fabrictype: 'Lawn',
      stitchingtype: 'Unstitched',
      korafinished: 'Embroidered',
      collection: 'Signature',
      department: 'Women',
      line: 'Signature',
    },
    is_new: true,
  },
  {
    name: 'Digital Printed Lawn 3pc',
    brand: 'Gul Ahmed',
    category: 'Lawn',
    unit: 'set',
    price: 4290,
    compare_price: 4990,
    cost_price: 2900,
    stock: 55,
    sku: 'GA-LWN-PRT-003',
    description: 'Vibrant digital prints on premium lawn.',
    image_url: fashionStockImage(U.printed),
    domain_data: {
      fabrictype: 'Lawn',
      stitchingtype: 'Unstitched',
      korafinished: 'Printed',
      collection: 'Summer',
      department: 'Women',
    },
    is_new: true,
  },
  {
    name: 'Chiffon Embroidered 3 Piece (Unstitched)',
    brand: 'Sana Safinaz',
    category: 'Unstitched Fabric',
    unit: 'set',
    price: 12500,
    compare_price: 14900,
    cost_price: 9200,
    stock: 18,
    sku: 'SS-CHF-UNS-004',
    description: 'Luxury chiffon with organza dupatta, unstitched formal.',
      image_url: fashionStockImage(U.chiffon || U.embroidered),
    domain_data: {
      fabrictype: 'Chiffon',
      stitchingtype: 'Unstitched',
      korafinished: 'Embroidered',
      collection: 'Evening Wear',
      department: 'Women',
    },
    is_featured: true,
  },
  {
    name: 'Cotton Khaddar Unstitched 2pc',
    brand: 'Al-Karam',
    category: 'Unstitched Fabric',
    unit: 'set',
    price: 3200,
    cost_price: 2400,
    stock: 40,
    sku: 'AK-COT-UNS-005',
    description: 'Winter khaddar collection, shirt & trouser.',
    image_url: fashionStockImage(U.cotton),
    domain_data: {
      fabrictype: 'Cotton',
      stitchingtype: 'Unstitched',
      korafinished: 'Finished',
      collection: 'Winter',
      department: 'Women',
    },
  },

  // Ready to Wear (Limelight READY TO WEAR circles)
  {
    name: '2 Piece Yarn Dyed Suit, Embroidered (Pret)',
    brand: 'Maria B',
    category: 'Stitched Suits',
    unit: 'set',
    price: 6899,
    compare_price: 6899,
    cost_price: 4800,
    stock: 22,
    sku: 'MB-RTW-EMB-006',
    description: 'Ready-to-wear embroidered pret suit.',
    image_url: fashionStockImage(R.embroidered),
    domain_data: {
      fabrictype: 'Cambric',
      stitchingtype: 'Ready-to-Wear',
      korafinished: 'Embroidered',
      collection: 'Luxury Pret',
      department: 'Women',
      line: 'Signature',
    },
    is_new: true,
    is_featured: true,
  },
  {
    name: 'Longline Lawn Kurta (Pret)',
    brand: 'Khaadi',
    category: 'Stitched Suits',
    unit: 'pcs',
    price: 4990,
    compare_price: 5490,
    cost_price: 3400,
    stock: 28,
    sku: 'KH-RTW-KRT-007',
    description: 'Embroidered | Lawn | Longline kurta, ready to wear.',
    image_url: fashionStockImage(R.kurtis),
    domain_data: {
      fabrictype: 'Lawn',
      stitchingtype: 'Ready-to-Wear',
      korafinished: 'Embroidered',
      collection: 'Essentials',
      department: 'Women',
      line: 'Essentials',
    },
    is_featured: true,
  },
  {
    name: 'Solid Cambric Kurta (Pret)',
    brand: 'Limelight',
    category: 'Stitched Suits',
    unit: 'pcs',
    price: 3490,
    cost_price: 2400,
    stock: 35,
    sku: 'LL-RTW-SLD-008',
    description: 'Monochrome solids pret kurta.',
    image_url: fashionStockImage(R.solids),
    domain_data: {
      fabrictype: 'Cambric',
      stitchingtype: 'Ready-to-Wear',
      korafinished: 'Dyed',
      collection: 'Monochrome Edit',
      department: 'Women',
    },
  },
  {
    name: 'Luxury Pret Co-ord Set',
    brand: 'Elan',
    category: 'Co-ords',
    unit: 'set',
    price: 8900,
    compare_price: 10500,
    cost_price: 6500,
    stock: 16,
    sku: 'EL-COORD-009',
    description: 'Printed co-ord set, shirt & trouser.',
    image_url: fashionStockImage(R.coords),
    domain_data: {
      fabrictype: 'Cambric',
      stitchingtype: 'Ready-to-Wear',
      korafinished: 'Printed',
      collection: 'Co-ords',
      department: 'Women',
    },
    is_featured: true,
  },
  {
    name: 'Formal Embroidered Kurta (Pret)',
    brand: 'Faraz Manan',
    category: 'Semi-Formal',
    unit: 'pcs',
    price: 7500,
    cost_price: 5200,
    stock: 20,
    sku: 'FM-RTW-FRM-010',
    description: 'Party formal embroidered kurta.',
    image_url: fashionStockImage(R.formals),
    domain_data: {
      fabrictype: 'Organza',
      stitchingtype: 'Ready-to-Wear',
      korafinished: 'Embroidered',
      collection: 'Evening Wear',
      department: 'Women',
    },
  },
  {
    name: 'Wide Leg Trousers (Pret)',
    brand: 'Limelight',
    category: 'Semi-Formal',
    unit: 'pcs',
    price: 2990,
    cost_price: 1900,
    stock: 42,
    sku: 'LL-RTW-BTM-011',
    description: 'Ready-to-wear wide leg trousers.',
    image_url: fashionStockImage(R.bottoms),
    domain_data: {
      fabrictype: 'Cotton',
      stitchingtype: 'Ready-to-Wear',
      collection: 'Bottoms',
      department: 'Women',
    },
  },
  {
    name: 'Silk Pret 2 Piece',
    brand: 'Zara Shahjahan',
    category: 'Stitched Suits',
    unit: 'set',
    price: 9990,
    compare_price: 11500,
    cost_price: 7200,
    stock: 12,
    sku: 'ZS-SLK-PRT-012',
    description: 'Silk pret shirt & trouser, signature collection.',
    image_url: fashionStockImage(R.silk),
    domain_data: {
      fabrictype: 'Silk',
      stitchingtype: 'Ready-to-Wear',
      collection: 'Signature',
      department: 'Women',
      line: 'Signature',
    },
  },

  // Western (Limelight shop-by-collection)
  {
    name: 'Everyday Stripe Top',
    brand: 'Limelight',
    category: 'Western',
    unit: 'pcs',
    price: 2499,
    compare_price: 2499,
    cost_price: 1600,
    stock: 50,
    sku: 'LL-WST-TOP-013',
    description: 'Casual western stripe top.',
    image_url: fashionStockImage(W.top),
    domain_data: {
      fabrictype: 'Cotton',
      stitchingtype: 'Ready-to-Wear',
      collection: 'Western',
      department: 'Women',
    },
    is_new: true,
  },
  {
    name: 'Lounge Wear Co-ord',
    brand: 'Limelight',
    category: 'Co-ords',
    unit: 'set',
    price: 4590,
    cost_price: 3100,
    stock: 24,
    sku: 'LL-LNG-COORD-014',
    description: 'Soft lounge co-ord set.',
    image_url: fashionStockImage(W.lounge),
    domain_data: {
      stitchingtype: 'Ready-to-Wear',
      collection: 'Lounge Wear',
      department: 'Women',
    },
  },

  // Accessories (Limelight ACCESSORIES carousel)
  {
    name: 'Viscose Scarf',
    brand: 'Limelight',
    category: 'Accessories',
    unit: 'pcs',
    price: 1199,
    compare_price: 1199,
    cost_price: 650,
    stock: 80,
    sku: 'LL-ACC-SCF-015',
    description: 'Lightweight viscose scarf.',
    image_url: fashionStockImage(A.scarf),
    domain_data: { accessoryType: 'Scarves', department: 'Women' },
    is_new: true,
  },
  {
    name: 'Silk Digital Print Stole',
    brand: 'Khaadi',
    category: 'Accessories',
    unit: 'pcs',
    price: 1290,
    compare_price: 1590,
    cost_price: 750,
    stock: 60,
    sku: 'KH-ACC-STL-016',
    description: 'Pure silk stole with digital print.',
    image_url: fashionStockImage(A.stole),
    domain_data: { accessoryType: 'Shawls', department: 'Women' },
  },
  {
    name: 'Embroidered Dupatta',
    brand: 'Nomi Ansari',
    category: 'Accessories',
    unit: 'pcs',
    price: 3490,
    cost_price: 2200,
    stock: 30,
    sku: 'NA-ACC-DUP-017',
    description: 'Organza embroidered dupatta.',
    image_url: fashionStockImage(A.dupattas),
    domain_data: { accessoryType: 'Dupattas', department: 'Women' },
  },
  {
    name: 'Pearl Drop Earrings',
    brand: 'Limelight',
    category: 'Accessories',
    unit: 'pair',
    price: 1890,
    cost_price: 950,
    stock: 45,
    sku: 'LL-ACC-JWL-018',
    description: 'Gold-tone pearl drop earrings.',
    image_url: fashionStockImage(A.jewellery),
    domain_data: { accessoryType: 'Jewelry', department: 'Women' },
  },
  {
    name: 'Structured Crossbody Bag',
    brand: 'Limelight',
    category: 'Accessories',
    unit: 'pcs',
    price: 3490,
    compare_price: 4290,
    cost_price: 2100,
    stock: 25,
    sku: 'LL-ACC-BAG-019',
    description: 'Crossbody handbag with chain detail.',
    image_url: fashionStockImage(A.bag),
    domain_data: { accessoryType: 'Bags', department: 'Women' },
    is_new: true,
  },
  {
    name: 'Envelope Wallet',
    brand: 'Limelight',
    category: 'Accessories',
    unit: 'pcs',
    price: 2190,
    cost_price: 1200,
    stock: 38,
    sku: 'LL-ACC-WLT-020',
    description: 'Compact envelope wallet.',
    image_url: fashionStockImage(A.wallet),
    domain_data: { accessoryType: 'Wallets', department: 'Women' },
  },
  {
    name: 'Printed Shawl',
    brand: 'Limelight',
    category: 'Accessories',
    unit: 'pcs',
    price: 2790,
    cost_price: 1700,
    stock: 32,
    sku: 'LL-ACC-SHW-021',
    description: 'Vibrant printed shawl with fringe.',
    image_url: fashionStockImage(A.shawls),
    domain_data: { accessoryType: 'Shawls', department: 'Women' },
  },
  {
    name: 'Oversized Sunglasses',
    brand: 'Imported',
    category: 'Accessories',
    unit: 'pcs',
    price: 2490,
    cost_price: 1400,
    stock: 28,
    sku: 'LL-ACC-SUN-022',
    description: 'Tortoiseshell oversized sunglasses.',
    image_url: fashionStockImage(A.sunglasses),
    domain_data: { accessoryType: 'Sunglasses', department: 'Women' },
  },
  {
    name: 'Crystal Bezel Watch',
    brand: 'Imported',
    category: 'Accessories',
    unit: 'pcs',
    price: 4990,
    compare_price: 5990,
    cost_price: 3200,
    stock: 15,
    sku: 'LL-ACC-WCH-023',
    description: 'Metal strap watch with crystal bezel.',
    image_url: fashionStockImage(A.watches),
    domain_data: { accessoryType: 'Watches', department: 'Women' },
  },

  // Footwear
  {
    name: 'Gold Chain Slide Sandals',
    brand: 'Limelight',
    category: 'Footwear',
    unit: 'pair',
    price: 3290,
    compare_price: 3890,
    cost_price: 2100,
    stock: 22,
    sku: 'LL-FTW-SLD-024',
    description: 'Comfort slides with gold chain accent.',
    image_url: fashionStockImage(A.slides),
    domain_data: { accessoryType: 'Footwear', footwearType: 'Slides', department: 'Women' },
    is_new: true,
  },
];

/** Categories seeded for boutique demo (Limelight / Khaadi nav order). */
export const BOUTIQUE_FASHION_SEED_CATEGORIES = [
  'Unstitched Fabric',
  'Lawn',
  'Stitched Suits',
  'Semi-Formal',
  'Co-ords',
  'Western',
  'Accessories',
  'Footwear',
];
