/**
 * Rich seed products for gems & jewellery demos, PKR pricing, hallmark fields,
 * and curated Unsplash imagery for client-facing storefronts.
 */
import { jewelleryStockImage, JEWELLERY_DEMO_IMAGES } from './jewelleryDemoImages.js';

const G = JEWELLERY_DEMO_IMAGES.gold;
const D = JEWELLERY_DEMO_IMAGES.diamond;
const B = JEWELLERY_DEMO_IMAGES.bridal;
const N = JEWELLERY_DEMO_IMAGES.necklace;
const E = JEWELLERY_DEMO_IMAGES.earrings;
const R = JEWELLERY_DEMO_IMAGES.rings;
const S = JEWELLERY_DEMO_IMAGES.silver;
const F = JEWELLERY_DEMO_IMAGES.gifts;

/** @type {Array<Record<string, unknown>>} */
export const GEMS_JEWELLERY_SEED_PRODUCTS = [
  // Gold
  {
    name: '22K Gold Wedding Band (Men)',
    brand: 'Heritage Gold',
    category: 'Gold',
    unit: 'pcs',
    price: 185000,
    compare_price: 198000,
    cost_price: 162000,
    stock: 8,
    sku: 'GOLD-RNG-M-22K-001',
    description: 'Classic 22K gold wedding band, hallmark assured, sizes 18-22.',
    image_url: jewelleryStockImage(G.ring),
    domain_data: { carat: '22K', weight: 8.5, hallmark: 'PK-HM-8821', certification: 'Assay certified' },
    is_featured: true,
    is_new: true,
  },
  {
    name: '21K Gold Chain Necklace (22")',
    brand: 'Saddar Jewellers',
    category: 'Gold',
    unit: 'pcs',
    price: 245000,
    cost_price: 218000,
    stock: 6,
    sku: 'GOLD-CHN-21K-22',
    description: 'Machine-made Cuban link chain, insured shipping.',
    image_url: jewelleryStockImage(G.chain),
    domain_data: { carat: '21K', weight: 12.2, hallmark: 'PK-HM-4410' },
    is_featured: true,
  },
  {
    name: '22K Gold Chand Bali Earrings',
    brand: 'Heritage Gold',
    category: 'Gold',
    unit: 'pair',
    price: 128000,
    compare_price: 142000,
    cost_price: 108000,
    stock: 10,
    sku: 'GOLD-EAR-CHB-22',
    description: 'Traditional chand bali with safety hooks.',
    image_url: jewelleryStockImage(G.earrings),
    domain_data: { carat: '22K', weight: 6.8, hallmark: 'PK-HM-3302' },
    is_new: true,
  },
  {
    name: '24K Gold Coin (1 Tola)',
    brand: 'National Refinery',
    category: 'Gold Coins',
    unit: 'tola',
    price: 285000,
    cost_price: 272000,
    stock: 24,
    sku: 'GOLD-COIN-1T-24K',
    description: '999.9 pure gold 1 tola investment coin with assay certificate.',
    image_url: jewelleryStockImage(G.coin),
    domain_data: { carat: '24K', weight: 11.66, certification: 'Assay certificate' },
    is_featured: true,
  },
  {
    name: '22K Gold Kangan Pair (Bangles)',
    brand: 'Saddar Jewellers',
    category: 'Bracelets',
    unit: 'pair',
    price: 320000,
    compare_price: 345000,
    cost_price: 288000,
    stock: 4,
    sku: 'GOLD-BNG-KNG-22',
    description: 'Handcrafted solid kangan pair, bridal favourite.',
    image_url: jewelleryStockImage(G.bangle),
    domain_data: { carat: '22K', weight: 28.5, hallmark: 'PK-HM-7712' },
    is_new: true,
  },

  // Diamonds
  {
    name: 'GIA 0.50ct Solitaire Diamond Ring',
    brand: 'Lumière Diamonds',
    category: 'Diamonds',
    unit: 'pcs',
    price: 425000,
    compare_price: 465000,
    cost_price: 360000,
    stock: 3,
    sku: 'DIA-SOL-050-GIA',
    description: 'Round brilliant GIA certified, 18K white gold mount.',
    image_url: jewelleryStockImage(D.solitaire),
    domain_data: {
      carat: '18K',
      clarity: 'VS1',
      cut: 'Round',
      certification: 'GIA',
      weight: 3.2,
    },
    is_featured: true,
    is_new: true,
  },
  {
    name: 'VS1 Diamond Stud Earrings (0.30ct each)',
    brand: 'Lumière Diamonds',
    category: 'Diamonds',
    unit: 'pair',
    price: 198000,
    compare_price: 225000,
    cost_price: 168000,
    stock: 5,
    sku: 'DIA-STD-030-VS1',
    description: 'Four-prong studs in 18K white gold, IGI certified pair.',
    image_url: jewelleryStockImage(D.studs),
    domain_data: { clarity: 'VS1', cut: 'Round', certification: 'IGI', carat: '18K' },
  },
  {
    name: 'Diamond Tennis Bracelet (2ct TDW)',
    brand: 'Lumière Diamonds',
    category: 'Diamonds',
    unit: 'pcs',
    price: 385000,
    cost_price: 325000,
    stock: 2,
    sku: 'DIA-BRC-TEN-2CT',
    description: 'Graduated tennis bracelet, 18K white gold clasp.',
    image_url: jewelleryStockImage(D.bracelet),
    domain_data: { clarity: 'VS2', cut: 'Round', certification: 'IGI', carat: '18K' },
    is_featured: true,
  },
  {
    name: 'Oval Diamond Pendant with Chain',
    brand: 'Lumière Diamonds',
    category: 'Diamonds',
    unit: 'pcs',
    price: 156000,
    compare_price: 175000,
    cost_price: 132000,
    stock: 7,
    sku: 'DIA-PND-OVL-018',
    description: '0.18ct oval diamond on 18" 18K chain.',
    image_url: jewelleryStockImage(D.pendant),
    domain_data: { clarity: 'SI1', cut: 'Oval', certification: 'IGI', carat: '18K' },
    is_new: true,
  },

  // Bridal
  {
    name: 'Kundan Bridal Necklace Set (4pc)',
    brand: 'Royal Heritage',
    category: 'Bridal',
    unit: 'set',
    price: 285000,
    compare_price: 320000,
    cost_price: 235000,
    stock: 3,
    sku: 'BRD-KUN-4PC-001',
    description: 'Necklace, earrings, tikka & ring, kundan with meenakari.',
    image_url: jewelleryStockImage(B.set),
    domain_data: { carat: '22K', weight: 45, hallmark: 'PK-HM-9901' },
    is_featured: true,
    is_new: true,
  },
  {
    name: 'Polki Bridal Choker & Earrings',
    brand: 'Royal Heritage',
    category: 'Bridal',
    unit: 'set',
    price: 198000,
    cost_price: 165000,
    stock: 4,
    sku: 'BRD-POL-CHK-002',
    description: 'Uncut polki choker with matching jhumka earrings.',
    image_url: jewelleryStockImage(B.choker),
    domain_data: { carat: '22K', weight: 32, hallmark: 'PK-HM-9902' },
  },
  {
    name: 'Bridal Payal Pair (Gold Plated)',
    brand: 'Royal Heritage',
    category: 'Bridal',
    unit: 'pair',
    price: 45000,
    cost_price: 28000,
    stock: 12,
    sku: 'BRD-PAY-GP-003',
    description: 'Traditional payal with ghungroo detailing.',
    image_url: jewelleryStockImage(B.payal),
    domain_data: { carat: '18K', weight: 18 },
  },

  // Necklaces
  {
    name: 'Ruby & Gold Statement Necklace',
    brand: 'Saddar Jewellers',
    category: 'Necklaces',
    unit: 'pcs',
    price: 165000,
    compare_price: 185000,
    cost_price: 138000,
    stock: 5,
    sku: 'NCK-RBY-STMT-22',
    description: 'Burmese ruby drops on 22K gold collar.',
    image_url: jewelleryStockImage(N.ruby),
    domain_data: { carat: '22K', weight: 22.4, hallmark: 'PK-HM-5520' },
    is_new: true,
  },
  {
    name: 'Layered Gold Chain Set (3 Strand)',
    brand: 'Heritage Gold',
    category: 'Necklaces',
    unit: 'pcs',
    price: 98000,
    cost_price: 82000,
    stock: 9,
    sku: 'NCK-LAY-3ST-21',
    description: 'Three delicate chains at 16", 18" & 20", 21K gold.',
    image_url: jewelleryStockImage(N.layered),
    domain_data: { carat: '21K', weight: 9.6, hallmark: 'PK-HM-4411' },
  },

  // Earrings
  {
    name: 'Pearl Drop Earrings (18K)',
    brand: 'Pearl & Co',
    category: 'Earrings',
    unit: 'pair',
    price: 68000,
    cost_price: 52000,
    stock: 11,
    sku: 'EAR-PRL-DRP-18',
    description: 'South Sea pearl drops on 18K gold hooks.',
    image_url: jewelleryStockImage(E.pearl),
    domain_data: { carat: '18K', weight: 4.2 },
    is_new: true,
  },
  {
    name: '22K Gold Medium Hoops',
    brand: 'Heritage Gold',
    category: 'Earrings',
    unit: 'pair',
    price: 72000,
    compare_price: 79000,
    cost_price: 61000,
    stock: 14,
    sku: 'EAR-HOP-MED-22',
    description: 'Hollow medium hoops, lightweight daily wear.',
    image_url: jewelleryStockImage(E.hoops),
    domain_data: { carat: '22K', weight: 3.8, hallmark: 'PK-HM-3305' },
  },

  // Rings
  {
    name: 'Emerald Cocktail Ring (18K)',
    brand: 'Saddar Jewellers',
    category: 'Rings',
    unit: 'pcs',
    price: 142000,
    compare_price: 158000,
    cost_price: 118000,
    stock: 4,
    sku: 'RNG-EMR-CCK-18',
    description: 'Colombian emerald centre stone with diamond halo.',
    image_url: jewelleryStockImage(R.emerald),
    domain_data: { carat: '18K', clarity: 'VS2', cut: 'Emerald', weight: 5.1 },
  },
  {
    name: '18K Engagement Ring Semi-Mount',
    brand: 'Lumière Diamonds',
    category: 'Rings',
    unit: 'pcs',
    price: 85000,
    cost_price: 68000,
    stock: 6,
    sku: 'RNG-ENG-SM-18',
    description: 'Six-prong semi-mount, fits 0.50-0.75ct centre stone.',
    image_url: jewelleryStockImage(R.engagement),
    domain_data: { carat: '18K', cut: 'Round', weight: 2.8 },
    is_new: true,
  },

  // Pearls
  {
    name: 'Freshwater Pearl Strand Necklace (18")',
    brand: 'Pearl & Co',
    category: 'Pearls',
    unit: 'pcs',
    price: 52000,
    compare_price: 58000,
    cost_price: 38000,
    stock: 8,
    sku: 'PRL-STR-18-FW',
    description: 'AAA freshwater pearls with 18K gold clasp.',
    image_url: jewelleryStockImage(N.pearl),
    domain_data: { carat: '18K', weight: 12 },
    is_featured: true,
  },

  // Silver
  {
    name: '925 Silver Crescent Moon Pendant',
    brand: 'Silver Craft',
    category: 'Silver',
    unit: 'pcs',
    price: 8500,
    compare_price: 9900,
    cost_price: 5200,
    stock: 22,
    sku: 'SLV-PND-CRE-925',
    description: 'Oxidised crescent with 18" sterling chain.',
    image_url: jewelleryStockImage(S.pendant),
    domain_data: { weight: 8.5 },
    is_new: true,
  },
  {
    name: 'Sterling Silver Toe Ring Set',
    brand: 'Silver Craft',
    category: 'Silver',
    unit: 'set',
    price: 4200,
    cost_price: 2600,
    stock: 30,
    sku: 'SLV-TOE-SET-925',
    description: 'Adjustable toe rings, set of 4.',
    image_url: jewelleryStockImage(S.toeRings),
    domain_data: { weight: 3.2 },
  },

  // Bracelets
  {
    name: 'CZ Gold-Plated Bracelet Stack',
    brand: 'Everyday Luxe',
    category: 'Bracelets',
    unit: 'set',
    price: 12500,
    compare_price: 14900,
    cost_price: 6800,
    stock: 18,
    sku: 'BRC-CZ-STK-GP',
    description: 'Three-piece stackable bangles with cubic zirconia.',
    image_url: jewelleryStockImage(G.bangle),
    domain_data: { carat: '18K', weight: 15 },
  },

  // Gifts
  {
    name: 'Engraved Heart Locket (18K)',
    brand: 'Heritage Gold',
    category: 'Gifts',
    unit: 'pcs',
    price: 95000,
    compare_price: 108000,
    cost_price: 78000,
    stock: 7,
    sku: 'GFT-LCK-HRT-18',
    description: 'Photo locket with complimentary engraving.',
    image_url: jewelleryStockImage(F.locket),
    domain_data: { carat: '18K', weight: 4.5, hallmark: 'PK-HM-2201' },
    is_featured: true,
  },
  {
    name: 'Miniature Gold Elephant Figurine',
    brand: 'Heritage Gold',
    category: 'Gifts',
    unit: 'pcs',
    price: 68000,
    cost_price: 55000,
    stock: 5,
    sku: 'GFT-FIG-ELP-22',
    description: 'Hand-finished desk figurine, gift boxed.',
    image_url: jewelleryStockImage(F.figurine),
    domain_data: { carat: '22K', weight: 6.2, hallmark: 'PK-HM-2202' },
  },
];

/** Storefront category order for gems & jewellery demos. */
export const GEMS_JEWELLERY_SEED_CATEGORIES = [
  'Gold',
  'Diamonds',
  'Bridal',
  'Necklaces',
  'Earrings',
  'Rings',
  'Bracelets',
  'Pearls',
  'Silver',
  'Gold Coins',
  'Gifts',
];
