/**
 * Pakistan registration seed for clothing / textile verticals.
 * Mixes local Pakistani brands with imported / Lunda Bazaar stock (Turkey, China, UAE).
 */
import { fashionStockImage, FASHION_DEMO_IMAGES } from './fashionDemoImages.js';
import { buildUnsplashImageUrl } from '../storefront/unsplashUrl.js';

/** @param {string} photoId @param {number} [w] */
function stockImage(photoId, w = 800) {
  return buildUnsplashImageUrl(photoId, { w, q: 82 });
}

const U = FASHION_DEMO_IMAGES.unstitched;
const R = FASHION_DEMO_IMAGES.rtw;

/** Garments hub categories — local vs imported split for PK retail. */
export const GARMENTS_SEED_CATEGORIES = [
  'Pakistani Brands',
  'Imported Fashion',
  "Men's Wear",
  "Women's Wear",
  'Traditional',
  'Kids Wear',
];

/** @type {Array<Record<string, unknown>>} */
export const GARMENTS_SEED_PRODUCTS = [
  {
    name: 'Cotton Shalwar Kameez (Unstitched)',
    brand: 'Khaadi',
    category: 'Pakistani Brands',
    unit: 'set',
    price: 4500,
    compare_price: 5200,
    cost_price: 3100,
    stock: 40,
    sku: 'PK-SHK-KH-001',
    description: 'Classic cotton shalwar kameez fabric set, local brand.',
    image_url: fashionStockImage(U.cotton),
    domain_data: {
      sourcing: 'local',
      fabrictype: 'Cotton',
      stitchingstatus: 'Unstitched',
      season: 'Eid',
      designertracking: 'Khaadi',
    },
    is_featured: true,
  },
  {
    name: 'Digital Print Lawn 3pc',
    brand: 'Gul Ahmed',
    category: 'Pakistani Brands',
    unit: 'set',
    price: 4290,
    compare_price: 4990,
    cost_price: 2900,
    stock: 55,
    sku: 'PK-LWN-GA-002',
    description: 'Premium local lawn collection, shirt dupatta trouser.',
    image_url: fashionStockImage(U.printed),
    domain_data: {
      sourcing: 'local',
      fabrictype: 'Lawn',
      stitchingstatus: 'Unstitched',
      season: 'Summer',
      designertracking: 'Gul Ahmed',
    },
    is_new: true,
  },
  {
    name: 'Wash & Wear Executive 2pc',
    brand: 'Al-Karam',
    category: 'Traditional',
    unit: 'set',
    price: 3200,
    cost_price: 2300,
    stock: 35,
    sku: 'PK-WW-AK-003',
    description: 'Local mens wash & wear suit fabric.',
    image_url: stockImage('1617137968427-85924c800a22'),
    domain_data: {
      sourcing: 'local',
      fabrictype: 'Wash & Wear',
      stitchingstatus: 'Unstitched',
      season: 'Winter',
      designertracking: 'Al-Karam',
    },
  },
  {
    name: 'Formal White Shirt (Ready-to-Wear)',
    brand: 'Outfitters',
    category: "Men's Wear",
    unit: 'pcs',
    price: 2800,
    cost_price: 1850,
    stock: 60,
    sku: 'PK-SHT-OUT-004',
    description: 'Local brand formal shirt, size M.',
    image_url: stockImage('1596755090264-768c56c1f769'),
    domain_data: {
      sourcing: 'local',
      fabrictype: 'Cotton',
      stitchingstatus: 'Ready-to-Wear',
      sizecolormatrix: 'M-White',
      season: 'Spring',
    },
  },
  {
    name: 'Kids Cotton Kurta Set',
    brand: 'Junaid Jamshed',
    category: 'Kids Wear',
    unit: 'set',
    price: 2490,
    cost_price: 1650,
    stock: 45,
    sku: 'PK-KID-JJ-005',
    description: 'Local brand kids festive kurta shalwar.',
    image_url: fashionStockImage(R.kurtis),
    domain_data: {
      sourcing: 'local',
      fabrictype: 'Cotton',
      stitchingstatus: 'Ready-to-Wear',
      season: 'Eid',
    },
  },
  {
    name: 'Turkey Import Formal Shirt Lot',
    brand: 'Turkey',
    category: 'Imported Fashion',
    unit: 'pcs',
    price: 2200,
    compare_price: 2800,
    cost_price: 1400,
    stock: 80,
    sku: 'IMP-TR-SHT-006',
    description: 'Imported formal shirts, mixed sizes, Turkey origin.',
    image_url: stockImage('1594938298603-c8148c4dae35'),
    domain_data: {
      sourcing: 'imported',
      fabrictype: 'Cotton',
      origin: 'Turkey',
      stitchingstatus: 'Ready-to-Wear',
      season: 'Spring',
    },
    is_featured: true,
  },
  {
    name: 'China Import Polyester Kurta',
    brand: 'China',
    category: 'Imported Fashion',
    unit: 'pcs',
    price: 1650,
    cost_price: 950,
    stock: 100,
    sku: 'IMP-CN-KRT-007',
    description: 'Imported polyester kurtas, budget festive stock.',
    image_url: stockImage('1558171813-e2f8110a3b1e'),
    domain_data: {
      sourcing: 'imported',
      fabrictype: 'Chiffon',
      origin: 'China',
      stitchingstatus: 'Ready-to-Wear',
      season: 'Eid',
    },
  },
  {
    name: 'Lunda Bazaar Mixed Jeans Lot',
    brand: 'Imported',
    category: 'Imported Fashion',
    unit: 'pcs',
    price: 1890,
    compare_price: 2400,
    cost_price: 1100,
    stock: 120,
    sku: 'IMP-LND-JNS-008',
    description: 'Second-hand / surplus imported denim, Lunda Bazaar sourcing.',
    image_url: stockImage('1542272604-787c683553e7'),
    domain_data: {
      sourcing: 'imported',
      fabrictype: 'Denim',
      origin: 'Lunda Bazaar',
      stitchingstatus: 'Ready-to-Wear',
      season: 'Summer',
    },
  },
  {
    name: 'UAE Import Abaya Fabric Roll',
    brand: 'UAE',
    category: 'Imported Fashion',
    unit: 'meter',
    price: 850,
    cost_price: 580,
    stock: 200,
    sku: 'IMP-UAE-ABY-009',
    description: 'Imported abaya fabric roll, Gulf market surplus.',
    image_url: stockImage('1586796640118-4811f0880a72'),
    domain_data: {
      sourcing: 'imported',
      fabrictype: 'Silk',
      origin: 'UAE',
      stitchingstatus: 'Unstitched',
    },
  },
  {
    name: 'Imported Denim Jeans (Standard Fit)',
    brand: 'Imported',
    category: "Men's Wear",
    unit: 'pcs',
    price: 3200,
    cost_price: 2100,
    stock: 70,
    sku: 'IMP-JNS-STD-010',
    description: 'Imported blue denim jeans, assorted sizes.',
    image_url: stockImage('1542272604-787c683553e7'),
    domain_data: {
      sourcing: 'imported',
      fabrictype: 'Denim',
      origin: 'Turkey',
      stitchingstatus: 'Ready-to-Wear',
      sizecolormatrix: 'L-Blue',
      season: 'Summer',
    },
  },
];

/** Textile wholesale — local mills plus imported / Lunda stock. */
export const TEXTILE_WHOLESALE_SEED_CATEGORIES = [
  'Lawn',
  'Cotton',
  'Khaddar',
  'Wash & Wear',
  'Chiffon',
  'Imported Fabric',
  'Lunda Bazaar',
  'Mens Unstitched',
  'Bridal Collection',
];

/** @type {Array<Record<string, unknown>>} */
export const TEXTILE_MILL_SEED_CATEGORIES = [
  'Raw Yarn',
  'Finished Fabric',
  'Imported Yarn',
  'Dyes & Chemicals',
  'Packaging Material',
];

/** @type {Array<Record<string, unknown>>} */
export const TEXTILE_MILL_SEED_PRODUCTS = [
  {
    name: 'Combed Cotton Yarn (30s/1)',
    brand: 'Faisalabad Mill',
    category: 'Raw Yarn',
    unit: 'kg',
    price: 450,
    cost_price: 380,
    stock: 1000,
    sku: 'ML-YRN-COT-001',
    description: 'Local combed cotton yarn for weaving.',
    image_url: stockImage('1509042237730-0909102a63ed'),
    domain_data: { yarntype: 'Cotton', sourcing: 'local', countgsm: '30s' },
    is_featured: true,
  },
  {
    name: 'Imported Polyester Yarn (DTY)',
    brand: 'China',
    category: 'Imported Yarn',
    unit: 'kg',
    price: 520,
    cost_price: 410,
    stock: 800,
    sku: 'ML-YRN-IMP-002',
    description: 'Imported polyester DTY yarn for blended fabrics.',
    image_url: stockImage('1586796640118-4811f0880a72'),
    domain_data: { yarntype: 'Polyester', sourcing: 'imported', origin: 'China', countgsm: '150D' },
  },
  {
    name: 'Dyed Plain Weave Fabric',
    brand: 'Nishat Mills',
    category: 'Finished Fabric',
    unit: 'meter',
    price: 180,
    cost_price: 135,
    stock: 5000,
    sku: 'ML-FAB-DYD-003',
    description: 'Finished plain weave cotton fabric, local mill output.',
    image_url: stockImage('1558171813-e2f8110a3b1e'),
    domain_data: { fabricdesign: 'Plain', sourcing: 'local', countgsm: '150 GSM' },
  },
  {
    name: 'Reactive Blue Dye',
    brand: 'Local Supplier',
    category: 'Dyes & Chemicals',
    unit: 'kg',
    price: 2400,
    cost_price: 1900,
    stock: 200,
    sku: 'ML-DYE-RBL-004',
    description: 'Reactive dyes for textile processing.',
    image_url: stockImage('1509042237730-0909102a63ed'),
    domain_data: { sourcing: 'local' },
  },
];

/** Imported supplements merged into textile-wholesale rich catalog at registration. */
export const TEXTILE_WHOLESALE_IMPORTED_SUPPLEMENT = [
  {
    name: 'Turkey Import Suit Fabric (Thaan)',
    brand: 'Turkey',
    category: 'Imported Fabric',
    unit: 'thaan',
    price: 9800,
    compare_price: 11500,
    cost_price: 7200,
    stock: 18,
    sku: 'TW-IMP-TR-TH-001',
    description: 'Imported suit fabric thaan (~35m), Turkey origin wholesale lot.',
    image_url: stockImage('1586796640118-4811f0880a72'),
    domain_data: {
      fabrictype: 'Wash & Wear',
      korafinished: 'Finished',
      thaanlength: 35,
      sourcing: 'imported',
      origin: 'Turkey',
    },
    is_featured: true,
  },
  {
    name: 'China Synthetic Thaan Roll',
    brand: 'China',
    category: 'Imported Fabric',
    unit: 'thaan',
    price: 6200,
    cost_price: 4800,
    stock: 25,
    sku: 'TW-IMP-CN-TH-002',
    description: 'Imported polyester blend thaan for budget wholesale.',
    image_url: stockImage('1509042237730-0909102a63ed'),
    domain_data: {
      fabrictype: 'Wash & Wear',
      korafinished: 'Dyed',
      thaanlength: 40,
      sourcing: 'imported',
      origin: 'China',
    },
  },
  {
    name: 'Lunda Bazaar Surplus Lawn Lot',
    brand: 'Imported',
    category: 'Lunda Bazaar',
    unit: 'suit',
    price: 2200,
    compare_price: 3200,
    cost_price: 1400,
    stock: 60,
    sku: 'TW-LND-LWN-003',
    description: 'Surplus / second-grade imported lawn suits, Lunda sourcing.',
    image_url: fashionStockImage(U.summer),
    domain_data: {
      fabrictype: 'Lawn',
      korafinished: 'Printed',
      sourcing: 'imported',
      origin: 'Lunda Bazaar',
    },
  },
  {
    name: 'UAE Import Chiffon Roll',
    brand: 'UAE',
    category: 'Imported Fabric',
    unit: 'thaan',
    price: 14500,
    cost_price: 11200,
    stock: 12,
    sku: 'TW-IMP-UAE-CH-004',
    description: 'Imported chiffon roll for formal / bridal wholesale.',
    image_url: fashionStockImage(U.chiffon || U.embroidered),
    domain_data: {
      fabrictype: 'Chiffon',
      korafinished: 'Embroidered',
      thaanlength: 30,
      sourcing: 'imported',
      origin: 'UAE',
    },
  },
];
