/**
 * Pakistani pharmacy demo catalog — realistic OTC/Rx names, PKR pricing, and
 * vertical-matched stock imagery (Unsplash license / Wikimedia Commons).
 */
import { buildUnsplashImageUrl } from '../storefront/unsplashUrl.js';

/** @param {string} photoId Unsplash photo id (after "photo-") @param {number} [w] */
function stockImage(photoId, w = 800) {
  return buildUnsplashImageUrl(photoId, { w, q: 82 });
}

/** @type {Array<Record<string, unknown>>} */
export const PHARMACY_SEED_PRODUCTS = [
  {
    name: 'Panadol Extra 20 Tablets',
    brand: 'GSK',
    category: 'Pain Relief',
    unit: 'pack',
    price: 85,
    cost_price: 68,
    stock: 240,
    sku: 'PH-PAN-EXT-20',
    description: 'Paracetamol 500mg + Caffeine 65mg for headache, fever, and body aches. Pakistan\'s trusted OTC pain reliever.',
    image_url: stockImage('1584308666744-24d5c474f2ae'),
    is_featured: true,
    domain_data: { scheduleh1: false, genericname: 'Paracetamol + Caffeine' },
  },
  {
    name: 'Brufen 400mg 20 Tablets',
    brand: 'Abbott',
    category: 'Pain Relief',
    unit: 'pack',
    price: 120,
    cost_price: 95,
    stock: 180,
    sku: 'PH-BRF-400-20',
    description: 'Ibuprofen 400mg for pain, inflammation, and fever. Take after food.',
    image_url: stockImage('1584308666744-24d5c474f2ae'),
    is_featured: true,
    domain_data: { scheduleh1: false, genericname: 'Ibuprofen' },
  },
  {
    name: 'Disprin 20 Tablets',
    brand: 'Reckitt',
    category: 'Pain Relief',
    unit: 'pack',
    price: 45,
    cost_price: 34,
    stock: 200,
    sku: 'PH-DSP-20',
    description: 'Aspirin 300mg soluble tablets for headache and mild pain relief.',
    image_url: stockImage('1585438852943-f934de1c6cad'),
    domain_data: { scheduleh1: false, genericname: 'Aspirin' },
  },
  {
    name: 'Panadol CF (Cold & Flu) 10 Tablets',
    brand: 'GSK',
    category: 'Cough & Cold',
    unit: 'pack',
    price: 95,
    compare_price: 110,
    cost_price: 76,
    stock: 120,
    sku: 'PH-PAN-CF-10',
    description: 'Relieves blocked nose, runny nose, fever, and body aches from cold and flu.',
    image_url: stockImage('1584308666744-24d5c474f2ae'),
    domain_data: { scheduleh1: false },
  },
  {
    name: 'Augmentin 625mg 14 Tablets',
    brand: 'GSK',
    category: 'Antibiotics',
    unit: 'pack',
    price: 450,
    cost_price: 380,
    stock: 45,
    sku: 'PH-AUG-625-14',
    description: 'Amoxicillin + Clavulanic acid. Prescription antibiotic — valid Rx required before dispatch.',
    image_url: stockImage('1471869640468-c56530f4c4d2'),
    domain_data: { scheduleh1: true, genericname: 'Co-amoxiclav' },
  },
  {
    name: 'Centrum Adults Multivitamin 30 Tablets',
    brand: 'Centrum',
    category: 'Vitamins',
    unit: 'pack',
    price: 3200,
    compare_price: 3600,
    cost_price: 2650,
    stock: 35,
    sku: 'PH-CEN-AD-30',
    description: 'Complete multivitamin with minerals for daily energy, immunity, and wellness support.',
    image_url: stockImage('1550572017-edd390b6992c'),
    is_featured: true,
  },
  {
    name: 'Surbex Z 30 Tablets',
    brand: 'Abbott',
    category: 'Vitamins',
    unit: 'pack',
    price: 850,
    cost_price: 680,
    stock: 60,
    sku: 'PH-SRB-Z-30',
    description: 'B-complex with zinc for energy metabolism and healthy skin.',
    image_url: stockImage('1550572017-edd390b6992c'),
  },
  {
    name: 'Osnate D 30 Tablets',
    brand: 'Martin Dow',
    category: 'Vitamins',
    unit: 'pack',
    price: 450,
    cost_price: 360,
    stock: 75,
    sku: 'PH-OSN-D-30',
    description: 'Calcium + Vitamin D3 for bone strength — commonly prescribed for deficiency.',
    image_url: stockImage('1584308666744-24d5c474f2ae'),
  },
  {
    name: 'Dettol Antiseptic Liquid 750ml',
    brand: 'Dettol',
    category: 'Personal Care',
    unit: 'pcs',
    price: 520,
    cost_price: 410,
    stock: 80,
    sku: 'PH-DET-750',
    description: 'Antiseptic disinfectant for first aid, surface cleaning, and personal hygiene.',
    image_url: stockImage('1585421514738-01798e348b17'),
    is_featured: true,
  },
  {
    name: 'Sensodyne Repair & Protect 100g',
    brand: 'GSK',
    category: 'Personal Care',
    unit: 'pcs',
    price: 680,
    compare_price: 750,
    cost_price: 540,
    stock: 55,
    sku: 'PH-SEN-RP-100',
    description: 'Toothpaste for sensitive teeth with NovaMin technology for daily protection.',
    image_url: stockImage('1607611568730-7d8a1a2612d4'),
  },
  {
    name: "Johnson's Baby Shampoo 200ml",
    brand: "Johnson's",
    category: 'Mother & Baby',
    unit: 'pcs',
    price: 420,
    cost_price: 330,
    stock: 70,
    sku: 'PH-JNJ-SHP-200',
    description: 'No-more-tears formula, dermatologist-tested, gentle for newborn scalp and hair.',
    image_url: stockImage('1555252333-9f8e92e65df9'),
  },
  {
    name: 'Nestle NAN Optipro Stage 1 (400g)',
    brand: 'Nestle',
    category: 'Mother & Baby',
    unit: 'pcs',
    price: 1850,
    compare_price: 1990,
    cost_price: 1520,
    stock: 40,
    sku: 'PH-NAN-S1-400',
    description: 'Infant formula with OPTIPRO for babies from birth when breastfeeding is insufficient.',
    image_url: stockImage('1584515933481-77f14e65bba3'),
    is_featured: true,
  },
  {
    name: 'Pampers Baby Dry Size 3 (42 pcs)',
    brand: 'Pampers',
    category: 'Mother & Baby',
    unit: 'pack',
    price: 1450,
    cost_price: 1180,
    stock: 50,
    sku: 'PH-PMP-S3-42',
    description: 'Up to 12 hours dryness for babies 6–10 kg. Soft waistband and leak guards.',
    image_url: stockImage('1555252333-9f8e92e65df9'),
  },
  {
    name: 'Neutrogena Hydro Boost Water Gel 50ml',
    brand: 'Neutrogena',
    category: 'Skin Care',
    unit: 'pcs',
    price: 2200,
    compare_price: 2450,
    cost_price: 1780,
    stock: 28,
    sku: 'PH-NEU-HB-50',
    description: 'Hyaluronic acid gel moisturiser for long-lasting hydration on normal to oily skin.',
    image_url: stockImage('1570172619644-dfd955f5b7a3'),
  },
  {
    name: 'Cetaphil Gentle Skin Cleanser 237ml',
    brand: 'Galderma',
    category: 'Skin Care',
    unit: 'pcs',
    price: 1650,
    cost_price: 1320,
    stock: 32,
    sku: 'PH-CET-GSC-237',
    description: 'Soap-free cleanser for sensitive and dry skin — face and body.',
    image_url: stockImage('1556228720-195a672e8a03'),
  },
  {
    name: 'Accu-Chek Active Strips (50)',
    brand: 'Roche',
    category: 'Diabetes Care',
    unit: 'pack',
    price: 1850,
    cost_price: 1520,
    stock: 22,
    sku: 'PH-ACC-50',
    description: 'Blood glucose test strips for Accu-Chek Active meter. Box of 50.',
    image_url: stockImage('1576091160550-2173dba999ef'),
    is_featured: true,
  },
  {
    name: 'Omron Blood Pressure Monitor M2',
    brand: 'Omron',
    category: 'Devices',
    unit: 'pcs',
    price: 6500,
    compare_price: 7200,
    cost_price: 5400,
    stock: 12,
    sku: 'PH-OMR-M2',
    description: 'Automatic upper-arm BP monitor with IntelliSense cuff — clinic-grade home use.',
    image_url: stockImage('1559757148-5c350d0d3c56'),
  },
  {
    name: 'Concor 5mg 30 Tablets',
    brand: 'Merck',
    category: 'Medicines',
    unit: 'pack',
    price: 380,
    cost_price: 300,
    stock: 55,
    sku: 'PH-CON-5-30',
    description: 'Bisoprolol 5mg for hypertension and heart conditions. Prescription required.',
    image_url: stockImage('1584308666744-24d5c474f2ae'),
    domain_data: { scheduleh1: true, genericname: 'Bisoprolol' },
  },
  {
    name: 'Glucophage 500mg 20 Tablets',
    brand: 'Merck',
    category: 'Diabetes Care',
    unit: 'pack',
    price: 195,
    cost_price: 155,
    stock: 90,
    sku: 'PH-GLU-500-20',
    description: 'Metformin 500mg for type 2 diabetes management. Valid prescription required.',
    image_url: stockImage('1576091160550-2173dba999ef'),
    domain_data: { scheduleh1: true, genericname: 'Metformin' },
  },
  {
    name: 'Actifed Syrup 120ml',
    brand: 'GSK',
    category: 'Cough & Cold',
    unit: 'pcs',
    price: 165,
    cost_price: 130,
    stock: 65,
    sku: 'PH-ACT-SYP-120',
    description: 'Relieves nasal congestion, runny nose, and sneezing from allergies and colds.',
    image_url: stockImage('1584308666744-24d5c474f2ae'),
  },
  {
    name: 'Livogen Tonic 200ml',
    brand: 'Abbott',
    category: 'Vitamins',
    unit: 'pcs',
    price: 320,
    compare_price: 360,
    cost_price: 250,
    stock: 85,
    sku: 'PH-LIV-TON-200',
    description: 'Iron + folic acid tonic for fatigue and iron deficiency anaemia support.',
    image_url: stockImage('1550572017-edd390b6992c'),
  },
  {
    name: 'Hansaplast Washproof Plasters 20s',
    brand: 'Hansaplast',
    category: 'First Aid',
    unit: 'pack',
    price: 180,
    cost_price: 140,
    stock: 100,
    sku: 'PH-HNS-PL-20',
    description: 'Waterproof adhesive bandages for minor cuts and grazes.',
    image_url: stockImage('1584308666744-24d5c474f2ae'),
  },
  {
    name: 'Volini Spray 60g',
    brand: 'Sanofi',
    category: 'Pain Relief',
    unit: 'pcs',
    price: 450,
    compare_price: 495,
    cost_price: 360,
    stock: 48,
    sku: 'PH-VOL-SPR-60',
    description: 'Diclofenac topical spray for muscle pain, sprains, and joint stiffness.',
    image_url: stockImage('1571019614242-c5c5dee9f50b'),
  },
  {
    name: 'Softcal 30 Tablets',
    brand: 'Getz Pharma',
    category: 'Vitamins',
    unit: 'pack',
    price: 280,
    cost_price: 220,
    stock: 110,
    sku: 'PH-SFT-30',
    description: 'Calcium supplement with Vitamin D for bone health — popular in Pakistan.',
    image_url: stockImage('1584308666744-24d5c474f2ae'),
  },
];
