/**
 * Roll Inn demo menu — sourced from https://rollinnbbq.pk/ (eatx.pk public API).
 * Images hosted on services.eatx.pk ProductImages CDN.
 * Regenerate: node scripts/fetch-rollinn-menu.mjs && node scripts/build-rollinn-restaurant-catalog.mjs
 */
export const RESTAURANT_SEED_BRAND = "Roll Inn";

export const RESTAURANT_SEED_CATEGORIES = [
  {
    "name": "Combos",
    "slug": "combos",
    "image_url": "https://services.eatx.pk/CategoryImages/501c5e03-6759-468b-acf5-6165188069bd.jpeg"
  },
  {
    "name": "Deals",
    "slug": "deals",
    "image_url": "https://services.eatx.pk/CategoryImages/f0cad0aa-4102-41ad-8bca-b0a08cbe6efa.jpeg"
  },
  {
    "name": "Special Roll",
    "slug": "special-roll",
    "image_url": "https://services.eatx.pk/CategoryImages/38cd4ff0-e423-449e-a0f0-8149f587f28b.jpeg"
  },
  {
    "name": "Rolls",
    "slug": "rolls",
    "image_url": "https://services.eatx.pk/CategoryImages/fd8f69a1-7949-4325-825d-78d1ee1964a5.jpeg"
  },
  {
    "name": "BBQ",
    "slug": "bbq",
    "image_url": "https://services.eatx.pk/CategoryImages/d27eaddf-be36-4430-ba9c-e0337d487193.jpeg"
  },
  {
    "name": "Chicken Burger",
    "slug": "chicken-burger",
    "image_url": "https://services.eatx.pk/CategoryImages/b1166e15-eed7-4c49-a880-4823d696e9f5.jpeg"
  },
  {
    "name": "Beef Burgers",
    "slug": "beef-burgers",
    "image_url": "https://services.eatx.pk/CategoryImages/0a988b60-99d2-439d-a31c-126f06e18605.jpeg"
  },
  {
    "name": "Sandwiches",
    "slug": "sandwiches",
    "image_url": "https://services.eatx.pk/CategoryImages/442a4cfa-96e0-4d0b-9d7a-e3b2af1f7666.jpeg"
  },
  {
    "name": "Broast",
    "slug": "broast",
    "image_url": "https://services.eatx.pk/CategoryImages/70706b19-b10d-4d63-9051-3ffc5b6b9f59.jpeg"
  },
  {
    "name": "French Fries",
    "slug": "french-fries",
    "image_url": "https://services.eatx.pk/CategoryImages/db0147c7-1c16-4f17-aecb-4254471f7f20.jpeg"
  },
  {
    "name": "Chicken Chinese",
    "slug": "chicken-chinese",
    "image_url": "https://services.eatx.pk/CategoryImages/67c9701d-5812-42bb-ac76-f35d6af679e6.png"
  },
  {
    "name": "Noodles",
    "slug": "noodles",
    "image_url": "https://services.eatx.pk/CategoryImages/3fdef80e-4f28-43eb-930f-87ffea0971d9.jpeg"
  },
  {
    "name": "Beef Chinese with Rice",
    "slug": "beef-chinese-with-rice",
    "image_url": ""
  },
  {
    "name": "Soup",
    "slug": "soup",
    "image_url": "https://services.eatx.pk/CategoryImages/8ba5a384-14b2-46b7-8869-b573bdf06391.jpeg"
  },
  {
    "name": "Biryani",
    "slug": "biryani",
    "image_url": "https://services.eatx.pk/CategoryImages/5a01034f-a9e5-4a92-bd19-da04ccc9c14e.jpeg"
  },
  {
    "name": "Rice",
    "slug": "rice",
    "image_url": "https://services.eatx.pk/CategoryImages/d07e61c9-3aab-4450-8d95-aee692f60ade.jpeg"
  },
  {
    "name": "Pizza",
    "slug": "pizza",
    "image_url": "https://services.eatx.pk/CategoryImages/659d7eda-e5b0-4f77-bec8-d074a5ea1bec.jpeg"
  },
  {
    "name": "Lemonade",
    "slug": "lemonade",
    "image_url": "https://services.eatx.pk/CategoryImages/228eef3a-e36b-4c11-9dfb-9edf65542059.jpeg"
  },
  {
    "name": "Exclusive Soda",
    "slug": "exclusive-soda",
    "image_url": "https://services.eatx.pk/CategoryImages/1f3ca102-1b6f-45ca-a67e-56deeeddad02.jpeg"
  },
  {
    "name": "Premium Soda Flavors",
    "slug": "premium-soda-flavors",
    "image_url": "https://services.eatx.pk/CategoryImages/c0a94c39-86e1-4a8e-927e-159ea4376a86.jpeg"
  },
  {
    "name": "Beverages",
    "slug": "beverages",
    "image_url": "https://services.eatx.pk/CategoryImages/e71bb57d-21f5-4489-87c4-353911bae1c5.jpeg"
  },
  {
    "name": "Extras",
    "slug": "extras",
    "image_url": "https://services.eatx.pk/CategoryImages/0617a57f-34c0-451d-856f-697f2ffeaba4.jpeg"
  }
];

export const RESTAURANT_SEED_PRODUCTS = [
  {
    "name": "Beef Behari Boti",
    "brand": "Roll Inn",
    "category": "BBQ",
    "unit": "portion",
    "price": 600,
    "compare_price": 750,
    "cost_price": 228,
    "stock": 999,
    "sku": "RIN-8472",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/d838a46d-20b8-4146-a349-ace9101c9e57.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2407,
      "category_slug": "bbq",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Beef Kabab",
    "brand": "Roll Inn",
    "category": "BBQ",
    "unit": "portion",
    "price": 600,
    "compare_price": 750,
    "cost_price": 228,
    "stock": 999,
    "sku": "RIN-8520",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/73e4c17e-f534-4398-ae98-a1af15727377.png",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2407,
      "category_slug": "bbq",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chapati",
    "brand": "Roll Inn",
    "category": "BBQ",
    "unit": "portion",
    "price": 48,
    "compare_price": 60,
    "cost_price": 50,
    "stock": 999,
    "sku": "RIN-8473",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/8bbf5333-ddf6-421f-80c5-9793a6e5a696.jpeg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2407,
      "category_slug": "bbq",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Behari Boti",
    "brand": "Roll Inn",
    "category": "BBQ",
    "unit": "portion",
    "price": 600,
    "compare_price": 750,
    "cost_price": 228,
    "stock": 999,
    "sku": "RIN-8467",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/fb8de0be-aaf1-4db3-a21f-393a8bff8b50.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2407,
      "category_slug": "bbq",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Behari Tikka",
    "brand": "Roll Inn",
    "category": "BBQ",
    "unit": "portion",
    "price": 432,
    "compare_price": 540,
    "cost_price": 164,
    "stock": 999,
    "sku": "RIN-8466",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/aa41ff12-888b-4b93-8042-fce0a22ed24c.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2407,
      "category_slug": "bbq",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Boti",
    "brand": "Roll Inn",
    "category": "BBQ",
    "unit": "portion",
    "price": 600,
    "compare_price": 750,
    "cost_price": 228,
    "stock": 999,
    "sku": "RIN-8469",
    "description": "Chicken Boti from Roll Inn — prepared fresh with authentic Desi BBQ flavour.",
    "image_url": "https://services.eatx.pk/ProductImages/282f0eac-4773-4afd-8f64-25d73d60fc59.avif",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2407,
      "category_slug": "bbq",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Malai Boti",
    "brand": "Roll Inn",
    "category": "BBQ",
    "unit": "portion",
    "price": 600,
    "compare_price": 750,
    "cost_price": 228,
    "stock": 999,
    "sku": "RIN-8468",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/4de6a3f5-4746-4164-9ef4-f99ab13963e8.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2407,
      "category_slug": "bbq",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Reshmi Kabab",
    "brand": "Roll Inn",
    "category": "BBQ",
    "unit": "portion",
    "price": 600,
    "compare_price": 750,
    "cost_price": 228,
    "stock": 999,
    "sku": "RIN-8471",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/247b32c4-788a-4e50-8209-63216d3a60d8.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2407,
      "category_slug": "bbq",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Tikka",
    "brand": "Roll Inn",
    "category": "BBQ",
    "unit": "portion",
    "price": 432,
    "compare_price": 540,
    "cost_price": 164,
    "stock": 999,
    "sku": "RIN-8470",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/c95c98b4-a9aa-4bca-8003-52c72cc2bd42.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2407,
      "category_slug": "bbq",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Paratha",
    "brand": "Roll Inn",
    "category": "BBQ",
    "unit": "portion",
    "price": 48,
    "compare_price": 60,
    "cost_price": 50,
    "stock": 999,
    "sku": "RIN-8474",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/769abd1f-eb86-4e80-a7d0-91b3d1eae3b3.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2407,
      "category_slug": "bbq",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "250ml Buddy Pack",
    "brand": "Roll Inn",
    "category": "Beverages",
    "unit": "pcs",
    "price": 80,
    "compare_price": 100,
    "cost_price": 50,
    "stock": 999,
    "sku": "RIN-8581",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/39a2db17-bdb3-419c-bc4e-3c25adb2b84c.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2422,
      "category_slug": "beverages",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Water",
    "brand": "Roll Inn",
    "category": "Beverages",
    "unit": "pcs",
    "price": 64,
    "compare_price": 80,
    "cost_price": 50,
    "stock": 999,
    "sku": "RIN-8564",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/444e157b-3beb-4d51-946b-0fea50408e42.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2422,
      "category_slug": "beverages",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "BBQ Boneless Handi Biryani",
    "brand": "Roll Inn",
    "category": "Biryani",
    "unit": "portion",
    "price": 560,
    "compare_price": 700,
    "cost_price": 213,
    "stock": 999,
    "sku": "RIN-8508",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/d59179ec-ecb2-4234-8808-1b0b9a1856ab.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2412,
      "category_slug": "biryani",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Tikka Biryani",
    "brand": "Roll Inn",
    "category": "Biryani",
    "unit": "portion",
    "price": 480,
    "compare_price": 600,
    "cost_price": 182,
    "stock": 999,
    "sku": "RIN-8507",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/60f4ca4c-de06-4b85-a676-eef2a2976efd.jpg",
    "is_featured": true,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2412,
      "category_slug": "biryani",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "BBQ Broast",
    "brand": "Roll Inn",
    "category": "Broast",
    "unit": "portion",
    "price": 528,
    "compare_price": 660,
    "cost_price": 201,
    "stock": 999,
    "sku": "RIN-8506",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/6496cce2-7ae9-4f1d-bd0f-4cfecd311ec1.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2411,
      "category_slug": "broast",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chatpata Broast",
    "brand": "Roll Inn",
    "category": "Broast",
    "unit": "portion",
    "price": 528,
    "compare_price": 660,
    "cost_price": 201,
    "stock": 999,
    "sku": "RIN-8505",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/e7915f5a-54a1-4143-b2b1-eb36e2bdb216.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2411,
      "category_slug": "broast",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Cheese Broast",
    "brand": "Roll Inn",
    "category": "Broast",
    "unit": "portion",
    "price": 528,
    "compare_price": 660,
    "cost_price": 201,
    "stock": 999,
    "sku": "RIN-8504",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/664c2a66-6b92-4b3a-9e83-664e26931078.png",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2411,
      "category_slug": "broast",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Crispy Broast",
    "brand": "Roll Inn",
    "category": "Broast",
    "unit": "portion",
    "price": 488,
    "compare_price": 610,
    "cost_price": 185,
    "stock": 999,
    "sku": "RIN-8498",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/2b48029f-922a-43d4-b63b-72aed56dee7a.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2411,
      "category_slug": "broast",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Masala Broast",
    "brand": "Roll Inn",
    "category": "Broast",
    "unit": "portion",
    "price": 488,
    "compare_price": 610,
    "cost_price": 185,
    "stock": 999,
    "sku": "RIN-8501",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/357fd984-1c0b-43ce-a29f-98bfa9700f2c.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2411,
      "category_slug": "broast",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Mayo Garlic Broast",
    "brand": "Roll Inn",
    "category": "Broast",
    "unit": "portion",
    "price": 528,
    "compare_price": 660,
    "cost_price": 201,
    "stock": 999,
    "sku": "RIN-8503",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/d849b57e-494a-4f6d-a409-dec1a12c0b57.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2411,
      "category_slug": "broast",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chatpata Cheese Burger",
    "brand": "Roll Inn",
    "category": "Chicken Burger",
    "unit": "portion",
    "price": 416,
    "compare_price": 520,
    "cost_price": 158,
    "stock": 999,
    "sku": "RIN-8482",
    "description": "Chatpata Cheese Burger from Roll Inn — prepared fresh with authentic Desi BBQ flavour.",
    "image_url": "https://services.eatx.pk/ProductImages/a666a917-58bd-4576-9af0-d9ab0bd79d0c.webp",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2409,
      "category_slug": "chicken-burger",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Burger",
    "brand": "Roll Inn",
    "category": "Chicken Burger",
    "unit": "portion",
    "price": 352,
    "compare_price": 440,
    "cost_price": 134,
    "stock": 999,
    "sku": "RIN-8480",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/f1e67a16-1afa-492f-b2e4-0351f1251aac.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2409,
      "category_slug": "chicken-burger",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Cheese Burger",
    "brand": "Roll Inn",
    "category": "Chicken Burger",
    "unit": "portion",
    "price": 416,
    "compare_price": 520,
    "cost_price": 158,
    "stock": 999,
    "sku": "RIN-8481",
    "description": "Chicken Cheese Burger from Roll Inn — prepared fresh with authentic Desi BBQ flavour.",
    "image_url": "https://services.eatx.pk/ProductImages/df3d9831-8e18-4a0d-9a1e-9209d32c4aff.webp",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2409,
      "category_slug": "chicken-burger",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Jalapeno Cheese Burger",
    "brand": "Roll Inn",
    "category": "Chicken Burger",
    "unit": "portion",
    "price": 552,
    "compare_price": 690,
    "cost_price": 210,
    "stock": 999,
    "sku": "RIN-8486",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/58ea9d8a-5fc6-4268-aa8a-0f1f51a4da73.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2409,
      "category_slug": "chicken-burger",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Stuff Jalapeno Burger",
    "brand": "Roll Inn",
    "category": "Chicken Burger",
    "unit": "portion",
    "price": 552,
    "compare_price": 690,
    "cost_price": 210,
    "stock": 999,
    "sku": "RIN-8487",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/e7f5c1a5-5156-44e4-bd9f-7e9e0bd0fda2.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2409,
      "category_slug": "chicken-burger",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Crispy with Cheese Burger",
    "brand": "Roll Inn",
    "category": "Chicken Burger",
    "unit": "portion",
    "price": 536,
    "compare_price": 670,
    "cost_price": 204,
    "stock": 999,
    "sku": "RIN-8483",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/aef7042b-30b3-4729-98c7-193f374d6d17.webp",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2409,
      "category_slug": "chicken-burger",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Grill Cheese Burger",
    "brand": "Roll Inn",
    "category": "Chicken Burger",
    "unit": "portion",
    "price": 496,
    "compare_price": 620,
    "cost_price": 188,
    "stock": 999,
    "sku": "RIN-8485",
    "description": "Grill Cheese Burger from Roll Inn — prepared fresh with authentic Desi BBQ flavour.",
    "image_url": "https://services.eatx.pk/ProductImages/ce80b168-e914-49e8-a448-3c7df23d94ec.webp",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2409,
      "category_slug": "chicken-burger",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Mega Crispy with Cheese Burger",
    "brand": "Roll Inn",
    "category": "Chicken Burger",
    "unit": "portion",
    "price": 680,
    "compare_price": 850,
    "cost_price": 258,
    "stock": 999,
    "sku": "RIN-8484",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/58137f83-0132-4a6d-b96a-7d63ff8bdff8.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2409,
      "category_slug": "chicken-burger",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Chili Dry",
    "brand": "Roll Inn",
    "category": "Chicken Chinese",
    "unit": "portion",
    "price": 776,
    "compare_price": 970,
    "cost_price": 295,
    "stock": 999,
    "sku": "RIN-8515",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/2a78b0b7-d3f8-4a13-94f4-d2d5533704ed.jpeg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2414,
      "category_slug": "chicken-chinese",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Chili Onion",
    "brand": "Roll Inn",
    "category": "Chicken Chinese",
    "unit": "portion",
    "price": 688,
    "compare_price": 860,
    "cost_price": 261,
    "stock": 999,
    "sku": "RIN-8516",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/a6839036-4f38-475e-99be-e3962a9c3377.jpeg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2414,
      "category_slug": "chicken-chinese",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Chili Vegetable",
    "brand": "Roll Inn",
    "category": "Chicken Chinese",
    "unit": "portion",
    "price": 688,
    "compare_price": 860,
    "cost_price": 261,
    "stock": 999,
    "sku": "RIN-8514",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/ebf97fd1-a69c-4bd8-981f-181f0b3fcbd8.jpeg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2414,
      "category_slug": "chicken-chinese",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Ginger Onion",
    "brand": "Roll Inn",
    "category": "Chicken Chinese",
    "unit": "portion",
    "price": 736,
    "compare_price": 920,
    "cost_price": 280,
    "stock": 999,
    "sku": "RIN-8522",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/62ff22a5-8881-4102-b814-9a7359f5cd1b.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2414,
      "category_slug": "chicken-chinese",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Ginger Thai Style",
    "brand": "Roll Inn",
    "category": "Chicken Chinese",
    "unit": "portion",
    "price": 776,
    "compare_price": 970,
    "cost_price": 295,
    "stock": 999,
    "sku": "RIN-8521",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/d471f2b1-fa62-4948-a87d-751f070f7c64.jpeg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2414,
      "category_slug": "chicken-chinese",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Jalfrezi",
    "brand": "Roll Inn",
    "category": "Chicken Chinese",
    "unit": "portion",
    "price": 776,
    "compare_price": 970,
    "cost_price": 295,
    "stock": 999,
    "sku": "RIN-8518",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/30ff1e9d-25f5-4bca-b774-6a04d09046d2.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2414,
      "category_slug": "chicken-chinese",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Manchurian",
    "brand": "Roll Inn",
    "category": "Chicken Chinese",
    "unit": "portion",
    "price": 736,
    "compare_price": 920,
    "cost_price": 280,
    "stock": 999,
    "sku": "RIN-8517",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/9bcbbe6f-a6c4-4ad3-b190-83d6a327ad5d.jpeg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2414,
      "category_slug": "chicken-chinese",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Shashlik",
    "brand": "Roll Inn",
    "category": "Chicken Chinese",
    "unit": "portion",
    "price": 688,
    "compare_price": 860,
    "cost_price": 261,
    "stock": 999,
    "sku": "RIN-8513",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/cc955aed-2c6f-4483-8e55-af13e45c00c6.jpeg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2414,
      "category_slug": "chicken-chinese",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Hot & Sour Chicken",
    "brand": "Roll Inn",
    "category": "Chicken Chinese",
    "unit": "portion",
    "price": 688,
    "compare_price": 860,
    "cost_price": 261,
    "stock": 999,
    "sku": "RIN-8519",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/79c631b0-27ea-46ff-a859-1f4fe7c039fb.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2414,
      "category_slug": "chicken-chinese",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Combo 1",
    "brand": "Roll Inn",
    "category": "Combos",
    "unit": "portion",
    "price": 950,
    "cost_price": 361,
    "stock": 999,
    "sku": "RIN-8585",
    "description": "Chicken Tikka (Leg) with 2pcs Chicken Kebab & 2 Paratha",
    "image_url": "https://services.eatx.pk/ProductImages/11ab6a62-06db-49bd-9c60-b8c1f12dd5d5.jpeg",
    "is_featured": false,
    "on_sale": false,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2401,
      "category_slug": "combos",
      "is_deal": true,
      "product_tag": null
    }
  },
  {
    "name": "Combo 10",
    "brand": "Roll Inn",
    "category": "Combos",
    "unit": "portion",
    "price": 750,
    "cost_price": 285,
    "stock": 999,
    "sku": "RIN-8808",
    "description": "1 Wild Flair Burger 1 Drink",
    "image_url": "https://services.eatx.pk/ProductImages/650d5dd1-0a6a-47f7-aa69-bfc46be20bfb.jpeg",
    "is_featured": false,
    "on_sale": false,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2401,
      "category_slug": "combos",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Combo 11",
    "brand": "Roll Inn",
    "category": "Combos",
    "unit": "portion",
    "price": 750,
    "cost_price": 285,
    "stock": 999,
    "sku": "RIN-13115",
    "description": "1 BBQ Boneless Handi Biryani 1 Drink salad & Raita",
    "image_url": "https://services.eatx.pk/ProductImages/ed47ee3d-cb27-4982-bedc-b0907ffb5e28.jpeg",
    "is_featured": false,
    "on_sale": false,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2401,
      "category_slug": "combos",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Combo 12",
    "brand": "Roll Inn",
    "category": "Combos",
    "unit": "portion",
    "price": 630,
    "cost_price": 239,
    "stock": 999,
    "sku": "RIN-13116",
    "description": "1 Chicken Tikka Biryani 1 Drink Salad & Raita",
    "image_url": "https://services.eatx.pk/ProductImages/04853018-8e79-4add-9c8f-d6b2af3fb0e1.jpeg",
    "is_featured": false,
    "on_sale": false,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2401,
      "category_slug": "combos",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Combo 2",
    "brand": "Roll Inn",
    "category": "Combos",
    "unit": "portion",
    "price": 920,
    "cost_price": 350,
    "stock": 999,
    "sku": "RIN-8586",
    "description": "1 Chicken Tikka 1 Chicken Chutney Roll 2 Paratha Raita & Salad",
    "image_url": "https://services.eatx.pk/ProductImages/d1e60a1f-1dcc-46aa-a6de-8cb0cc22a5cc.jpeg",
    "is_featured": false,
    "on_sale": false,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2401,
      "category_slug": "combos",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Combo 3",
    "brand": "Roll Inn",
    "category": "Combos",
    "unit": "portion",
    "price": 800,
    "cost_price": 304,
    "stock": 999,
    "sku": "RIN-8587",
    "description": "1 Club Sandwich 1 Chicken Chutney Roll Fries",
    "image_url": "https://services.eatx.pk/ProductImages/5c596b47-d76d-4ae4-9b85-6d69e76a7beb.jpeg",
    "is_featured": false,
    "on_sale": false,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2401,
      "category_slug": "combos",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Combo 4",
    "brand": "Roll Inn",
    "category": "Combos",
    "unit": "portion",
    "price": 700,
    "cost_price": 266,
    "stock": 999,
    "sku": "RIN-8588",
    "description": "Any Club Sandwich 1 Drink",
    "image_url": "https://services.eatx.pk/ProductImages/085b4fd0-add5-449a-acd4-6115814bd045.jpeg",
    "is_featured": false,
    "on_sale": false,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2401,
      "category_slug": "combos",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Combo 5",
    "brand": "Roll Inn",
    "category": "Combos",
    "unit": "portion",
    "price": 1000,
    "cost_price": 380,
    "stock": 999,
    "sku": "RIN-8589",
    "description": "1 Crispy Chicken Burger 1 Mayo Garlic Roll Fries",
    "image_url": "https://services.eatx.pk/ProductImages/cd2b92e7-fd72-42d6-bfb1-bf4799ebf5b4.jpeg",
    "is_featured": false,
    "on_sale": false,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2401,
      "category_slug": "combos",
      "is_deal": true,
      "product_tag": null
    }
  },
  {
    "name": "Combo 6",
    "brand": "Roll Inn",
    "category": "Combos",
    "unit": "portion",
    "price": 750,
    "cost_price": 285,
    "stock": 999,
    "sku": "RIN-8590",
    "description": "1 Crispy Chicken Burger 1 Drink",
    "image_url": "https://services.eatx.pk/ProductImages/822f28da-0a5e-438b-ab5c-3e7e9888b180.jpeg",
    "is_featured": false,
    "on_sale": false,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2401,
      "category_slug": "combos",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Combo 7",
    "brand": "Roll Inn",
    "category": "Combos",
    "unit": "portion",
    "price": 860,
    "cost_price": 327,
    "stock": 999,
    "sku": "RIN-8591",
    "description": "1 QTR Broast 1 Chicken Chutney Roll Fries",
    "image_url": "https://services.eatx.pk/ProductImages/df401014-2b5d-4e35-b725-72de36c9ca1f.jpeg",
    "is_featured": false,
    "on_sale": false,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2401,
      "category_slug": "combos",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Combo 8",
    "brand": "Roll Inn",
    "category": "Combos",
    "unit": "portion",
    "price": 800,
    "cost_price": 304,
    "stock": 999,
    "sku": "RIN-8592",
    "description": "1 Stuff Jalapeno Burger 1 Drink",
    "image_url": "https://services.eatx.pk/ProductImages/f45e40ec-aa69-4fdb-b8c1-3a6f74150cfb.jpeg",
    "is_featured": false,
    "on_sale": false,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2401,
      "category_slug": "combos",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Combo 9",
    "brand": "Roll Inn",
    "category": "Combos",
    "unit": "portion",
    "price": 550,
    "cost_price": 209,
    "stock": 999,
    "sku": "RIN-8593",
    "description": "1 Chicken / Beef Burger 1 Drink",
    "image_url": "https://services.eatx.pk/ProductImages/f6836c1d-e823-4fb3-a366-22a2206bdba7.jpeg",
    "is_featured": false,
    "on_sale": false,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2401,
      "category_slug": "combos",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Deal 1",
    "brand": "Roll Inn",
    "category": "Deals",
    "unit": "portion",
    "price": 710,
    "cost_price": 270,
    "stock": 999,
    "sku": "RIN-8577",
    "description": "2 Chicken Chutney Roll 1 Drink",
    "image_url": "https://services.eatx.pk/ProductImages/3bfc9325-75ba-4636-8ac4-376b6e1c042b.jpeg",
    "is_featured": false,
    "on_sale": false,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2402,
      "category_slug": "deals",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Deal 2",
    "brand": "Roll Inn",
    "category": "Deals",
    "unit": "portion",
    "price": 1430,
    "cost_price": 543,
    "stock": 999,
    "sku": "RIN-8578",
    "description": "4 Chicken Chutney Roll 2 Drink",
    "image_url": "https://services.eatx.pk/ProductImages/7ebda3c2-e9d0-40ea-9da3-8c973d8b4854.jpeg",
    "is_featured": false,
    "on_sale": false,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2402,
      "category_slug": "deals",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Deal 3",
    "brand": "Roll Inn",
    "category": "Deals",
    "unit": "portion",
    "price": 3200,
    "cost_price": 1216,
    "stock": 999,
    "sku": "RIN-8579",
    "description": "10 Chicken Chutney Roll 1.5 Liter Drink",
    "image_url": "https://services.eatx.pk/ProductImages/b2c83dea-36ff-4f54-b932-284f5413fa62.jpeg",
    "is_featured": false,
    "on_sale": false,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2402,
      "category_slug": "deals",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Deal 4",
    "brand": "Roll Inn",
    "category": "Deals",
    "unit": "portion",
    "price": 1500,
    "cost_price": 570,
    "stock": 999,
    "sku": "RIN-8580",
    "description": "Chicken Shashlik Chicken Chowmein Corn Soup",
    "image_url": "https://services.eatx.pk/ProductImages/346fc4fb-e4b6-4905-acab-f3e3a5824d62.jpeg",
    "is_featured": false,
    "on_sale": false,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2402,
      "category_slug": "deals",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Deal 5",
    "brand": "Roll Inn",
    "category": "Deals",
    "unit": "portion",
    "price": 610,
    "cost_price": 232,
    "stock": 999,
    "sku": "RIN-8584",
    "description": "1 Small Pizza 1 Drink",
    "image_url": "https://services.eatx.pk/ProductImages/94e3a1fd-cb85-4ca5-8549-b4d5f7076422.jpeg",
    "is_featured": false,
    "on_sale": false,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2402,
      "category_slug": "deals",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Deal 6",
    "brand": "Roll Inn",
    "category": "Deals",
    "unit": "portion",
    "price": 1200,
    "cost_price": 456,
    "stock": 999,
    "sku": "RIN-13118",
    "description": "1 Medium Pizza 2 Drink",
    "image_url": "https://services.eatx.pk/ProductImages/1d9b49aa-89e3-472f-baad-560fa95d44ea.jpeg",
    "is_featured": false,
    "on_sale": false,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2402,
      "category_slug": "deals",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Deal 7",
    "brand": "Roll Inn",
    "category": "Deals",
    "unit": "portion",
    "price": 1500,
    "cost_price": 570,
    "stock": 999,
    "sku": "RIN-13119",
    "description": "1 Large Pizza 1.5 Liter Drink",
    "image_url": "https://services.eatx.pk/ProductImages/91d50f64-eb60-41ab-89ad-d0c60898abb5.jpeg",
    "is_featured": false,
    "on_sale": false,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2402,
      "category_slug": "deals",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Deal 8",
    "brand": "Roll Inn",
    "category": "Deals",
    "unit": "portion",
    "price": 2050,
    "cost_price": 779,
    "stock": 999,
    "sku": "RIN-13120",
    "description": "2 Medium Pizza 1.5 Liter Drink",
    "image_url": "https://services.eatx.pk/ProductImages/7d137f17-3e37-4933-954d-55b2ac5e0145.jpeg",
    "is_featured": false,
    "on_sale": false,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2402,
      "category_slug": "deals",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Apple Sidra Soda",
    "brand": "Roll Inn",
    "category": "Exclusive Soda",
    "unit": "pcs",
    "price": 168,
    "compare_price": 210,
    "cost_price": 64,
    "stock": 999,
    "sku": "RIN-8545",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/3ec7874e-2ba9-4660-9311-8752e00f97aa.png",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2417,
      "category_slug": "exclusive-soda",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Black Current Soda",
    "brand": "Roll Inn",
    "category": "Exclusive Soda",
    "unit": "pcs",
    "price": 168,
    "compare_price": 210,
    "cost_price": 64,
    "stock": 999,
    "sku": "RIN-8538",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/0eb391ec-6eb5-4e92-9d6d-ece2fc68a62e.png",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2417,
      "category_slug": "exclusive-soda",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Blood Orange Soda",
    "brand": "Roll Inn",
    "category": "Exclusive Soda",
    "unit": "pcs",
    "price": 168,
    "compare_price": 210,
    "cost_price": 64,
    "stock": 999,
    "sku": "RIN-8546",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/6be67f2f-380e-4301-a853-bc84a9fa53a5.png",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2417,
      "category_slug": "exclusive-soda",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Blueberry Soda",
    "brand": "Roll Inn",
    "category": "Exclusive Soda",
    "unit": "pcs",
    "price": 168,
    "compare_price": 210,
    "cost_price": 64,
    "stock": 999,
    "sku": "RIN-8537",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/ff96cab0-35e8-4ec0-bfa6-715d187578b0.png",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2417,
      "category_slug": "exclusive-soda",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Ginger Soda",
    "brand": "Roll Inn",
    "category": "Exclusive Soda",
    "unit": "pcs",
    "price": 168,
    "compare_price": 210,
    "cost_price": 64,
    "stock": 999,
    "sku": "RIN-8535",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/4472badb-8b19-490a-9dbb-1bc7533c17fa.png",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2417,
      "category_slug": "exclusive-soda",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Green Apple Soda",
    "brand": "Roll Inn",
    "category": "Exclusive Soda",
    "unit": "pcs",
    "price": 168,
    "compare_price": 210,
    "cost_price": 64,
    "stock": 999,
    "sku": "RIN-8541",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/295e1b8b-aad3-4813-b1d6-136a2cb25e9a.png",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2417,
      "category_slug": "exclusive-soda",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Ice Cream Soda",
    "brand": "Roll Inn",
    "category": "Exclusive Soda",
    "unit": "pcs",
    "price": 168,
    "compare_price": 210,
    "cost_price": 64,
    "stock": 999,
    "sku": "RIN-8536",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/d93d0e64-6db7-4482-8f3f-7a97a2825b84.png",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2417,
      "category_slug": "exclusive-soda",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Lemon Soda",
    "brand": "Roll Inn",
    "category": "Exclusive Soda",
    "unit": "pcs",
    "price": 168,
    "compare_price": 210,
    "cost_price": 64,
    "stock": 999,
    "sku": "RIN-8534",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/0a61a05e-5c1b-4a11-9bba-6f59748b8f76.png",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2417,
      "category_slug": "exclusive-soda",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Lychee Soda",
    "brand": "Roll Inn",
    "category": "Exclusive Soda",
    "unit": "pcs",
    "price": 168,
    "compare_price": 210,
    "cost_price": 64,
    "stock": 999,
    "sku": "RIN-8539",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/593eb22e-7988-45c3-bc48-ef0321d2b789.png",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2417,
      "category_slug": "exclusive-soda",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Mango Soda",
    "brand": "Roll Inn",
    "category": "Exclusive Soda",
    "unit": "pcs",
    "price": 168,
    "compare_price": 210,
    "cost_price": 64,
    "stock": 999,
    "sku": "RIN-8542",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/7b3d1e0a-1a19-47df-915a-db0a5e1092f9.png",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2417,
      "category_slug": "exclusive-soda",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Peach Soda",
    "brand": "Roll Inn",
    "category": "Exclusive Soda",
    "unit": "pcs",
    "price": 168,
    "compare_price": 210,
    "cost_price": 64,
    "stock": 999,
    "sku": "RIN-8543",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/246df271-02e0-4344-93e9-df9c091470a0.png",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2417,
      "category_slug": "exclusive-soda",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Pineapple Soda",
    "brand": "Roll Inn",
    "category": "Exclusive Soda",
    "unit": "pcs",
    "price": 168,
    "compare_price": 210,
    "cost_price": 64,
    "stock": 999,
    "sku": "RIN-8540",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/391449cb-4e19-4c53-8a38-de9da9e8e000.png",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2417,
      "category_slug": "exclusive-soda",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Pomegranate Soda",
    "brand": "Roll Inn",
    "category": "Exclusive Soda",
    "unit": "pcs",
    "price": 168,
    "compare_price": 210,
    "cost_price": 64,
    "stock": 999,
    "sku": "RIN-8544",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/aeb6d49b-6c07-4b81-90a6-c31540196a92.png",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2417,
      "category_slug": "exclusive-soda",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Raspberry Soda",
    "brand": "Roll Inn",
    "category": "Exclusive Soda",
    "unit": "pcs",
    "price": 168,
    "compare_price": 210,
    "cost_price": 64,
    "stock": 999,
    "sku": "RIN-8533",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/f78bdcba-7094-4b0b-a20a-dca189fb4372.png",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2417,
      "category_slug": "exclusive-soda",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Strawberry Soda",
    "brand": "Roll Inn",
    "category": "Exclusive Soda",
    "unit": "pcs",
    "price": 168,
    "compare_price": 210,
    "cost_price": 64,
    "stock": 999,
    "sku": "RIN-8532",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/e2fe0ce4-c860-490f-b9d8-8fa4781dd6a9.png",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2417,
      "category_slug": "exclusive-soda",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Cheese",
    "brand": "Roll Inn",
    "category": "Extras",
    "unit": "portion",
    "price": 112,
    "compare_price": 140,
    "cost_price": 50,
    "stock": 999,
    "sku": "RIN-8558",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/3aa25378-f8a7-46c0-8cd7-ea3737698cc1.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2421,
      "category_slug": "extras",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Cheese Slice",
    "brand": "Roll Inn",
    "category": "Extras",
    "unit": "portion",
    "price": 112,
    "compare_price": 140,
    "cost_price": 50,
    "stock": 999,
    "sku": "RIN-8560",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/e9e5b4ce-cfe1-4ff1-8c74-383e0645156d.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2421,
      "category_slug": "extras",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Coleslaw",
    "brand": "Roll Inn",
    "category": "Extras",
    "unit": "portion",
    "price": 112,
    "compare_price": 140,
    "cost_price": 50,
    "stock": 999,
    "sku": "RIN-8559",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/5ca682d8-e808-4c2c-b9fd-683ea0eb36a4.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2421,
      "category_slug": "extras",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Garlic",
    "brand": "Roll Inn",
    "category": "Extras",
    "unit": "portion",
    "price": 112,
    "compare_price": 140,
    "cost_price": 50,
    "stock": 999,
    "sku": "RIN-8557",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/f4ce77f6-87cf-4542-9a3a-7ccfdf0220be.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2421,
      "category_slug": "extras",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "BBQ Fries",
    "brand": "Roll Inn",
    "category": "French Fries",
    "unit": "portion",
    "price": 248,
    "compare_price": 310,
    "cost_price": 94,
    "stock": 999,
    "sku": "RIN-8477",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/18bd9e06-24d4-4d12-91c4-fd380f25edbb.jpg",
    "is_featured": true,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2408,
      "category_slug": "french-fries",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Cheese Fries",
    "brand": "Roll Inn",
    "category": "French Fries",
    "unit": "portion",
    "price": 248,
    "compare_price": 310,
    "cost_price": 94,
    "stock": 999,
    "sku": "RIN-8478",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/01a71d5c-503c-462e-beb0-58b2dc2d5d46.jpg",
    "is_featured": true,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2408,
      "category_slug": "french-fries",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Garlic Mayo Fries",
    "brand": "Roll Inn",
    "category": "French Fries",
    "unit": "portion",
    "price": 248,
    "compare_price": 310,
    "cost_price": 94,
    "stock": 999,
    "sku": "RIN-8479",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/427eaba8-1951-4cff-8bea-7176a53f1842.png",
    "is_featured": true,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2408,
      "category_slug": "french-fries",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Masala Fries",
    "brand": "Roll Inn",
    "category": "French Fries",
    "unit": "portion",
    "price": 208,
    "compare_price": 260,
    "cost_price": 79,
    "stock": 999,
    "sku": "RIN-8476",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/6cd60b4c-f128-4c2d-af67-adb3df393ea7.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2408,
      "category_slug": "french-fries",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Regular Fries",
    "brand": "Roll Inn",
    "category": "French Fries",
    "unit": "portion",
    "price": 208,
    "compare_price": 260,
    "cost_price": 79,
    "stock": 999,
    "sku": "RIN-8475",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/4c4b8d8f-62b3-45fb-8b97-952695c699a8.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2408,
      "category_slug": "french-fries",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Blue Lemonade",
    "brand": "Roll Inn",
    "category": "Lemonade",
    "unit": "pcs",
    "price": 280,
    "compare_price": 350,
    "cost_price": 106,
    "stock": 999,
    "sku": "RIN-8531",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/039a12d7-d825-44ba-b6f0-16ab61b85e02.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2416,
      "category_slug": "lemonade",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Fresh Lime",
    "brand": "Roll Inn",
    "category": "Lemonade",
    "unit": "pcs",
    "price": 184,
    "compare_price": 230,
    "cost_price": 70,
    "stock": 999,
    "sku": "RIN-8527",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/0c54b0ff-ba59-4b77-9e29-46c57eb92327.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2416,
      "category_slug": "lemonade",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Lemon and Mint Mojito",
    "brand": "Roll Inn",
    "category": "Lemonade",
    "unit": "pcs",
    "price": 320,
    "compare_price": 400,
    "cost_price": 122,
    "stock": 999,
    "sku": "RIN-8574",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/3e00c6e8-4f89-4804-bb60-9c58f7bdb81e.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2416,
      "category_slug": "lemonade",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Mint Lemonade",
    "brand": "Roll Inn",
    "category": "Lemonade",
    "unit": "pcs",
    "price": 280,
    "compare_price": 350,
    "cost_price": 106,
    "stock": 999,
    "sku": "RIN-8530",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/3420ed16-f9e0-4601-98e6-53cadb0b8c98.jpeg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2416,
      "category_slug": "lemonade",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Raspberry Lemonade",
    "brand": "Roll Inn",
    "category": "Lemonade",
    "unit": "pcs",
    "price": 312,
    "compare_price": 390,
    "cost_price": 119,
    "stock": 999,
    "sku": "RIN-8529",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/63717c05-5389-4122-83ab-fea841c7952c.jpeg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2416,
      "category_slug": "lemonade",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Beef Chowmein",
    "brand": "Roll Inn",
    "category": "Noodles",
    "unit": "portion",
    "price": 688,
    "compare_price": 860,
    "cost_price": 261,
    "stock": 999,
    "sku": "RIN-8573",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/1cb7045e-cc11-49ab-bdf2-ced3d6f60aa8.jpeg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2415,
      "category_slug": "noodles",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Chowmein",
    "brand": "Roll Inn",
    "category": "Noodles",
    "unit": "portion",
    "price": 552,
    "compare_price": 690,
    "cost_price": 210,
    "stock": 999,
    "sku": "RIN-8523",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/df77af73-e923-451c-8c15-6b5f30210772.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2415,
      "category_slug": "noodles",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Roll Inn Special Chowmein",
    "brand": "Roll Inn",
    "category": "Noodles",
    "unit": "portion",
    "price": 688,
    "compare_price": 860,
    "cost_price": 261,
    "stock": 999,
    "sku": "RIN-8526",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/4e80e29e-9615-45eb-ab2e-a51f235618ec.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2415,
      "category_slug": "noodles",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Thai Chowmein",
    "brand": "Roll Inn",
    "category": "Noodles",
    "unit": "portion",
    "price": 592,
    "compare_price": 740,
    "cost_price": 225,
    "stock": 999,
    "sku": "RIN-8524",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/209a3d8b-3d0f-453e-a791-def3bfc52ec4.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2415,
      "category_slug": "noodles",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Vegetable Chowmein",
    "brand": "Roll Inn",
    "category": "Noodles",
    "unit": "portion",
    "price": 464,
    "compare_price": 580,
    "cost_price": 176,
    "stock": 999,
    "sku": "RIN-8525",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/d90eae97-8a78-43c5-ad5f-d655a0ca5145.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2415,
      "category_slug": "noodles",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "All Cheese",
    "brand": "Roll Inn",
    "category": "Pizza",
    "unit": "portion",
    "price": 536,
    "compare_price": 670,
    "cost_price": 204,
    "stock": 999,
    "sku": "RIN-8460",
    "description": "For Those who live life on the cheesy side a fusion of our classic Cheeses, marinara sauce and hand knead bread .",
    "image_url": "https://services.eatx.pk/ProductImages/cb08c1bf-e435-486c-bff4-ccdb182cc59f.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2403,
      "category_slug": "pizza",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Kabab Delight",
    "brand": "Roll Inn",
    "category": "Pizza",
    "unit": "portion",
    "price": 488,
    "compare_price": 610,
    "cost_price": 185,
    "stock": 999,
    "sku": "RIN-8454",
    "description": "Delicious Kabab with a splendid topping of onion jalapeno Cheese & at last BBA mayo sauce on Top",
    "image_url": "https://services.eatx.pk/ProductImages/815a3f9c-ac11-4cbc-812e-bfcc2432867d.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2403,
      "category_slug": "pizza",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Supreme",
    "brand": "Roll Inn",
    "category": "Pizza",
    "unit": "portion",
    "price": 488,
    "compare_price": 610,
    "cost_price": 185,
    "stock": 999,
    "sku": "RIN-8455",
    "description": "Combination of Tikka, Fajita Chicken & Smoked chicken topped with Onion, Capsicum, Mushroom, Olives and Cheese for a twist.",
    "image_url": "https://services.eatx.pk/ProductImages/6a69a18e-a14f-4ded-832c-1d79d27f62dd.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2403,
      "category_slug": "pizza",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Tikka Pizza",
    "brand": "Roll Inn",
    "category": "Pizza",
    "unit": "portion",
    "price": 440,
    "compare_price": 550,
    "cost_price": 167,
    "stock": 999,
    "sku": "RIN-8452",
    "description": "Pizza Topped With Chicken Tikka Cubes, Cheese And Onion",
    "image_url": "https://services.eatx.pk/ProductImages/7cdd745e-c392-4cb7-945b-fdf4fb301add.webp",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2403,
      "category_slug": "pizza",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Fajita Supereme",
    "brand": "Roll Inn",
    "category": "Pizza",
    "unit": "portion",
    "price": 488,
    "compare_price": 610,
    "cost_price": 185,
    "stock": 999,
    "sku": "RIN-8453",
    "description": "Fajita Chicken With the right amount fresh Capsicum, Onion, Jalapeno, Tomato & heavenly Cheese served on an irresistible crust",
    "image_url": "https://services.eatx.pk/ProductImages/9aecf3c1-b4ce-4992-b1c1-750343dc892a.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2403,
      "category_slug": "pizza",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Malai Soft",
    "brand": "Roll Inn",
    "category": "Pizza",
    "unit": "portion",
    "price": 536,
    "compare_price": 670,
    "cost_price": 204,
    "stock": 999,
    "sku": "RIN-8456",
    "description": "Pizza topped with chicken malai boti chunks Onion, Green Peppers & Garlic mayo sauce .",
    "image_url": "https://services.eatx.pk/ProductImages/282b76db-7efe-4121-9247-d8114854f0b5.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2403,
      "category_slug": "pizza",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Peri - Peri Chicken",
    "brand": "Roll Inn",
    "category": "Pizza",
    "unit": "portion",
    "price": 488,
    "compare_price": 610,
    "cost_price": 185,
    "stock": 999,
    "sku": "RIN-8458",
    "description": "A true Mozambique recipe of peri peri sauce adds life to chicken Tikka topping with red thai Chillies Onion & our best Cheese .",
    "image_url": "https://services.eatx.pk/ProductImages/3b67d5f9-4354-4d62-ad3b-cfbf28066013.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2403,
      "category_slug": "pizza",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Roll Inn Special Pizza",
    "brand": "Roll Inn",
    "category": "Pizza",
    "unit": "portion",
    "price": 584,
    "compare_price": 730,
    "cost_price": 222,
    "stock": 999,
    "sku": "RIN-8459",
    "description": "A fusion of all we love sausages, Kaba , Chicken Chunks, Jalapeno & Bell peppers Truly Deluxe.",
    "image_url": "https://services.eatx.pk/ProductImages/70c0fc3b-1b1e-44b0-a57e-9e8d2adea63d.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2403,
      "category_slug": "pizza",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Vegie Lover",
    "brand": "Roll Inn",
    "category": "Pizza",
    "unit": "portion",
    "price": 488,
    "compare_price": 610,
    "cost_price": 185,
    "stock": 999,
    "sku": "RIN-8461",
    "description": "A healthy Take on Pizza ,fresh Onion Capsicum, Mushrooms, Olives, Tomatoes toppes with our best Cheeses",
    "image_url": "https://services.eatx.pk/ProductImages/1dfa8df3-9f67-43a9-adb7-2ece7917fb49.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2403,
      "category_slug": "pizza",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Blue Curracao",
    "brand": "Roll Inn",
    "category": "Premium Soda Flavors",
    "unit": "pcs",
    "price": 200,
    "compare_price": 250,
    "cost_price": 76,
    "stock": 999,
    "sku": "RIN-8550",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/584488fc-6970-449b-89c4-43164c6ba901.png",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2419,
      "category_slug": "premium-soda-flavors",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Blue Hawaii",
    "brand": "Roll Inn",
    "category": "Premium Soda Flavors",
    "unit": "pcs",
    "price": 200,
    "compare_price": 250,
    "cost_price": 76,
    "stock": 999,
    "sku": "RIN-8549",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/d4825609-3b36-4d88-8108-8c979c6d0817.png",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2419,
      "category_slug": "premium-soda-flavors",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Mint",
    "brand": "Roll Inn",
    "category": "Premium Soda Flavors",
    "unit": "pcs",
    "price": 200,
    "compare_price": 250,
    "cost_price": 76,
    "stock": 999,
    "sku": "RIN-8552",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/c950eb4f-d9d8-44e3-aa7a-91ffcde63e24.png",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2419,
      "category_slug": "premium-soda-flavors",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Redbull",
    "brand": "Roll Inn",
    "category": "Premium Soda Flavors",
    "unit": "pcs",
    "price": 200,
    "compare_price": 250,
    "cost_price": 76,
    "stock": 999,
    "sku": "RIN-8547",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/7c7f66c9-9cbb-4a11-9c23-e70717bf435d.png",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2419,
      "category_slug": "premium-soda-flavors",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Vimto",
    "brand": "Roll Inn",
    "category": "Premium Soda Flavors",
    "unit": "pcs",
    "price": 200,
    "compare_price": 250,
    "cost_price": 76,
    "stock": 999,
    "sku": "RIN-8548",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/a4eafa1b-4f5d-4d08-b401-8e9a398ae0dc.png",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2419,
      "category_slug": "premium-soda-flavors",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "X On The Beach",
    "brand": "Roll Inn",
    "category": "Premium Soda Flavors",
    "unit": "pcs",
    "price": 200,
    "compare_price": 250,
    "cost_price": 76,
    "stock": 999,
    "sku": "RIN-8551",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/198b0dfa-f47c-4bb2-9ecb-740eed47a8d8.png",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2419,
      "category_slug": "premium-soda-flavors",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Fried Rice",
    "brand": "Roll Inn",
    "category": "Rice",
    "unit": "portion",
    "price": 552,
    "compare_price": 690,
    "cost_price": 210,
    "stock": 999,
    "sku": "RIN-8510",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/e1ddf24e-7a27-4b4b-8098-0491c16a9689.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2413,
      "category_slug": "rice",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Egg Fried Rice",
    "brand": "Roll Inn",
    "category": "Rice",
    "unit": "portion",
    "price": 504,
    "compare_price": 630,
    "cost_price": 192,
    "stock": 999,
    "sku": "RIN-8511",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/2348a8e2-0d12-49d1-b750-81bb03b07d2b.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2413,
      "category_slug": "rice",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Plain Rice",
    "brand": "Roll Inn",
    "category": "Rice",
    "unit": "portion",
    "price": 368,
    "compare_price": 460,
    "cost_price": 140,
    "stock": 999,
    "sku": "RIN-8509",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/65be24b6-1d0d-4557-a7e3-1c304d572f41.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2413,
      "category_slug": "rice",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Vegetable Fried Rice",
    "brand": "Roll Inn",
    "category": "Rice",
    "unit": "portion",
    "price": 464,
    "compare_price": 580,
    "cost_price": 176,
    "stock": 999,
    "sku": "RIN-8512",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/863cbc1a-9132-4d61-83b7-0483380ac98a.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2413,
      "category_slug": "rice",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Beef Behari Roll With",
    "brand": "Roll Inn",
    "category": "Rolls",
    "unit": "portion",
    "price": 272,
    "compare_price": 340,
    "cost_price": 103,
    "stock": 999,
    "sku": "RIN-8492",
    "description": "Chutney, Cheese, Garlic Mayo, Juicy Sauce, Spicy Ketchup.",
    "image_url": "https://services.eatx.pk/ProductImages/28dc8024-b76b-4afe-8dec-542f61f9e5a0.jpeg",
    "is_featured": true,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2405,
      "category_slug": "rolls",
      "is_deal": true,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Bihari Roll With",
    "brand": "Roll Inn",
    "category": "Rolls",
    "unit": "portion",
    "price": 272,
    "compare_price": 340,
    "cost_price": 103,
    "stock": 999,
    "sku": "RIN-8499",
    "description": "Chutney, Cheese, Garlic Mayo, Juicy Sauce, Spicy Ketchup.",
    "image_url": "https://services.eatx.pk/ProductImages/0910ca26-7b26-4b07-aa84-2d20edc9c005.jpeg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2405,
      "category_slug": "rolls",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Crispy Roll With",
    "brand": "Roll Inn",
    "category": "Rolls",
    "unit": "portion",
    "price": 272,
    "compare_price": 340,
    "cost_price": 103,
    "stock": 999,
    "sku": "RIN-8502",
    "description": "Chutney, Cheese, Garlic Mayo, Juicy Sauce, Spicy Ketchup.",
    "image_url": "https://services.eatx.pk/ProductImages/5f7896c0-9988-446b-a08c-f89524550ed3.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2405,
      "category_slug": "rolls",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Malai Roll With",
    "brand": "Roll Inn",
    "category": "Rolls",
    "unit": "portion",
    "price": 272,
    "compare_price": 340,
    "cost_price": 103,
    "stock": 999,
    "sku": "RIN-8500",
    "description": "Chutney, Cheese, Garlic Mayo, Juicy Sauce, Spicy Ketchup.",
    "image_url": "https://services.eatx.pk/ProductImages/cf218c2d-759c-416e-9746-9c530b437dde.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2405,
      "category_slug": "rolls",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Reshmi Roll With",
    "brand": "Roll Inn",
    "category": "Rolls",
    "unit": "portion",
    "price": 248,
    "compare_price": 310,
    "cost_price": 94,
    "stock": 999,
    "sku": "RIN-8497",
    "description": "Chutney, Cheese, Garlic Mayo, Juicy Sauce, Spicy Ketchup.",
    "image_url": "https://services.eatx.pk/ProductImages/78e8f5fe-c223-4d51-9ed3-462673868623.webp",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2405,
      "category_slug": "rolls",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Roll With",
    "brand": "Roll Inn",
    "category": "Rolls",
    "unit": "portion",
    "price": 248,
    "compare_price": 310,
    "cost_price": 94,
    "stock": 999,
    "sku": "RIN-8491",
    "description": "Chutney, Cheese, Garlic Mayo, Juicy Sauce, Spicy Ketchup.",
    "image_url": "https://services.eatx.pk/ProductImages/d791133a-b052-4a24-bc8d-ac4b5a06043f.webp",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2405,
      "category_slug": "rolls",
      "is_deal": true,
      "product_tag": null
    }
  },
  {
    "name": "B.B.Q Chicken Sandwich",
    "brand": "Roll Inn",
    "category": "Sandwiches",
    "unit": "portion",
    "price": 464,
    "compare_price": 580,
    "cost_price": 176,
    "stock": 999,
    "sku": "RIN-8490",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/dd714896-ecdf-463a-b790-fe6405714118.png",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2410,
      "category_slug": "sandwiches",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Malai Boti Sandwich",
    "brand": "Roll Inn",
    "category": "Sandwiches",
    "unit": "portion",
    "price": 432,
    "compare_price": 540,
    "cost_price": 164,
    "stock": 999,
    "sku": "RIN-8488",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/1dd00fc4-3026-49c6-8d31-a3186a9933f6.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2410,
      "category_slug": "sandwiches",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Club Sandwich",
    "brand": "Roll Inn",
    "category": "Sandwiches",
    "unit": "portion",
    "price": 416,
    "compare_price": 520,
    "cost_price": 158,
    "stock": 999,
    "sku": "RIN-8489",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/c623cad8-9c10-4e62-ae85-e3ae14de14e8.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2410,
      "category_slug": "sandwiches",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Grill Chicken Sandwich",
    "brand": "Roll Inn",
    "category": "Sandwiches",
    "unit": "portion",
    "price": 464,
    "compare_price": 580,
    "cost_price": 176,
    "stock": 999,
    "sku": "RIN-8495",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/52f0472b-f0dc-417b-8dc5-fce4150438ec.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2410,
      "category_slug": "sandwiches",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Roll Inn Special sandwich",
    "brand": "Roll Inn",
    "category": "Sandwiches",
    "unit": "portion",
    "price": 536,
    "compare_price": 670,
    "cost_price": 204,
    "stock": 999,
    "sku": "RIN-8496",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/fce7d69b-9580-47d7-8991-079a218a9ea5.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2410,
      "category_slug": "sandwiches",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Corn Soup",
    "brand": "Roll Inn",
    "category": "Soup",
    "unit": "portion",
    "price": 200,
    "compare_price": 250,
    "cost_price": 76,
    "stock": 999,
    "sku": "RIN-8553",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/f873f3ac-26bc-4ae5-b1db-9c5765d02900.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2420,
      "category_slug": "soup",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Vegetable Soup",
    "brand": "Roll Inn",
    "category": "Soup",
    "unit": "portion",
    "price": 248,
    "compare_price": 310,
    "cost_price": 94,
    "stock": 999,
    "sku": "RIN-8556",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/eb5e2977-4f2f-44d9-a4f4-57f5ffd9a5e2.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2420,
      "category_slug": "soup",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Hot & Sour Soup",
    "brand": "Roll Inn",
    "category": "Soup",
    "unit": "portion",
    "price": 248,
    "compare_price": 310,
    "cost_price": 94,
    "stock": 999,
    "sku": "RIN-8554",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/2d860b5c-ca35-4f31-a5e4-9b83d87615f9.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2420,
      "category_slug": "soup",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Thai Soup",
    "brand": "Roll Inn",
    "category": "Soup",
    "unit": "portion",
    "price": 248,
    "compare_price": 310,
    "cost_price": 94,
    "stock": 999,
    "sku": "RIN-8555",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/75f8b295-8e56-4381-b152-8ae12584b7cd.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2420,
      "category_slug": "soup",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Grilled Roll",
    "brand": "Roll Inn",
    "category": "Special Roll",
    "unit": "portion",
    "price": 360,
    "compare_price": 450,
    "cost_price": 137,
    "stock": 999,
    "sku": "RIN-8465",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/a668afb3-0e7f-4848-8615-2459a8f68574.jpg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2404,
      "category_slug": "special-roll",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Chicken Roasted Roll With Fries",
    "brand": "Roll Inn",
    "category": "Special Roll",
    "unit": "portion",
    "price": 360,
    "compare_price": 450,
    "cost_price": 137,
    "stock": 999,
    "sku": "RIN-8463",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/e5a5be1c-9db1-4a2c-9d0c-497404040d55.webp",
    "is_featured": true,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2404,
      "category_slug": "special-roll",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "MD Roll",
    "brand": "Roll Inn",
    "category": "Special Roll",
    "unit": "portion",
    "price": 360,
    "compare_price": 450,
    "cost_price": 137,
    "stock": 999,
    "sku": "RIN-8464",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/091ab9c4-3819-481a-9ea5-da4f9fe242ee.jpeg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2404,
      "category_slug": "special-roll",
      "is_deal": false,
      "product_tag": null
    }
  },
  {
    "name": "Pizza Roll With Fries",
    "brand": "Roll Inn",
    "category": "Special Roll",
    "unit": "portion",
    "price": 360,
    "compare_price": 450,
    "cost_price": 137,
    "stock": 999,
    "sku": "RIN-8462",
    "description": "null",
    "image_url": "https://services.eatx.pk/ProductImages/b1777319-5635-406e-a711-7800b4fcacd6.jpeg",
    "is_featured": false,
    "on_sale": true,
    "domain_data": {
      "source": "rollinnbbq.pk",
      "category_id": 2404,
      "category_slug": "special-roll",
      "is_deal": false,
      "product_tag": null
    }
  }
];
