/**
 * Tenvo Kitchen demo menu — generated from archive/restraint.html.
 * Images use curated Unsplash food photography (the original Supermeal CDN is offline).
 * Regenerate: node scripts/extract-restaurant-archive.mjs && node scripts/build-restaurant-seed-catalog.mjs
 */
export const RESTAURANT_SEED_PRODUCTS = [
  {
    "name": "Garden Fresh Salad Bowl",
    "brand": "Tenvo Kitchen",
    "category": "Appetizers",
    "unit": "portion",
    "price": 850,
    "cost_price": 280,
    "stock": 999,
    "sku": "RST-CUI-SALADS",
    "description": "House favourite salads dish, prepared fresh to order.",
    "image_url": "https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=800&q=80&auto=format&fit=crop",
    "is_featured": false
  },
  {
    "name": "Hot & Sour Soup",
    "brand": "Tenvo Kitchen",
    "category": "Appetizers",
    "unit": "portion",
    "price": 850,
    "cost_price": 280,
    "stock": 999,
    "sku": "RST-CUI-SOUP",
    "description": "House favourite soup dish, prepared fresh to order.",
    "image_url": "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80&auto=format&fit=crop",
    "is_featured": false
  },
  {
    "name": "Mixed Grill Platter",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "portion",
    "price": 850,
    "cost_price": 280,
    "stock": 999,
    "sku": "RST-CUI-BBQ",
    "description": "House favourite bbq dish, prepared fresh to order.",
    "image_url": "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=800&q=80&auto=format&fit=crop",
    "is_featured": true
  },
  {
    "name": "Chocolate Fudge Brownie",
    "brand": "Tenvo Kitchen",
    "category": "Desserts",
    "unit": "portion",
    "price": 450,
    "cost_price": 280,
    "stock": 999,
    "sku": "RST-CUI-DESSERTS",
    "description": "House favourite desserts dish, prepared fresh to order.",
    "image_url": "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&q=80&auto=format&fit=crop",
    "is_featured": false
  },
  {
    "name": "Fresh Mint Lemonade",
    "brand": "Tenvo Kitchen",
    "category": "Beverages",
    "unit": "pcs",
    "price": 350,
    "cost_price": 280,
    "stock": 999,
    "sku": "RST-CUI-DRINKS",
    "description": "House favourite drinks dish, prepared fresh to order.",
    "image_url": "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=800&q=80&auto=format&fit=crop",
    "is_featured": false
  },
  {
    "name": "Chicken Shawarma Plate",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "portion",
    "price": 850,
    "cost_price": 280,
    "stock": 999,
    "sku": "RST-CUI-ARABIC",
    "description": "House favourite arabic dish, prepared fresh to order.",
    "image_url": "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80&auto=format&fit=crop",
    "is_featured": false
  },
  {
    "name": "Chicken Karahi (Full)",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "portion",
    "price": 850,
    "cost_price": 280,
    "stock": 999,
    "sku": "RST-CUI-KARHAI",
    "description": "House favourite karhai dish, prepared fresh to order.",
    "image_url": "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80&auto=format&fit=crop",
    "is_featured": false
  },
  {
    "name": "Pad Thai Noodles",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "portion",
    "price": 850,
    "cost_price": 280,
    "stock": 999,
    "sku": "RST-CUI-THAI",
    "description": "House favourite thai dish, prepared fresh to order.",
    "image_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80&auto=format&fit=crop",
    "is_featured": false
  },
  {
    "name": "Chicken Biryani (Full)",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "portion",
    "price": 850,
    "cost_price": 280,
    "stock": 999,
    "sku": "RST-CUI-PAKISTAN",
    "description": "House favourite pakistani dish, prepared fresh to order.",
    "image_url": "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80&auto=format&fit=crop",
    "is_featured": true
  },
  {
    "name": "Butter Chicken with Naan",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "portion",
    "price": 850,
    "cost_price": 280,
    "stock": 999,
    "sku": "RST-CUI-INDIAN",
    "description": "House favourite indian dish, prepared fresh to order.",
    "image_url": "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=800&q=80&auto=format&fit=crop",
    "is_featured": false
  },
  {
    "name": "Crispy Spring Rolls (6 pcs)",
    "brand": "Tenvo Kitchen",
    "category": "Appetizers",
    "unit": "portion",
    "price": 550,
    "cost_price": 280,
    "stock": 999,
    "sku": "RST-CUI-APPETIZE",
    "description": "House favourite appetizers dish, prepared fresh to order.",
    "image_url": "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80&auto=format&fit=crop",
    "is_featured": false
  },
  {
    "name": "Wood-fired Margherita Pizza",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "portion",
    "price": 850,
    "cost_price": 280,
    "stock": 999,
    "sku": "RST-CUI-ITALIAN",
    "description": "House favourite italian dish, prepared fresh to order.",
    "image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop",
    "is_featured": true
  },
  {
    "name": "Grill O Grill Platter",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "portion",
    "price": 750,
    "compare_price": 840,
    "cost_price": 315,
    "stock": 999,
    "sku": "RST-GRILL-O",
    "description": "Signature item inspired by Grill O. Min order Rs 500. from Rs 50.",
    "image_url": "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80&auto=format&fit=crop",
    "is_featured": true,
    "on_sale": true
  },
  {
    "name": "Sultan Karahi Special",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "portion",
    "price": 950,
    "compare_price": 1064,
    "cost_price": 399,
    "stock": 999,
    "sku": "RST-SULTAN",
    "description": "Signature item inspired by Sultan. Min order Rs 500. Free Delivery.",
    "image_url": "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=800&q=80&auto=format&fit=crop",
    "is_featured": true,
    "on_sale": true
  },
  {
    "name": "Pizzay Bahadurabad Special Pizza",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "pcs",
    "price": 499,
    "cost_price": 210,
    "stock": 999,
    "sku": "RST-PIZZAY-BAHAD",
    "description": "Signature item inspired by Pizzay Bahadurabad. Min order Rs 600. from Rs 60.",
    "image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "Penny Pizza Special Pizza",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "pcs",
    "price": 550,
    "cost_price": 231,
    "stock": 999,
    "sku": "RST-PENNY-PIZZA",
    "description": "Signature item inspired by Penny Pizza. Min order Rs 1000. from Rs 100.",
    "image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "Pizza Inc Special Pizza",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "pcs",
    "price": 499,
    "cost_price": 210,
    "stock": 999,
    "sku": "RST-PIZZA-INC",
    "description": "Signature item inspired by Pizza Inc. Min order Rs 499. from Rs 150.",
    "image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "Bun Ka Baap Chef Special",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "portion",
    "price": 550,
    "cost_price": 231,
    "stock": 999,
    "sku": "RST-BUN-KA-BAAP",
    "description": "Signature item inspired by Bun Ka Baap. Min order Rs 350. from Rs 100.",
    "image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "Icy n Spicy Spicy Combo Box",
    "brand": "Tenvo Kitchen",
    "category": "Appetizers",
    "unit": "pcs",
    "price": 650,
    "cost_price": 273,
    "stock": 999,
    "sku": "RST-ICY-N-SPICY",
    "description": "Signature item inspired by Icy n Spicy. Min order Rs 800. from Rs 70.",
    "image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "Spice Minded Home Chef Chef Special",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "portion",
    "price": 550,
    "cost_price": 231,
    "stock": 999,
    "sku": "RST-SPICE-MINDED",
    "description": "Signature item inspired by Spice Minded Home Chef. Min order Rs 800. from Rs 100.",
    "image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "EATMEAT Grill Platter",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "portion",
    "price": 750,
    "cost_price": 315,
    "stock": 999,
    "sku": "RST-EATMEAT",
    "description": "Signature item inspired by EATMEAT. Min order Rs 800. from Rs 80.",
    "image_url": "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "Zhi Zhi Fan Chao Wok Special",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "portion",
    "price": 750,
    "cost_price": 315,
    "stock": 999,
    "sku": "RST-ZHI-ZHI-FAN-",
    "description": "Signature item inspired by Zhi Zhi Fan Chao. Min order Rs 350. from Rs 70.",
    "image_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "Pizza Lounge Special Pizza",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "pcs",
    "price": 499,
    "cost_price": 210,
    "stock": 999,
    "sku": "RST-PIZZA-LOUNGE",
    "description": "Signature item inspired by Pizza Lounge. Min order Rs 300. from Rs 100.",
    "image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "The Olive Burger Signature Burger",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "pcs",
    "price": 450,
    "cost_price": 189,
    "stock": 999,
    "sku": "RST-THE-OLIVE-BU",
    "description": "Signature item inspired by The Olive Burger. Min order Rs 500. Free Delivery.",
    "image_url": "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "Pizza Zone King Special Pizza",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "pcs",
    "price": 499,
    "cost_price": 210,
    "stock": 999,
    "sku": "RST-PIZZA-ZONE-K",
    "description": "Signature item inspired by Pizza Zone King. Min order Rs 300. from Rs 100.",
    "image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "Pizza 99 Special Pizza",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "pcs",
    "price": 499,
    "cost_price": 210,
    "stock": 999,
    "sku": "RST-PIZZA-99",
    "description": "Signature item inspired by Pizza 99. Min order Rs 500. from Rs 50.",
    "image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "Pizza Crispy Special Pizza",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "pcs",
    "price": 499,
    "cost_price": 210,
    "stock": 999,
    "sku": "RST-PIZZA-CRISPY",
    "description": "Signature item inspired by Pizza Crispy. Min order Rs 800. from Rs 150.",
    "image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "Pizza Home Special Pizza",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "pcs",
    "price": 499,
    "cost_price": 210,
    "stock": 999,
    "sku": "RST-PIZZA-HOME",
    "description": "Signature item inspired by Pizza Home. Min order Rs 300. from Rs 150.",
    "image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "Subway DHA Club Sandwich",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "pcs",
    "price": 550,
    "cost_price": 231,
    "stock": 999,
    "sku": "RST-SUBWAY-DHA",
    "description": "Signature item inspired by Subway DHA. Min order Rs 300. from Rs 100.",
    "image_url": "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "Pizza IZ Special Pizza",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "pcs",
    "price": 825,
    "cost_price": 347,
    "stock": 999,
    "sku": "RST-PIZZA-IZ",
    "description": "Signature item inspired by Pizza IZ. Min order Rs 1500. from Rs 150.",
    "image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "Golden Apple Bahadurabad Family Feast Box",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "portion",
    "price": 1200,
    "cost_price": 504,
    "stock": 999,
    "sku": "RST-GOLDEN-APPLE",
    "description": "Signature item inspired by Golden Apple Bahadurabad. Min order Rs 300. from Rs 100.",
    "image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "Cross Roadz Pizza Special Pizza",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "pcs",
    "price": 499,
    "cost_price": 210,
    "stock": 999,
    "sku": "RST-CROSS-ROADZ-",
    "description": "Signature item inspired by Cross Roadz Pizza. Min order Rs 500. from Rs 50.",
    "image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "Pizza Hot Special Pizza",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "pcs",
    "price": 499,
    "cost_price": 210,
    "stock": 999,
    "sku": "RST-PIZZA-HOT",
    "description": "Signature item inspired by Pizza Hot. Min order Rs 500. from Rs 50.",
    "image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "Burger Hut Signature Burger",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "pcs",
    "price": 450,
    "cost_price": 189,
    "stock": 999,
    "sku": "RST-BURGER-HUT",
    "description": "Signature item inspired by Burger Hut. Min order Rs 800. from Rs 80.",
    "image_url": "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "Chicken Cottage Roast Chicken Meal",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "portion",
    "price": 850,
    "cost_price": 357,
    "stock": 999,
    "sku": "RST-CHICKEN-COTT",
    "description": "Signature item inspired by Chicken Cottage. Min order Rs 800. from Rs 80.",
    "image_url": "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "HeisenBurgers Signature Burger",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "pcs",
    "price": 450,
    "cost_price": 189,
    "stock": 999,
    "sku": "RST-HEISENBURGER",
    "description": "Signature item inspired by HeisenBurgers. Min order Rs 800. from Rs 80.",
    "image_url": "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "De Pizza Town Special Pizza",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "pcs",
    "price": 499,
    "cost_price": 210,
    "stock": 999,
    "sku": "RST-DE-PIZZA-TOW",
    "description": "Signature item inspired by De Pizza Town. Min order Rs 600. from Rs 150.",
    "image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "Hot Snacks Roll n BBQ Grill Platter",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "portion",
    "price": 750,
    "cost_price": 315,
    "stock": 999,
    "sku": "RST-HOT-SNACKS-R",
    "description": "Signature item inspired by Hot Snacks Roll n BBQ. Min order Rs 800. from Rs 80.",
    "image_url": "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "Pizza Gateway Special Pizza",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "pcs",
    "price": 499,
    "cost_price": 210,
    "stock": 999,
    "sku": "RST-PIZZA-GATEWA",
    "description": "Signature item inspired by Pizza Gateway. Min order Rs 500. from Rs 70.",
    "image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "Pizza Own Special Pizza",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "pcs",
    "price": 499,
    "cost_price": 210,
    "stock": 999,
    "sku": "RST-PIZZA-OWN",
    "description": "Signature item inspired by Pizza Own. Min order Rs 500. from Rs 100.",
    "image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "Red Apple PECHS Family Feast Box",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "portion",
    "price": 1200,
    "cost_price": 504,
    "stock": 999,
    "sku": "RST-RED-APPLE-PE",
    "description": "Signature item inspired by Red Apple PECHS. Min order Rs 400. from Rs 50.",
    "image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop",
    "is_featured": false,
    "on_sale": false
  },
  {
    "name": "Family Pizza & Drinks Combo",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "pcs",
    "price": 1499,
    "compare_price": 1799,
    "cost_price": 620,
    "stock": 999,
    "sku": "RST-CMB-PIZZA",
    "description": "Large pizza, garlic bread, and 1.5L drink. Perfect for sharing.",
    "image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop",
    "is_featured": true,
    "on_sale": true
  },
  {
    "name": "BBQ Feast for Two",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "portion",
    "price": 1899,
    "compare_price": 2199,
    "cost_price": 780,
    "stock": 999,
    "sku": "RST-CMB-BBQ",
    "description": "Mixed grill, naan, raita, and salad for two.",
    "image_url": "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80&auto=format&fit=crop",
    "is_featured": true,
    "on_sale": true
  },
  {
    "name": "Midnight Burger Box",
    "brand": "Tenvo Kitchen",
    "category": "Main Course",
    "unit": "pcs",
    "price": 999,
    "compare_price": 1150,
    "cost_price": 410,
    "stock": 999,
    "sku": "RST-CMB-BRG",
    "description": "Two burgers, fries, and soft drinks. Late-night favourite.",
    "image_url": "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80&auto=format&fit=crop",
    "on_sale": true
  }
];
