/**
 * Tenvo Vehicles starter catalog for vehicle-dealership demos and registration seeds.
 * Vehicles, accessories, PPF, conversions, and bikes with regional pricing.
 */
import { productImageForSku } from '../storefront/tenvoVehiclesAssets.js';

const img = (sku) => productImageForSku(sku);

const vehicle = (fields) => ({
  unit: 'unit',
  stock: fields.stock ?? 1,
  is_featured: fields.is_featured ?? false,
  ...fields,
});

const accessory = (fields) => ({
  unit: 'pcs',
  stock: fields.stock ?? 25,
  is_featured: fields.is_featured ?? false,
  ...fields,
});

/** @type {Array<Record<string, unknown>>} */
export const SEHGAL_SHOWROOM_PRODUCTS = [
  // ── Recently added vehicles (from sehgalmotorsports.pk) ─────────────────────
  vehicle({
    name: 'Toyota Hilux Revo V 2.8D 2021',
    brand: 'Toyota',
    category: 'All Cars',
    price: 12600000,
    marketPrices: { PK: 12600000 },
    sku: 'TYT-HILUX-REVO-2021',
    description: 'Toyota Hilux Revo V 2.8D diesel, automatic, Islamabad registered. 92,000 km.',
    image_url: img('TYT-HILUX-REVO-2021'),
    is_featured: true,
    domain_data: {
      vehiclemake: 'Toyota',
      vehiclemodel: 'Hilux Revo V',
      modelyear: '2021',
      mileage: '92000',
      fueltype: 'Diesel',
      transmission: 'Automatic',
      bodytype: 'Double Cabin',
      condition: 'used',
      registrationcity: 'Islamabad',
      enginesize: '2800 CC',
    },
  }),
  vehicle({
    name: 'Suzuki Swift GLX 1.2 2025',
    brand: 'Suzuki',
    category: 'New Cars',
    price: 4200000,
    marketPrices: { PK: 4200000 },
    sku: 'SUZ-SWIFT-GLX-2025',
    description: 'Brand new Suzuki Swift GLX 1.2 petrol, automatic, Islamabad. 14,000 km.',
    image_url: img('SUZ-SWIFT-GLX-2025'),
    is_featured: true,
    domain_data: {
      vehiclemake: 'Suzuki',
      vehiclemodel: 'Swift GLX',
      modelyear: '2025',
      mileage: '14000',
      fueltype: 'Petrol',
      transmission: 'Automatic',
      bodytype: 'Hatchback',
      condition: 'new',
      registrationcity: 'Islamabad',
      enginesize: '1200 CC',
    },
  }),
  vehicle({
    name: 'Toyota Corolla Altis 1.6 Automatic 2020',
    brand: 'Toyota',
    category: 'All Cars',
    price: 5700000,
    marketPrices: { PK: 5700000 },
    sku: 'TYT-ALTIS-2020',
    description: 'Toyota Corolla Altis 1.6 automatic, Punjab registered, 68,999 km.',
    image_url: img('TYT-ALTIS-2020'),
    is_featured: true,
    domain_data: {
      vehiclemake: 'Toyota',
      vehiclemodel: 'Corolla Altis',
      modelyear: '2020',
      mileage: '68999',
      fueltype: 'Petrol',
      transmission: 'Automatic',
      bodytype: 'Sedan',
      condition: 'used',
      registrationcity: 'Punjab',
      enginesize: '1600 CC',
    },
  }),
  vehicle({
    name: 'Peugeot 2008 Allure 2023',
    brand: 'Peugeot',
    category: 'Imported',
    price: 5700000,
    marketPrices: { PK: 5700000 },
    sku: 'PEU-2008-2023',
    description: 'Imported Peugeot 2008 Allure petrol SUV, Islamabad, 40,000 km.',
    image_url: img('PEU-2008-2023'),
    is_featured: true,
    domain_data: {
      vehiclemake: 'Peugeot',
      vehiclemodel: '2008 Allure',
      modelyear: '2023',
      mileage: '40000',
      fueltype: 'Petrol',
      transmission: 'Automatic',
      bodytype: 'SUV',
      condition: 'used',
      registrationcity: 'Islamabad',
      enginesize: '1200 CC',
    },
  }),
  vehicle({
    name: 'Toyota Fortuner Legender 2.8 2022',
    brand: 'Toyota',
    category: 'Luxury',
    price: 18500000,
    marketPrices: { PK: 18500000 },
    sku: 'TYT-FORT-LEG-2022',
    description: 'Toyota Fortuner Legender 2.8 diesel, top variant, low mileage.',
    image_url: img('TYT-FORT-LEG-2022'),
    domain_data: {
      vehiclemake: 'Toyota',
      vehiclemodel: 'Fortuner Legender',
      modelyear: '2022',
      mileage: '35000',
      fueltype: 'Diesel',
      transmission: 'Automatic',
      bodytype: 'Luxury SUV',
      condition: 'used',
      registrationcity: 'Islamabad',
      enginesize: '2800 CC',
    },
  }),
  vehicle({
    name: 'Honda City Aspire 1.5 CVT 2024',
    brand: 'Honda',
    category: 'New Cars',
    price: 4850000,
    marketPrices: { PK: 4850000 },
    sku: 'HND-CITY-2024',
    description: 'Honda City Aspire 1.5 CVT, factory fresh with warranty.',
    image_url: img('HND-CITY-2024'),
    domain_data: {
      vehiclemake: 'Honda',
      vehiclemodel: 'City Aspire',
      modelyear: '2024',
      mileage: '5000',
      fueltype: 'Petrol',
      transmission: 'Automatic',
      bodytype: 'Sedan',
      condition: 'new',
      registrationcity: 'Islamabad',
      enginesize: '1500 CC',
    },
  }),
  vehicle({
    name: 'Kia Sportage Alpha 2023',
    brand: 'Kia',
    category: 'All Cars',
    price: 7200000,
    marketPrices: { PK: 7200000 },
    sku: 'KIA-SPORT-2023',
    description: 'Kia Sportage Alpha AWD, panoramic roof, Islamabad registered.',
    image_url: img('KIA-SPORT-2023'),
    domain_data: {
      vehiclemake: 'Kia',
      vehiclemodel: 'Sportage Alpha',
      modelyear: '2023',
      mileage: '28000',
      fueltype: 'Petrol',
      transmission: 'Automatic',
      bodytype: 'SUV',
      condition: 'used',
      registrationcity: 'Islamabad',
      enginesize: '2000 CC',
    },
  }),
  vehicle({
    name: 'Haval H6 HEV 2024',
    brand: 'Haval',
    category: 'New Cars',
    price: 8900000,
    marketPrices: { PK: 8900000 },
    sku: 'HVL-H6-HEV-2024',
    description: 'Haval H6 hybrid electric SUV, latest model with ADAS.',
    image_url: img('HVL-H6-HEV-2024'),
    domain_data: {
      vehiclemake: 'Haval',
      vehiclemodel: 'H6 HEV',
      modelyear: '2024',
      mileage: '8000',
      fueltype: 'Hybrid',
      transmission: 'Automatic',
      bodytype: 'SUV',
      condition: 'new',
      registrationcity: 'Rawalpindi',
      enginesize: '1500 CC',
    },
  }),
  vehicle({
    name: 'BMW 520i M Sport 2019',
    brand: 'BMW',
    category: 'Luxury',
    price: 14200000,
    marketPrices: { PK: 14200000 },
    sku: 'BMW-520I-2019',
    description: 'BMW 520i M Sport, executive sedan, full service history.',
    image_url: img('BMW-520I-2019'),
    domain_data: {
      vehiclemake: 'BMW',
      vehiclemodel: '520i M Sport',
      modelyear: '2019',
      mileage: '55000',
      fueltype: 'Petrol',
      transmission: 'Automatic',
      bodytype: 'Luxury Sedan',
      condition: 'used',
      registrationcity: 'Islamabad',
      enginesize: '2000 CC',
    },
  }),
  vehicle({
    name: 'Tesla Model 3 Long Range 2022',
    brand: 'Tesla',
    category: 'Imported',
    price: 16800000,
    marketPrices: { PK: 16800000 },
    sku: 'TSL-M3-2022',
    description: 'Imported Tesla Model 3 Long Range, Islamabad registered.',
    image_url: img('TSL-M3-2022'),
    domain_data: {
      vehiclemake: 'Tesla',
      vehiclemodel: 'Model 3',
      modelyear: '2022',
      mileage: '22000',
      fueltype: 'Electric',
      transmission: 'Automatic',
      bodytype: 'Sedan',
      condition: 'used',
      registrationcity: 'Islamabad',
      enginesize: 'Electric',
    },
  }),
  // ── Bikes ─────────────────────────────────────────────────────────────────
  vehicle({
    name: 'Yamaha YBR 125G Cruiser',
    brand: 'Yamaha',
    category: 'Bikes',
    price: 245000,
    marketPrices: { PK: 245000 },
    sku: 'YBR-125G',
    description: 'Yamaha YBR 125G cruiser, petrol, showroom condition.',
    image_url: img('YBR-125G'),
    domain_data: {
      vehiclemake: 'Yamaha',
      vehiclemodel: 'YBR 125G',
      modelyear: '2024',
      mileage: '1200',
      fueltype: 'Petrol',
      transmission: 'Manual',
      bodytype: 'Cruiser',
      condition: 'new',
      registrationcity: 'Rawalpindi',
    },
  }),
  vehicle({
    name: 'United US 125 Scooter',
    brand: 'United',
    category: 'Bikes',
    price: 185000,
    marketPrices: { PK: 185000 },
    sku: 'US-125-SCOOT',
    description: 'United US 125 electric-start scooter for city commuting.',
    image_url: img('US-125-SCOOT'),
    domain_data: {
      vehiclemake: 'United',
      vehiclemodel: 'US 125',
      modelyear: '2024',
      mileage: '800',
      fueltype: 'Petrol',
      transmission: 'Automatic',
      bodytype: 'Scooter',
      condition: 'new',
      registrationcity: 'Islamabad',
    },
  }),
  // ── Best sellers / auto store (from homepage) ─────────────────────────────
  accessory({
    name: 'Car Bhouse X Car Air Freshener Gel (Multiple Scents)',
    brand: 'Car Bhouse',
    category: 'Auto Store',
    price: 1200,
    marketPrices: { PK: 1200 },
    sku: 'CBH-AIR-GEL',
    description: 'Long-lasting dashboard gel freshener, multiple scents available.',
    image_url: img('CBH-AIR-GEL'),
    is_featured: true,
  }),
  accessory({
    name: 'MrHorn Sports Snail Horn YW-A056 410/510 Hz 12v',
    brand: 'MrHorn Sports',
    category: 'Auto Store',
    price: 4500,
    marketPrices: { PK: 4500 },
    sku: 'MRH-YW-A056',
    description: 'Dual-tone snail horn, 12V, loud and clear tone for highway safety.',
    image_url: img('MRH-YW-A056'),
    is_featured: true,
  }),
  accessory({
    name: 'X-7Seven Universal 3 Lens Dual Color Bonnet Spotlight',
    brand: 'X-7Seven',
    category: 'LED & Lightening',
    price: 15300,
    marketPrices: { PK: 15300 },
    sku: 'X7-BONNET-3L',
    description: 'Universal bonnet spotlight with mounts, dual color LED pods.',
    image_url: img('X7-BONNET-3L'),
    is_featured: true,
  }),
  accessory({
    name: 'MrHorn Sports Snail Horn MR-80-002 400/500 Hz 12v',
    brand: 'MrHorn Sports',
    category: 'Auto Store',
    price: 5500,
    compare_price: 5500,
    marketPrices: { PK: 5500 },
    sku: 'MRH-MR-80-002',
    description: 'Premium snail horn pair, 400/500 Hz dual tone.',
    image_url: img('MRH-MR-80-002'),
    is_featured: true,
  }),
  accessory({
    name: 'Portable Multi Color Car Ashtray With LED',
    brand: 'Sehgal Sports',
    category: 'Interior',
    price: 1200,
    marketPrices: { PK: 1200 },
    sku: 'SMS-ASH-LED',
    description: 'Compact LED ashtray with custom car logo option.',
    image_url: img('SMS-ASH-LED'),
    is_featured: true,
  }),
  accessory({
    name: 'Toyota Corolla Head Light Nike Style 2011-2014',
    brand: 'X-7Seven',
    category: 'LED & Lightening',
    price: 70000,
    compare_price: 79000,
    marketPrices: { PK: 70000 },
    sku: 'X7-COROLLA-HL',
    description: 'Nike-style projector headlamps for Toyota Corolla 2011-2014.',
    image_url: img('X7-COROLLA-HL'),
    is_featured: true,
  }),
  accessory({
    name: 'Pioneer Bass Tube TS-WX306T',
    brand: 'Pioneer',
    category: 'Music & Stereo',
    price: 43500,
    compare_price: 73000,
    marketPrices: { PK: 43500 },
    sku: 'PIO-WX306T',
    description: 'Active bass tube subwoofer, easy install, deep bass response.',
    image_url: img('PIO-WX306T'),
    is_featured: true,
  }),
  accessory({
    name: 'Pioneer Universal Back Camera',
    brand: 'Pioneer',
    category: 'Gadgets',
    price: 6500,
    compare_price: 10000,
    marketPrices: { PK: 6500 },
    sku: 'PIO-CAM-UNI',
    description: 'Universal rear view camera with night vision.',
    image_url: img('PIO-CAM-UNI'),
    is_featured: true,
  }),
  accessory({
    name: 'Honda City Back Light Smoke Version 4 Model 2021-2022',
    brand: 'X-7Seven',
    category: 'LED & Lightening',
    price: 42000,
    compare_price: 49000,
    marketPrices: { PK: 42000 },
    sku: 'X7-CITY-BL',
    description: 'Smoke LED tail lights for Honda City 2021-2022.',
    image_url: img('X7-CITY-BL'),
    is_featured: true,
  }),
  accessory({
    name: 'X-7Seven Universal Off-road LED Pod Light 3 inch 40w',
    brand: 'X-7Seven',
    category: 'LED & Lightening',
    price: 8200,
    marketPrices: { PK: 8200 },
    sku: 'X7-POD-40W',
    description: '3-inch 40W off-road flood/pod light, 12V.',
    image_url: img('X7-POD-40W'),
    is_featured: true,
  }),
  accessory({
    name: 'KLCB Car Shampoo Wash & Wax 1L',
    brand: 'KLCB',
    category: 'Car Care',
    price: 2800,
    marketPrices: { PK: 2800 },
    sku: 'KLCB-SHAMPOO-1L',
    description: 'Premium pH-neutral car shampoo with wax protection.',
    image_url: img('KLCB-SHAMPOO-1L'),
    is_featured: true,
  }),
  accessory({
    name: 'Micro Fiber Cloth Pack of 5',
    brand: 'Sehgal Sports',
    category: 'Car Care',
    price: 1500,
    marketPrices: { PK: 1500 },
    sku: 'SMS-MF-5PK',
    description: 'High GSM microfiber cloths for detailing and drying.',
    image_url: img('SMS-MF-5PK'),
  }),
  accessory({
    name: 'Android Multimedia LCD Panel 10 inch Universal',
    brand: 'Sehgal Sports',
    category: 'Music & Stereo',
    price: 28500,
    marketPrices: { PK: 28500 },
    sku: 'SMS-AND-10',
    description: 'Android 10-inch panel with CarPlay, reverse camera input.',
    image_url: img('SMS-AND-10'),
  }),
  accessory({
    name: '10D Floor Mats Custom Fit',
    brand: 'Sehgal Sports',
    category: 'Car Mats',
    price: 12500,
    marketPrices: { PK: 12500 },
    sku: 'SMS-10D-MATS',
    description: 'Custom 10D floor mats with heel pad and full coverage.',
    image_url: img('SMS-ASH-LED'),
  }),
  accessory({
    name: 'Car DVR Camera Dual Lens 4K',
    brand: 'Sehgal Sports',
    category: 'Gadgets',
    price: 9800,
    marketPrices: { PK: 9800 },
    sku: 'SMS-DVR-4K',
    description: 'Front and rear dash cam with parking mode and GPS.',
    image_url: img('SMS-DVR-4K'),
  }),
  // ── PPF ───────────────────────────────────────────────────────────────────
  accessory({
    name: 'PPF TPU Bourgogne Red CL-49',
    brand: 'Motorsports PPF',
    category: 'PPF',
    price: 185000,
    marketPrices: { PK: 185000 },
    sku: 'PPF-CL-49',
    description: 'Color PPF TPU film, Bourgogne Red, professional grade.',
    image_url: img('PPF-CL-49'),
    is_featured: true,
  }),
  accessory({
    name: 'PPF TPU Nardo Grey JGY-100',
    brand: 'Motorsports PPF',
    category: 'PPF',
    price: 195000,
    marketPrices: { PK: 195000 },
    sku: 'PPF-JGY-100',
    description: 'Color PPF TPU Nardo Grey, full body wrap ready.',
    image_url: img('PPF-JGY-100'),
  }),
  accessory({
    name: 'PPF Transparent Ultimate',
    brand: 'Motorsports PPF',
    category: 'PPF',
    price: 225000,
    marketPrices: { PK: 225000 },
    sku: 'PPF-ULT-CLR',
    description: 'Self-healing transparent PPF, ultimate protection grade.',
    image_url: img('PPF-ULT-CLR'),
  }),
  // ── Conversions ───────────────────────────────────────────────────────────
  accessory({
    name: 'Toyota Hilux Revo Conversion into Rocco GR 2023 Style',
    brand: 'Sehgal Motorsports',
    category: 'Conversions',
    price: 850000,
    marketPrices: { PK: 850000 },
    sku: 'CONV-REVO-ROCCO',
    description: 'Full Hilux Revo conversion to Rocco GR 2023 style body kit.',
    image_url: img('CONV-REVO-ROCCO'),
    is_featured: true,
  }),
  accessory({
    name: 'Toyota Prado FJ150 Conversion GX-460 Style 2018-2022',
    brand: 'Sehgal Motorsports',
    category: 'Conversions',
    price: 1250000,
    marketPrices: { PK: 1250000 },
    sku: 'CONV-PRADO-GX',
    description: 'Prado FJ150 half conversion to Lexus GX-460 style.',
    image_url: img('CONV-PRADO-GX'),
  }),
  accessory({
    name: 'Toyota Fortuner Conversion into Legender 2022 Style',
    brand: 'Sehgal Motorsports',
    category: 'Conversions',
    price: 650000,
    marketPrices: { PK: 650000 },
    sku: 'CONV-FORT-LEG',
    description: 'Fortuner facelift conversion to Legender 2022 styling.',
    image_url: img('CONV-FORT-LEG'),
  }),
  accessory({
    name: 'Mercedes W222 into Maybach Conversion',
    brand: 'Sehgal Motorsports',
    category: 'Conversions',
    price: 2200000,
    marketPrices: { PK: 2200000 },
    sku: 'CONV-W222-MAY',
    description: 'Mercedes W222 complete Maybach-style conversion package.',
    image_url: img('CONV-W222-MAY'),
  }),
  // ── Window films ──────────────────────────────────────────────────────────
  accessory({
    name: 'Motorsports Window Film Ceramic',
    brand: 'Motorsports',
    category: 'Window Films',
    price: 18500,
    marketPrices: { PK: 18500 },
    sku: 'WF-CERAMIC',
    description: 'Ceramic heat rejection window film, full car package.',
    image_url: img('WF-CERAMIC'),
  }),
  accessory({
    name: 'Motorsports Chameleon Window Film',
    brand: 'Motorsports',
    category: 'Window Films',
    price: 24000,
    marketPrices: { PK: 24000 },
    sku: 'WF-CHAMELEON',
    description: 'Color-shifting chameleon tint for premium look.',
    image_url: img('WF-CHAMELEON'),
  }),
  accessory({
    name: '3M Automotive Window Film Crystalline',
    brand: '3M',
    category: 'Window Films',
    price: 32000,
    marketPrices: { PK: 32000 },
    sku: '3M-CRYST',
    description: 'Genuine 3M Crystalline series, superior heat rejection.',
    image_url: img('3M-CRYST'),
  }),
  // ── Modifications sample ────────────────────────────────────────────────────
  accessory({
    name: 'Toyota Fortuner Sigma Style Body Kit',
    brand: 'Sehgal Sports',
    category: 'Modifications',
    price: 145000,
    marketPrices: { PK: 145000 },
    sku: 'MOD-FORT-SIGMA',
    description: 'Complete Sigma style body kit for Toyota Fortuner.',
    image_url: img('MOD-FORT-SIGMA'),
  }),
  accessory({
    name: 'Universal Chrome Door Handle Covers Set of 4',
    brand: 'Sehgal Sports',
    category: 'Exterior',
    price: 3200,
    marketPrices: { PK: 3200 },
    sku: 'EXT-DHC-4',
    description: 'Chrome door handle covers, universal fit.',
    image_url: img('EXT-DHC-4'),
  }),
];

/** Storefront + hub category order for Sehgal-style dealership demos. */
export const SEHGAL_SHOWROOM_CATEGORIES = [
  'All Cars',
  'New Cars',
  'Pre-Owned',
  'Used Cars',
  'Luxury',
  'Imported',
  'Bikes',
  'Auto Store',
  'Car Care',
  'LED & Lightening',
  'Modifications',
  'Interior',
  'Exterior',
  'Gadgets',
  'Music & Stereo',
  'Car Mats',
  'PPF',
  'Conversions',
  'Window Films',
];
