/**
 * Supermarket demo catalog — product names & imagery from archive/supper-store.html
 * (DSM Clifton) with Naheed-style grocery mix. Used for demo-supermarket seed + storefront fallback.
 */
import { stockImage } from './richProductCatalog.js';

const DSM_PROD =
  'https://www.dsmonline.pk/media/catalog/product/cache/b5728db6998991bed0f3916e81c5dbd3';

/** @type {Array<Record<string, unknown>>} */
export const SUPERMARKET_SEED_PRODUCTS = [
  {
    name: 'Coca-Cola 330ml Can',
    brand: 'Coca-Cola',
    category: 'Beverages',
    unit: 'can',
    price: 120,
    compare_price: 150,
    cost_price: 95,
    stock: 320,
    sku: 'SM-COLA-330',
    image_url: `${DSM_PROD}/c/o/coca-cola-330ml-can-imp2.png`,
    is_featured: true,
  },
  {
    name: 'Closeup Toothpaste 85g Red Hot',
    brand: 'Closeup',
    category: 'Personal Care',
    unit: 'pack',
    price: 265,
    compare_price: 298,
    cost_price: 210,
    stock: 140,
    sku: 'SM-CLP-85',
    image_url: `${DSM_PROD}/a/v/avredcws.png`,
    is_featured: true,
  },
  {
    name: 'Diamond Easy Cook Haleem Mix 300g',
    brand: 'Diamond',
    category: 'Food Staples',
    unit: 'pack',
    price: 185,
    cost_price: 142,
    stock: 95,
    sku: 'SM-DMH-300',
    image_url: `${DSM_PROD}/d/i/diamond_haleem_mix_300g.png`,
  },
  {
    name: "Pond's Super Light Gel 25g",
    brand: "Pond's",
    category: 'Personal Care',
    unit: 'pack',
    price: 450,
    cost_price: 360,
    stock: 80,
    sku: 'SM-PND-25',
    image_url: `${DSM_PROD}/z/e/zero_opal_z_buds_beige_15_v_awd_awdc.png`,
  },
  {
    name: 'Mango Dasheri 1kg',
    brand: 'Fresh',
    category: 'Fresh Produce',
    unit: 'kg',
    price: 380,
    cost_price: 290,
    stock: 60,
    sku: 'SM-MNG-DSH',
    image_url: `${DSM_PROD}/d/a/dasheri_image_1.png`,
    is_featured: true,
    domain_data: { is_weight_item: true },
  },
  {
    name: 'Diamond Sheer Khurma 200g',
    brand: 'Diamond',
    category: 'Food Staples',
    unit: 'pack',
    price: 220,
    cost_price: 175,
    stock: 110,
    sku: 'SM-DSK-200',
    image_url: `${DSM_PROD}/d/a/date-filled-bar-shopee-lazada-6-640w_-_2025-08-27t174811.539.png`,
  },
  {
    name: 'Nutrilov Protein Choco Almond 70g',
    brand: 'Nutrilov',
    category: 'Snacks',
    unit: 'pack',
    price: 350,
    compare_price: 399,
    cost_price: 280,
    stock: 75,
    sku: 'SM-NUT-70',
    image_url: `${DSM_PROD}/n/u/nutrilov_protein_choco_almond_70g.png`,
    is_featured: true,
  },
  {
    name: 'Haldee Fresh Turmeric 50g',
    brand: 'Haldee',
    category: 'Fresh Produce',
    unit: 'pack',
    price: 45,
    cost_price: 32,
    stock: 200,
    sku: 'SM-HAL-50',
    image_url: `${DSM_PROD}/5/0/50mg_41_.png`,
  },
  {
    name: 'Zero Headphone Storm Z Midnight Blue',
    brand: 'Zero',
    category: 'Electronics',
    unit: 'pcs',
    price: 4990,
    compare_price: 5490,
    cost_price: 4100,
    stock: 24,
    sku: 'SM-ZRO-HP',
    image_url: `${DSM_PROD}/j/n/jnb_g.png`,
    is_featured: true,
  },
  {
    name: 'Intex Tropical Buddies Swim Vest',
    brand: 'Intex',
    category: 'Kids & Babies',
    unit: 'pcs',
    price: 2890,
    cost_price: 2200,
    stock: 18,
    sku: 'SM-INT-VEST',
    image_url: `${DSM_PROD}/v/e/vest_q2ethdrgb.png`,
  },
  {
    name: 'Musical Target Boxing Set',
    brand: 'Sports',
    category: 'Toys',
    unit: 'set',
    price: 1990,
    cost_price: 1500,
    stock: 22,
    sku: 'SM-BOX-SET',
    image_url: `${DSM_PROD}/a/w/awxaw.png`,
  },
  {
    name: 'Captain America Spiral Notebook',
    brand: 'Stationery',
    category: 'Stationery',
    unit: 'pcs',
    price: 350,
    cost_price: 260,
    stock: 90,
    sku: 'SM-NB-CAP',
    image_url: `${DSM_PROD}/n/o/note-book-captian-america1.png`,
  },
  {
    name: 'Nestlé EveryDay Milk Powder 400g',
    brand: 'Nestlé',
    category: 'Dairy',
    unit: 'pack',
    price: 650,
    compare_price: 720,
    cost_price: 540,
    stock: 90,
    sku: 'SM-NLD-400',
    image_url: stockImage('1550583724-b2692b85b150'),
    is_featured: true,
  },
  {
    name: 'Lays Classic Salted Large',
    brand: "Lay's",
    category: 'Snacks',
    unit: 'pack',
    price: 100,
    cost_price: 72,
    stock: 180,
    sku: 'SM-LAY-001',
    image_url: stockImage('1566478989037-e624b0e253bf'),
  },
  {
    name: 'Dalda Cooking Oil 5L',
    brand: 'Dalda',
    category: 'Cooking Oil',
    unit: 'pcs',
    price: 2850,
    compare_price: 3100,
    cost_price: 2480,
    stock: 40,
    sku: 'SM-DLD-5L',
    image_url: stockImage('1474979266342-cc1e39dca2fe'),
  },
  {
    name: 'Tapal Danedar Tea 950g',
    brand: 'Tapal',
    category: 'Beverages',
    unit: 'pack',
    price: 1250,
    cost_price: 1080,
    stock: 70,
    sku: 'SM-TPL-950',
    image_url: stockImage('1556679343-5493566d3e7b'),
  },
  {
    name: 'Surf Excel 1kg',
    brand: 'Surf Excel',
    category: 'Household',
    unit: 'pack',
    price: 520,
    compare_price: 580,
    cost_price: 420,
    stock: 120,
    sku: 'SM-SRF-1K',
    image_url: stockImage('1585421516923-31b3831aadf0'),
  },
  {
    name: 'Olpers Full Cream Milk 1L',
    brand: 'Olpers',
    category: 'Dairy',
    unit: 'pack',
    price: 280,
    cost_price: 230,
    stock: 150,
    sku: 'SM-OLP-1L',
    image_url: stockImage('1628088062854-d1870b4553da'),
    is_featured: true,
  },
  {
    name: 'Shan Biryani Masala 65g',
    brand: 'Shan',
    category: 'Food Staples',
    unit: 'pack',
    price: 95,
    cost_price: 72,
    stock: 200,
    sku: 'SM-SHN-BIR',
    image_url: stockImage('1596040033229-a9821ebd058d'),
  },
  {
    name: 'Sunsilk Black Shine Shampoo 200ml',
    brand: 'Sunsilk',
    category: 'Personal Care',
    unit: 'bottle',
    price: 420,
    compare_price: 480,
    cost_price: 340,
    stock: 85,
    sku: 'SM-SUN-200',
    image_url: stockImage('1556228720-195a672e8a03'),
  },
  {
    name: 'Dettol Original Soap 130g',
    brand: 'Dettol',
    category: 'Personal Care',
    unit: 'pack',
    price: 165,
    cost_price: 125,
    stock: 160,
    sku: 'SM-DET-130',
    image_url: stockImage('1587854694152-42e3e8f5b672'),
  },
  {
    name: 'Garnier Micellar Water 125ml',
    brand: 'Garnier',
    category: 'Personal Care',
    unit: 'bottle',
    price: 890,
    compare_price: 990,
    cost_price: 720,
    stock: 55,
    sku: 'SM-GAR-125',
    image_url: stockImage('1570172619644-dfd955f5b7a3'),
  },
  {
    name: 'Basmati Rice Super Kernel 5kg',
    brand: 'Diamond',
    category: 'Food Staples',
    unit: 'bag',
    price: 1890,
    cost_price: 1580,
    stock: 65,
    sku: 'SM-RIC-5K',
    image_url: stockImage('1586201375761-83865001e31c'),
  },
  {
    name: 'Nestlé Pure Life Water 1.5L',
    brand: 'Nestlé',
    category: 'Beverages',
    unit: 'bottle',
    price: 90,
    cost_price: 68,
    stock: 400,
    sku: 'SM-WTR-15',
    image_url: stockImage('1625772299848-391b6a87ff7e'),
  },
  {
    name: 'Fresh Red Apples Premium 1kg',
    brand: 'Fresh',
    category: 'Fresh Produce',
    unit: 'kg',
    price: 300,
    cost_price: 210,
    stock: 45,
    sku: 'SM-APL-KG',
    image_url: stockImage('1560806887-1e4cd0b6faa6'),
    domain_data: { is_weight_item: true },
  },
  {
    name: 'Frozen Sweet Corn 1kg',
    brand: 'Fresh',
    category: 'Frozen',
    unit: 'pack',
    price: 320,
    cost_price: 250,
    stock: 70,
    sku: 'SM-CORN-1K',
    image_url: stockImage('1574484284002-952d924569c8'),
  },
  {
    name: 'Brooke Bond Supreme 200g',
    brand: 'Brooke Bond',
    category: 'Beverages',
    unit: 'pack',
    price: 380,
    cost_price: 310,
    stock: 100,
    sku: 'SM-BRB-200',
    image_url: stockImage('1556679343-5493566d3e7b'),
  },
  {
    name: 'Ruffles Cheddar & Sour Cream',
    brand: 'Ruffles',
    category: 'Snacks',
    unit: 'pack',
    price: 110,
    compare_price: 130,
    cost_price: 78,
    stock: 130,
    sku: 'SM-RUF-CHD',
    image_url: stockImage('1621939514649-280e2ee25f60'),
  },
];
